### ISSUE TITLE
add preview in readme

### ISSUE THREAD

**Issue by parth181195** [bdlukaa/fluent_ui#1]
it would be much easier for people to have kind of brief  preview for the package in readme like screenshots and gif.if u get time please consider adding it

**Comment by bdlukaa** [comment]
I have thought of that but I haven't found any good way to record the screen and transform the video in a gif. Screenshots are planned for the next versions, whenever the theme api gets stable (probably 0.0.4)

**Comment by parth181195** [comment]
Thanks for it I tried the package and got the idea why u didn't add screenshot.

**Comment by parth181195** [comment]
Are u looking for help I was thinking about similar package I can submit prs if u don't mind

**Comment by bdlukaa** [comment]
> I can submit prs

Pull requests are welcome :)

> Screenshots are planned for the next versions

The screenshot in readme will probably look like this:
![](https://docs.microsoft.com/en-us/windows/uwp/design/style/images/color/windows-controls.svg)

But for that, there is a long path:
- Get dropdown button working
- Update ToggleSwitch disabled states

Currently, only the following controls are stable:
- `Checkbox`
- `RadioButton`
- `Button`

**Comment by bdlukaa** [comment]
Just release a new version that fixes this issue: [v0.0.5](https://pub.dev/packages/fluent_ui)

**Comment by parth181195** [comment]
any way i can dm u directly?
