### ISSUE TITLE
🐛 Buttons use wrong padding

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#1010]
The padding used in buttons is too small (compared to WinUI 3 Gallery) resulting in an overall smaller button:

![Button_Padding](https://github.com/bdlukaa/fluent_ui/assets/103884835/0a702fd2-5ae7-4513-8942-01bbfae82d53)
(left: fluent_ui, right: WinUI 3 Gallery)

**Comment by bdlukaa** [comment]
The `Button` widget use the same padding specified by microsoft.

* https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/inputs/buttons/button.dart#L3-L8
* https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/1.4-stable/controls/dev/CommonStyles/Button_themeresources.xaml#L116
