### ISSUE TITLE
[Proposal] NavigationPane needs to have style property.

### ISSUE THREAD

**Issue by takifouhal** [bdlukaa/fluent_ui#102]
`NavigationPane`  needs to have `NavigationPaneThemeData style` property to use custom style when needed, because it might be used multiple times :
- globally,  to navigate between top level panes.
- within a pane,  to navigate between sub panes.

So assuming that the widget will be used once isn't a good idea , because sub navigations is a common thing.

**Comment by bdlukaa** [comment]
In recent Windows 11, most apps use inner navigation within the same Navigation Pane. You can see that on the Settings app, for example. Even mobiles apps have been using this approach for a while, such as Instagram.

If you need custom navigation, you may need to do it yourself
