### ISSUE TITLE
i want a detailed doc,such how can successfully build and run my own hello world,i am new to flutter i can not do that by now doc

### ISSUE THREAD

**Issue by LanHuangJG** [bdlukaa/fluent_ui#1021]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bdlukaa** [comment]
There are plenty of articles and tutorials out there on the internet that can help you. As a single maintainer of the package, I can not write detailed docs for beginners.
