### ISSUE TITLE
TabView - expose tab border color and tab selected color

### ISSUE THREAD

**Issue by AlastairOZ** [bdlukaa/fluent_ui#1024]
I have a suggestion for the TabView

It would be nice if you could expose the tab border color  and tab selected color 

In _tab class: 

            decoration: BoxDecoration(
              borderRadius: borderRadius,

              // if selected, the background is painted by _TabPainter
              color: widget.selected ? null : backgroundColor,
            ),

Suggested change:

            decoration: BoxDecoration(
              borderRadius: borderRadius,
              border: Border(
                top: BorderSide(color: widget.tabBorderColor ?? Colors.transparent),
                left: BorderSide(color: widget.tabBorderColor ?? Colors.transparent),
                right: BorderSide(color: widget.tabBorderColor ?? Colors.transparent),
              ),
              // if selected, the background is painted by _TabPainter
              color: widget.selected ? widget.tabSelectedColor : backgroundColor,
            ),

**Comment by bdlukaa** [comment]
We provide the `Tab.outlineColor`, which is the border color. You can override the `Tab` widget and provide your custom widget as the tab. See #1050
