### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by selvam920** [bdlukaa/fluent_ui#103]
/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fluent_ui-3.4.1/lib/src/controls/form/selection_controls.dart(35,52): error G366B1FB5: Too few positional arguments: 2 required, 1 given. [C:\Users\Jack Selvam\Downloads\fluent_ui-master (1)\fluent_ui-master\example\build\windows\flutter\flutter_assemble.vcxproj]

Flutter 2.6.0-12.0.pre.825 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6a3ea7eb83 (27 hours ago) • 2021-11-23 17:38:02 -0800
Engine • revision 635b4202d7
Tools • Dart 2.16.0 (build 2.16.0-38.0.dev) • DevTools 2.8.0

**Comment by WinXaito** [comment]
Confirmed, but only on master branch of Flutter. (2.6+), work on stable channel.

Linked to this commit: https://github.com/flutter/flutter/commit/33e261c0a2eb1f02b94c8fdfef092350c65b4d5c 

`handleCut`, `handleCopy`, etc. take now 2 arguments. But I think it's preferable to wait the update on the stable channel.

**Comment by WinXaito** [comment]
@bdlukaa how do you want manage that for have a non-break change ?

**Comment by bdlukaa** [comment]
@WinXaito wdym? The package is made to run on the stable channel. Once that commit reaches the stable channel we should upgrade

**Comment by WinXaito** [comment]
I didn't know if you maintain compatibility with older versions of Flutter or not. I just wanted to know.

**Comment by bdlukaa** [comment]
@WinXaito since Flutter Desktop is changing constantly, maintaining compatibility with older versions is surely not an option!

**Comment by whiplashoo** [comment]
It seems that this is now in stable (Flutter 2.8.0). I am getting the same error trying to run a build.

**Comment by WinXaito** [comment]
Have you updated flutter and fluent ? (3.5.0)

getting exact same error ?

**Comment by whiplashoo** [comment]
Works fine now (Flutter 2.8.0 and fluent_ui 3.5.0). Probably a cache issue for me? 

Feel free to close.
