### ISSUE TITLE
🐛 Maximized fluent_ui app prevents automatically hidden taskbar from appearing

### ISSUE THREAD

**Issue by roman-yepishev** [bdlukaa/fluent_ui#1030]
**Description**

When Explorer shell Taskbar is set to "Automatically hide", apps using `fluent_ui` maximize their window in a way that prevents taskbar from appearing when the mouse is moved to screen edge where taskbar is supposed to pop up.

**To Reproduce**
1. Enable "Automatically hide the taskbar" in Taskbar Settings on Windows 11, "Automatically hide the taskbar in desktop mode" on Windows 11.
2. Run the `example` fluent_ui app.
3. Maximize the app window.
4. Move the mouse to the edge of the screen where the taskbar was docked to.

**Expected behavior**
Taskbar appears.

**Screenshots**
Taskbar does not appear.

**Additional context**

When the app is maximized, the thin line showing the taskbar is not displayed (as if the app hinted to the system that is a full screen app). The workaround is to press Windows+T or Windows+B to bring the focus to the taskbar or the notification area.

flutter example app delegating window chrome drawing to Windows DWM maximizes correctly. Tested on the example app and the [Shortcut Keeper](https://shortcutkeeper.com/windows.html).

Tested on fluent_ui rev 9c0840 under Windows 10 22H2, Windows 11 23H2 on an amd64 platform with Flutter 3.19.1 (stable).

**Comment by damywise** [comment]
This is a problem with the plugin window_manager, not fluent_ui

**Comment by roman-yepishev** [comment]
Indeed, this is https://github.com/leanflutter/window_manager/issues/438.
