### ISSUE TITLE
DataTable or the equivalent in the package

### ISSUE THREAD

**Issue by daumienebi** [bdlukaa/fluent_ui#1031]
I have been exploring the package and i want to say thanks for all those who contributed in putting this package together. After going through the documentation and searching online, i couldn't find a way of directly using a datatabe or any sort of table to display data without importing the `material.dart` file. I tried to use the datatable2 package but it needs a Material Widget above it.

The error i got was: 

![image](https://github.com/bdlukaa/fluent_ui/assets/90214727/a91e7a4d-2ca3-4cca-8f64-24d931fd0d30)

I would like to know if there is any solution integrated with this package since i couldn't find it in the documentation and if there is, i would like it to be documented.

I created a custom class for the datatable and wrapped it with a Scaffold since the Scaffold contains Material as indicated in the error message.

![image](https://github.com/bdlukaa/fluent_ui/assets/90214727/13bcdbb9-34b9-402a-95ac-efbf2bcee824)

**Comment by bdlukaa** [comment]
We do not have support data table in the package. See #514.

To fix the error stated, use a `Material` widget from the `flutter/material` package above your widget tree. This library is not automatically compatible with all material widgets.

**Comment by daumienebi** [comment]
Alright, thanks for your time 👍
