### ISSUE TITLE
🐛 To close Flyout after MenuFlyoutSubItem press.

### ISSUE THREAD

**Issue by web-liuyang** [bdlukaa/fluent_ui#1037]
**Describe the bug**
When `SubItemShowBehavior.press` is used, the sub-items will not be displayed, and the current Flyout will be closed

**Expected behavior**
show sub-items

**Screenshots**
file: `lib/src/controls/flyouts/menu.dart`

<img width="605" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/52391595/ebc939cb-64b1-48df-b39c-6a75de1e524f">

<img width="545" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/52391595/a7e21d8f-b388-4cce-a643-096b130cba6f">

**Comment by bdlukaa** [comment]
To show the items, you just need to hover the item.

**Comment by web-liuyang** [comment]
> To show the items, you just need to hover the item.

I want to use the press method, click on item and it disappears
