### ISSUE TITLE
🐛 Slider handle overflows or gets cut off

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#1038]
The slider's handle overflows its parent by about 11 pixels and thus might get cut off when it's at the minimum or maximum position:
![slider_fluent_ui](https://github.com/bdlukaa/fluent_ui/assets/103884835/16f6cecd-751d-475f-a1cb-8d05047e68ed)
![slider_cut_off](https://github.com/bdlukaa/fluent_ui/assets/103884835/7b343839-d27b-47ad-b7be-b506a2db7030)

**Additional information:**
In Material this is aparently prevented by indenting the entire slider on both sides to leave enough room for the handle.
![slider_material](https://github.com/bdlukaa/fluent_ui/assets/103884835/bf79d7fd-c60a-46da-89dd-de23c4df44d1)

The slider shown in WinUI gallery prevents overflowing by not allowing the handle to move as far: The handle stops as soon as its outer ring touches the end of the slider bar:
![slider_winUI](https://github.com/bdlukaa/fluent_ui/assets/103884835/ec7a1d4f-d957-499f-bd77-5a1a1a9cbacc)

The latter has the advantage of a cleaner layout: The slider bar uses the entire width that the `Slider` widget needs and thus aligns neatly with other form elements.

**Expected behaviour:**
The slider handle (knob) does not overflow its parent. And ideally reproduces the behaviour seen in WinUI gallery.

**Comment by bdlukaa** [comment]
We use material's `Slider` under the hood of `Slider`. We use a "hack" to remove the indentation on the slider sides (which is added by default on the material Slider), trying to mimic the native slider behavior.

To fix this issue, the offset of the knob would need to be evaluated to proper align the thumb:
https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/inputs/slider.dart#L429-L554

A workaround is to add a padding (6px horizontally) onto the Slider.

**Comment by robkri** [comment]
Yes, this is how I'm doing it currently. Although I need 11.0 pixels padding.
