### ISSUE TITLE
Add an ActionItem for NavigationPane

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#104]
Is there a way to perform an action from the NavigationPane (for example a "logout" action)?

If there is no possibility to do this, would it be possible to have an "ActionItem" in addition to the "PaneItem" allowing to execute a simple action when clicking on the button without having to change the pane.

![image](https://user-images.githubusercontent.com/8223773/143410610-bdeb201e-0f97-434b-8748-a868af4b28f0.png)

**Comment by bdlukaa** [comment]
You can use the `onChanged` to perform it:

```dart
onChanged: (i) {
  if (i == 3) // where 3 is your item index
      ; // perform your action
  else
      setState(() => index = i);
},
```

**Comment by WinXaito** [comment]
Yup

The only disadvantage is that if we do this on an item in the middle of the list, we are forced to have a "fake" widget in the list of items so we don't have to do index calculations.

But it's ok for me with this solution. Thanks

**Comment by bdlukaa** [comment]
Reopening as a valid request!
