### ISSUE TITLE
EditableComboBox - add inputFormatters

### ISSUE THREAD

**Issue by dungnguyen2703** [bdlukaa/fluent_ui#1041]
When I use EditableComboBox, if user input by keyboard instead of our list. In some case we need to use inputFormatters to make user input as our format only.

Thank you

**Comment by bdlukaa** [comment]
I don't understand the issue. Could you explain it better?

**Comment by dungnguyen2703** [comment]
Hi, I need something like this:

EditableComboBox<T>(
  onTextChanged: ,
  onFieldSubmitted:,
  value: ,
  placeholder: ,
  onChanged:,
  items: ,
  inputFormatters: , // add this like textbox have
),

Thanks
