### ISSUE TITLE
🐛 Slider cannot be moved sometimes 

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#1044]
**Describe the bug**
Sometimes when the slider knob is at one of the slider bar's ends it cannot be moved anymore. As you can see from the screenshot, on hovering the knob, it reacts at first but then appears to be "unhovered" - although the mouse pointer is still on top of the knob. The knob cannot be moved by dragging then.
![slider_undragable](https://github.com/bdlukaa/fluent_ui/assets/103884835/bd5f3e78-abed-4d8c-9338-ecaa9d32c7c9)

**To Reproduce**
1. Go to fluent_ui showcase and move the slider to one of the very ends of the bar. 
2. Move the mouse pointer over the knob a couple of times. It may take some tries but sooner or late it won't react in the expected way.

**Comment by dev-aniketj** [comment]
I started work on it, sounds good for me.

**Comment by bdlukaa** [comment]
Can you still reproduce this issue on the latest version?

**Comment by robkri** [comment]
Using v4.8.7 I cannot reproduce this issue anymore apparently.

**Comment by bdlukaa** [comment]
Thanks. It was fixed by #1046
