### ISSUE TITLE
🐛 Unknown trigger system sound

### ISSUE THREAD

**Issue by rainonline** [bdlukaa/fluent_ui#1048]
**Describe the bug**
In `ScaffoldPage`，areas not covered by components, mouse click triggers system sound。

**To Reproduce**
For example, in the demo example：
<img width="1517" alt="PixPin_2024-03-30_17-31-10" src="https://github.com/bdlukaa/fluent_ui/assets/16534596/4719c19d-8b5e-4e50-ba59-b329688fa9a2">

<img width="1537" alt="PixPin_2024-03-30_17-41-47" src="https://github.com/bdlukaa/fluent_ui/assets/16534596/7401434e-d4ec-4db7-b1e4-1b3c95ad74a6">

<img width="952" alt="PixPin_2024-03-30_17-43-20" src="https://github.com/bdlukaa/fluent_ui/assets/16534596/dc4cbab5-60be-4ad0-9b11-3427d20a973b">

**Comment by RemarkIt** [comment]
Hi, I am running into the same issue, is there any progress or a known workaround?

**Comment by rainonline** [comment]
I use widget to cover it
