### ISSUE TITLE
acrylic navigationview

### ISSUE THREAD

**Issue by andreshark** [bdlukaa/fluent_ui#1052]
I would like to see the ability to do transparency navigationview.
Example:
![image](https://github.com/bdlukaa/fluent_ui/assets/137806754/70711a51-4781-4851-a81d-160dda4cde37)

**Comment by bdlukaa** [comment]
This is beyond the scope of this package. We only provide UI controls. Having control of the window should be done on the native side. There are packages, such as [`flutter_acrylic`](https://pub.dev/packages/flutter_acrylic) that do this job.

On the example app, you can change the window transparency on the `Settings` page. When enabled, it makes the navigation view background color transparent and trigger the `flutter_acrylic` APIs.
