### ISSUE TITLE
🐛 Invalid font set in theme

### ISSUE THREAD

**Issue by linb1111111** [bdlukaa/fluent_ui#1058]
When I set the font in the theme, it didn't work, but styling the Text directly did

**Comment by bdlukaa** [comment]
Sorry, but I can not reproduce it locally.

```
FluentApp(
  theme: FluentThemeData(
    fontFamily: 'Arial',
  ),
)
```

Before:

![image](https://github.com/bdlukaa/fluent_ui/assets/45696119/a3ba8a36-4d5c-4f9a-8468-df6c9ddb146a)

After:

![image](https://github.com/bdlukaa/fluent_ui/assets/45696119/3f05e62c-ff06-4785-860a-8be22e55d4eb)
