### ISSUE TITLE
🐛 Handle enter click in a NumberBox and add onEditingComplete event

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#1060]
**Describe the bug**
When a `NumberBox` has the focus, a click on `enter` should exit the focus.

It would also be great to add `onEditingComplete`.

**Comment by bdlukaa** [comment]
I just debugged the issue and noticed that `onEditingComplete` is being the root of the issue. We provide it internally, but when not provided the Enter key exists the focus. `onEditingComplete` also overrides the default behavior of handling according to the `TextInputAction`.
