### ISSUE TITLE
🐛 Weird effect when a ComboBox is inside a SizedBox

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#1066]
**Describe the bug**
Put a ComboBox in a SizedBox, the content is based on the bigger element inside, instead of the real size of the combobox.

![image](https://github.com/bdlukaa/fluent_ui/assets/8223773/2f08f731-ae03-4412-8a46-1021d29d5cdf)

**Comment by bdlukaa** [comment]
Can you provide a reproducible snippet?

**Comment by WinXaito** [comment]
```dart
          SizedBox(
            width: 200,
            child: ComboBox(
              value: 1,
              items: const [
                ComboBoxItem(
                  value: 1,
                  child: Text('Val 1'),
                ),
                ComboBoxItem(
                  value: 2,
                  child: Text('Val 2'),
                ),
              ],
              onChanged: null,
            ),
          ),
```

Give this:

![image](https://github.com/bdlukaa/fluent_ui/assets/8223773/222353ed-8ad1-47c2-8d46-4031a31142a7)

I would expect to have `Val 1` on the left, and the chevron at the right.


Is it okay with that or you need a full reproductible project ?

**Comment by itzhoujun** [comment]
same issue

**Comment by WinXaito** [comment]
Okay my bad, I wanted to fix that but I saw the parameter `isExpanded`, when I change it to `true`, that fix this issue.

I don't know, maybe there is a way to detect automatically if the expand should be applied or not. But at least I can fix the render in my app by using `isExpanded: true`.

**Comment by WinXaito** [comment]
Okay, so since the parameters `isExpanded` fixed my problem. I think we can close this.
