### ISSUE TITLE
Ability to add common interactive implementations for multi-window applications

### ISSUE THREAD

**Issue by kuloud** [bdlukaa/fluent_ui#1073]
**Is your feature request related to a problem? Please describe.**
In multi-window desktop applications, pin / unpin or maximizing a subpage is needed, could you support a common implementation with CommondBar.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="256" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/2024271/db92ec9d-5717-4c39-87b8-b1997ed9bdaf">

**Comment by bdlukaa** [comment]
I'm not sure this is part of the official implementation.

We only provide controls and a few helper widgets used widely. This can be a custom widget of yours.
