### ISSUE TITLE
🐛 Scrollbar, disappear when the mouse is not over

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#1077]
**Describe the bug**
I'm not that sure if it's a problem with Fluent_ui or Flutter.  
The scrollbar tend to disappear when the mouse move (so almost everytime I scroll, it's hard to grab the bar and it disappear).

Also, maybe it's another bug, but if I go over the scrollbar, it appear, and after that if I scroll with the mouse wheel, it stay appeared.
But wait a couple of second, the bar disappear, scroll with mouse will, you'll not see the bar again.

![scroll](https://github.com/bdlukaa/fluent_ui/assets/8223773/483a9c1c-30fc-4348-8282-7378b35a6386)

**Comment by bdlukaa** [comment]
I think it is an issue with Flutter's `RawScrollbar`, but it is resolvable using the callbacks they expose.

We hide the scrollbar as soon as the mouse leaves it, but we don't take into account if the user is still pressing it. https://github.com/bdlukaa/fluent_ui/blob/5d756dbb91d1b37b40bc1f795047e4adebefcdef/lib/src/controls/utils/scrollbar.dart#L140-L184
