### ISSUE TITLE
🐛 TextBox is unfocussable

### ISSUE THREAD

**Issue by M-Ahal** [bdlukaa/fluent_ui#1083]
**Describe the bug**
The `TextBox()` widget does not focus on tap, and also is non-editable because of it. The Flutter-Inspector, shows it's FocusNode as 'NOT FOCUSABLE'

**To Reproduce**
Minimal Reproducible example
1. Create a new Flutter project with windows as a platform
2. Use `fluent_ui: ^4.9.0` as a dependency
3. Overwrite main.dart with the attachment (main.txt because of Github upload policy)
[main.txt](https://github.com/user-attachments/files/16143997/main.txt)
4. Run the application, and try clicking on the TextBox()

**Expected behavior**
Tapping the TextBox() widget, should bring the focus on that widget and make it editable

**Screenshots**
https://github.com/bdlukaa/fluent_ui/assets/132486634/4d348ce7-4ec0-46cf-9306-3d1a84395b9e

**Additional context**
I was orgininally using this widget as part of the `PlatformTextField` from [flutter_extended_platform_widgets](https://pub.dev/packages/flutter_extended_platform_widgets). I reproduced this on Android, and managed to resolve it with some SO isssue, by adding `keyboardType: TextInputType.text`. But that is not available for this platform. The issue logged was something to do 'Cannot have 0 span ...', but no log from this package

**Comment by M-Ahal** [comment]
If I replace the pane with content, then it works as expected:
```dart
return NavigationView(
      appBar: const NavigationAppBar(),
      content: TextBox(
        placeholder: 'Name',
        expands: false,
        autofocus: true,
        autocorrect: false,
        onTap: () => debugPrint('does detect tap'),
        onChanged: (value) => debugPrint('does not detect change: $value'),
      ),
      // pane: NavigationPane(
      //   items: [
      //     PaneItem(
      //       icon: const Icon(FluentIcons.add),
      //       title: const Text('Add'),
      //       body: const _TextFieldPage(),
      //     ),
      //   ],
      // ),
    );
```
So the problem seems to be with the `pane`

**Comment by thomaskim09** [comment]
I am experiencing this issue as well, and it is quite severe. I rely on a significant number of text boxes within the navigation pane body, which are now affected. Could we please have this issue prioritize? 🥲🥲

**Comment by WinXaito** [comment]
Just add this `selected: 0,` on `NavigationPane` and it works back.

I don't really know why. But you selected should not be null or you should use `content` instead of `items`.

I think it could be documented, but not necessarily need a fix (especially if it's tricky).

**Comment by thomaskim09** [comment]
@WinXaito Thanks! It fixed the issue after adding the `selected: 0`. Wishing you all a great day ahead!
