### ISSUE TITLE
Create `PaneItemWidget`

### ISSUE THREAD

**Issue by md-rifatkhan** [bdlukaa/fluent_ui#1087]
**Custom Navigation Pane Widget**
It will better to support custom navigation pane widget.

Because sometime we need to add slider or custom button on navigation view

**Comment by bdlukaa** [comment]
You can create a `PaneItem`, just as you would create a widget.

https://github.com/bdlukaa/fluent_ui/blob/0b712766bbf4e81eaa50803e07afb7c8b11ba969/example/lib/main.dart#L665-L701

Note that it behaves as a pane item, and it has an index.

The creation of a `PaneItemWidget` would be a good addition.
