### ISSUE TITLE
Theming buttons and pane items

### ISSUE THREAD

**Issue by alesimula** [bdlukaa/fluent_ui#111]
Hello, I was trying this library together with the flutter_acrylic library, and I tried to apply an "app-wide" mica effect.

I got some pretty decent results, but encountered some limitations, especially when trying to theme elements like buttons, pane items, text input boxes etc..

![image](https://user-images.githubusercontent.com/3057584/144726956-6fe8d634-83de-48bb-befc-0f6c7ed33c8b.png)

It isn't clear whether it is possible to chage these colors, in the specific case of pill buttons and pane items I wanted to use a translucent shade of white for dark theme and a translucent shade of gray for light theme instead of the default opaque colors.

**Comment by bdlukaa** [comment]
You can use the `style` property. https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/inputs/buttons/button.dart#L22

**Comment by alesimula** [comment]
@bdlukaa That doesn't help me with pane items though (I used those for the elements on the screenshot above)

It's also not clear how button states work, I've tried to change the button theme globally, but I'm only able to change it to a static unchanging color (I'd like to change the disabled, enabled, hover and pressed colors separately, or at least change them by a delta of the default color), what should I do

```
return FluentApp(
    theme: ThemeData(
        buttonTheme: ButtonThemeData(
            defaultButtonStyle: ButtonStyle(
                backgroundColor: ButtonState.all(Colors.transparent.lerpWith(Colors.black, 0.2))
            ),
        ),
        [...]
    )
)

```

**Comment by bdlukaa** [comment]
For `PaneItem`s, you can extend them and override the `build` method. An example of this can be the [`PaneItemSeparator`](https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/pane_items.dart#L214-L250)

For buttons, you can use `ButtonState.resolveWith`:

```dart
```

**Comment by alesimula** [comment]
@bdlukaa But in order to extend PaneItem and make it look and behave exactly like the PaneItem widget I should copy the whole build method from PaneItem (which is extensively longer), and other than being a little unpractical, the method uses a private class which I have no way to call ( _NavigationBody.maybeOf(context)?.displayMode ); it might still be a viable solution in my case as I don't need to get the current navigation view display mode, but I propose making this element themable (or at least calling an extensible method to apply the style)

**Comment by bdlukaa** [comment]
I agree with you that theming buttons and pane items should be easier.

**Comment by bdlukaa** [comment]
> Speaking of the Expander widget, it seems to have a black line border (on dark theme) similar to what I reported for the navigation bar, looks way better with white theme

I try to replicate everything in the native `Expander`, and the middle bar is there as well.

**Comment by alesimula** [comment]
@bdlukaa I know but (and this might just depend on the 125% or higher scaling) the lines are less noticeable in the native Expander, so I think if you can't find a way to prevent the lines scaling up, using a colour closer to the background (like in the white theme) or a translucent black colour would make it look better (and actually closer to the original)

**Comment by alesimula** [comment]
@bdlukaa BTW I've made an expander that looks like the Windows 11 settings' expander

Feel free to kang it :P 

https://github.com/alesimula/wsa_pacman/blob/main/lib/widget/fluent_expander.dart

![image](https://user-images.githubusercontent.com/3057584/145446331-79492959-b749-4ca6-8e2a-82f5b5b089ca.png)

**Comment by alesimula** [comment]
@bdlukaa I made a card widget using the expander as a base, and also updated the background color method (disabled color is now the same as the default color), again, I'd love to see that in this library :D

https://github.com/alesimula/wsa_pacman/blob/main/lib/widget/fluent_card.dart
