### ISSUE TITLE
🐛 The EditableComboBox is missing the part where it applies the style to the TextBox.

### ISSUE THREAD

**Issue by hanwha-cheoldong** [bdlukaa/fluent_ui#1119]
**Describe the bug**
The EditableComboBox is missing the part where it applies the style to the TextBox.

**Expected behavior**
The font size in the TextBox is currently fixed. 

**Screenshots**
line to 167

![스크린샷 2024-09-19 오후 5 01 22](https://github.com/user-attachments/assets/c4e3f2e1-8ef0-403b-9aeb-05bdb69a745a)

**Comment by bdlukaa** [comment]
Fixed by #1121
