### ISSUE TITLE
🐛 Strange effect when opening a compact NavigationPane

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#112]
**Describe the bug**
 Strange effect when opening a compact NavigationPane

And on the example App, we had the following error: (Maybe not directly linked to this bug).

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 20 pixels on the right.
```

**To Reproduce**

See on the example app.

**Expected behavior**

Smooth open.

**Screenshots**

![fluent_ui_panebug](https://user-images.githubusercontent.com/8223773/145468599-ec7c6e11-ae4e-489f-9865-747922d73675.gif)

-------------------

In fact, I think that come from the "Overflow" rectangle shown by Flutter in debug Mode. Not tested in Release.

But we always had an weird effect when `open` to `compact`.

**Comment by bdlukaa** [comment]
It's caused by the info badge

**Comment by pasleto** [comment]
Hi, this bug is still there. Either for trailing or infoBadge on PaneItem and PaneItemExpander.

**Comment by bdlukaa** [comment]
@pasleto can you post here the result of your `flutter doctor -v`? Also, what version of fluent_ui are you using?

**Comment by pasleto** [comment]
fluent_ui: ^4.0.1

[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale cs-CZ)
    • Flutter version 3.3.2 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (3 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4345.14

[√] VS Code (version 1.72.0)
    • VS Code at C:\Users\tomas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 106.0.5249.91
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 106.0.1370.34

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
