### ISSUE TITLE
🐛 AutoSuggestionBoxItem Height renderer overlay.

### ISSUE THREAD

**Issue by DevMensIT** [bdlukaa/fluent_ui#1133]
how to change height or with of AutoSuggestBoxItem ?
![image](https://github.com/user-attachments/assets/a06349b6-2bb7-4735-845e-42d6f5c340b5)

**Comment by bdlukaa** [comment]
You can provide your own `AutoSuggestBox.itemBuilder`. There you can build the tiles how you want, as well as customizing padding, height, colors and other stuff. It can be any widget. Please refer to the documentation. Thanks.

**Comment by DevMensIT** [comment]
> You can provide your own `AutoSuggestBox.itemBuilder`. There you can build the tiles how you want, as well as customizing padding, height, colors and other stuff. It can be any widget. Please refer to the documentation. Thanks.


while using itemBuilder problem is  not showing current selection item while using customizing.
