### ISSUE TITLE
[Feature Request] Add extra mouse callbacks for `TabView`'s `Tab`

### ISSUE THREAD

**Issue by diluculo** [bdlukaa/fluent_ui#1138]
Add built-in context flyout support to Tab items in TabView to provide quick access to tab operations.

![image](https://github.com/user-attachments/assets/81aaa9f0-011a-4bec-8a92-211f3bfe04d9)

### Example Usage
````dart
Tab(
  text: const Text('Tab 1'),
  body: Container(),
  flyoutItems: [
    FlyoutMenuItem(
      text: const Text('Close'),
      onPressed: onClosed,
    ),
    FlyoutMenuItem(
      text: const Text('Close Others'),
      onPressed: () {
        // Handle close others
      },
    ),
    FlyoutMenuItem(
      text: const Text('Rename'),
      onPressed: () {
        // Handle rename
      },
    ),
  ],
  onClosed: () {
    // Handle tab close
  },
)
````

**Comment by diluculo** [comment]
I'm uncertain about the standard approach for handling context menus in Flutter. Perhaps using `GestureDetector.onSecondaryTapUp` for desktop app and `onLongPress` for web app might work.

**Comment by bdlukaa** [comment]
Unfortunately we do not implement extra features that are not present in the native implementation. On the native TabView, this isn't implemented by default - and is always implemented by the software itself. Each browser has its own Flyout implementation on the tabs.

We currently do not expose the `onSecondaryTap` and `onLongPress` callbacks for the `Tab` widget, but it can be easily added by extending the `Tab` class and creating your own tab implementation.

```dart
final MyCustomTab extends Tab {

  MyCustomTab({
    super.key,
    required super.body,
    required super.text,
  });
  
  @override
  State<Tab> createState() => MyCustomTabState();

}

class MyCustomTabState extends TabState {

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onSecondaryTap: () { ... },
      onLongPress: () { ... },
      child: super.build(context),
    );
  }

}
```

I am making this a request to add extra action callbacks to the `Tab` widget.
