### ISSUE TITLE
🐛 Resize image

### ISSUE THREAD

**Issue by ajxcodergit** [bdlukaa/fluent_ui#1145]
Hi, I'm using quill to insert images. But when I resize the image (especially after uploading it via Delta) it doesn't work or creates too much space. I'd like to know how to solve it. Thanks,

**Comment by bdlukaa** [comment]
I'm sure this isn't the place to file this kind of issues. Please report problems or request features in this space. Try asking on stackoverflow with some more details. Thanks.
