### ISSUE TITLE
🐛 NumberBox when max changed, and setState(). Duplicate GlobalKey detected in widget tree.

### ISSUE THREAD

**Issue by git-boya** [bdlukaa/fluent_ui#1146]
**Describe the bug**
Duplicate GlobalKey detected in widget tree.

**To Reproduce**
```
SizedBox(
      width: 120,
      child: NumberBox(
        value: ConfigLogic.to.config.value.maxTask,
        min: 1,
        max: logic.cpuCoreCount,
        mode: SpinButtonPlacementMode.inline,
        clearButton: false,
        onChanged: (value) {
          if (value == null) return;
          ConfigLogic.to.config.update((val) => val?.maxTask = value);
          ConfigLogic.to.save();
        },
      ),
    )
```
change cpuCoreCount and setState()

**Screenshots**
![image](https://github.com/user-attachments/assets/a431db3a-61e7-476e-b93d-5e1199e5a044)

**Additional context**

**Comment by WinXaito** [comment]
Hello,

I tried, but I'm unable to reproduce:

```dart
NumberBox(
  value: 1,
  min: 1,
  max: viewModel.max,
  mode: SpinButtonPlacementMode.inline,
  clearButton: false,
  onChanged: (v) {
    viewModel.value = v;
  },
),
Button(child: Text('Change max'), onPressed: (){
  viewModel.max += 1;
}),
```

And in my viewModel:

```dart
int _max = 2;
int get max => _max;
set max(int v) {
  _max = v;
  notifyListeners();
}
int _value = 1;
int get value => _value;
set value(int? v) {
  _value = v ?? 1;
  notifyListeners();
}
```

It works has expected without any errors:

![fluentui_numberbox](https://github.com/user-attachments/assets/0c9b4cd9-f62e-4ac5-86e8-272be9c25eaa)

----

So, I think your problem is caused by something else.
Otherwise, could you provide a minimal reproductible example ?

**Comment by WinXaito** [comment]
Okay.
If it still appear on Mac, you can give me a minimal reproductible example and I can also check on my mac.

**Comment by git-boya** [comment]
After restarting my computer, the problem no longer occurred. It should not be related to Fluent_ui, but rather some unknown reasons.
Thanks!
