### ISSUE TITLE
🐛 DatePicker display formatting issues

### ISSUE THREAD

**Issue by avensteven** [bdlukaa/fluent_ui#1158]
When I use DatePicker, it's not clear to me if these issues are caused by me not knowing how to use them, or if it's a bug? The questions are as follows:
1. I use AnimatedFluentTheme(child:GetMaterialApp(...)) fluent_ui I encountered a yellow double underscore in the text style, and while most of the problems can be solved by wrapping a Material component in the outermost part, DatePicker can't;The screenshot is as follows:
![image](https://github.com/user-attachments/assets/4a6085bd-fe73-4489-aaff-3a6b96870c7d)

3. I used the locale specified in DatePicker: const Locale('zh', 'CN'), why is the month of the date not a number? 
![image](https://github.com/user-attachments/assets/c34c2c36-5a3c-4447-be09-2e8190e450be)

5. I tried to adjust the contentPadding but it only works for the middle month, is this a bug? Why isn't the Month Date field auto-centered?

Here's how I use fluent_ui:
```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return AnimatedFluentTheme(
      data: FluentThemeData(
        accentColor: Colors.blue,
        scaffoldBackgroundColor: Colors.white,
      ),
      child: GetMaterialApp(
        debugShowCheckedModeBanner: false,
        localizationsDelegates: const [
          FluentLocalizations.delegate,
        ],
        supportedLocales: const [
          Locale('zh', 'CN'), 
        ],
        title: '应用平台',
        initialRoute: '/login',
        getPages: [
          GetPage(name: '/login', page: () => const LoginPage()),
          GetPage(
              name: '/home',
              page: () => const MyHomePage(),
              middlewares: [AuthMiddleware()]),
        ],
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Material(child: NavigationLayout());
  }
}
```

Here's how I use DatePicker:
```dart
Container(
  width: 180,
  child: DatePicker(
    contentPadding :const EdgeInsets.all(0),
    locale:const Locale('zh', 'CN'),
    selected: table.startDate.value,
    fieldFlex: const [5, 4, 4],
    onChanged: (time) =>
        setState(() => table.startDate.value = time),
  ),
),
```

Can any of expert tell me how to solve it?

**Comment by bdlukaa** [comment]
1. You need a `DefaultTextStyle` above the entire widget tree. `FluentTheme` alone doesn't add it. We recommend to use `FluentApp` instead of `MaterialApp` if you are making a fluent-styled app;
2. This is the default style of the `DatePicker`. Here is how it look like in English:
    ![English Date Picker](https://github.com/user-attachments/assets/c056f511-5971-4d66-bd3d-599d425c2686)
    The [intl package](https://pub.dev/packages/intl) is the package that provides us these translations.
3. You can use the `fieldOrder` and `fieldFlex` parameters to determine the other and the width of the fields.

**Comment by avensteven** [comment]
> 1. You need a `DefaultTextStyle` above the entire widget tree. `FluentTheme` alone doesn't add it. We recommend to use `FluentApp` instead of `MaterialApp` if you are making a fluent-styled app;
> 2. This is the default style of the `DatePicker`. Here is how it look like in English:
>    ![English Date Picker](https://private-user-images.githubusercontent.com/45696119/396182026-c056f511-5971-4d66-bd3d-599d425c2686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzcyMzIsIm5iZiI6MTczNDQzNjkzMiwicGF0aCI6Ii80NTY5NjExOS8zOTYxODIwMjYtYzA1NmY1MTEtNTk3MS00ZDY2LWJkM2QtNTk5ZDQyNWMyNjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEyMDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YmJkMzgzNjdmZWNkOTY0ZDg1OGMzM2JhNzkyNGM0Y2M2NmVmZmIyMzJhNTNlMGI2MDNiYjZlZjZjZjVkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N5rvpH_K-XOC3J36CCVCb7IL1UOGAe-Rn44wKRswJrY)
>    The [intl package](https://pub.dev/packages/intl) is the package that provides us these translations.
> 3. You can use the `fieldOrder` and `fieldFlex` parameters to determine the other and the width of the fields.

First of all, thank you very much for your patience!
1.I need to use some advanced features of getx, so I have to use GetMaterialApp, which I followed this #164 issue. Also, I tried your suggestion use DefaultTextStyle above the entire widget tree,but it didn't work.
2.I know what the default English style of this DatePicker looks like. The question I want to ask is why this "month" field can't be like this "2024年 12月 17日", but not "2024年 十二月 17日",
3.I'm not trying to emphasize the issue of internationalized translations in particular, but rather the issue of month field alignment for this DatePicker component. This "month" is always on the left and not in the center.

**Comment by bdlukaa** [comment]
1. Since you are using a material app, you need a `Material` widget above your app `Navigator`. You can use the `MaterialApp.builder` callback to achieve this.

2. I am afraid that is not possible. We rely on the `intl` package to provide us these translations.

3. Use `DatePicker.fieldOrder` to manipulate the order of the date picker. Use `DatePicker.fieldFlex` to determine the space each field will take.
