### ISSUE TITLE
Web demo hosted on GitHub pages?

### ISSUE THREAD

**Issue by roman-petrov** [bdlukaa/fluent_ui#12]
This library is a great addition to Flutter Material & Cupertino, thank you for such amazing work!

Currently to see it in action developers have to manually build & launch example app. It is even harder to show it to someone in the company: the application needs to be built and hosted somewhere.

Is it possible to host example app somewhere in Web (for example, on GitHub pages) to allow people to launch and see it in action just in a single button click?

**Comment by bdlukaa** [comment]
Yeah, you can deploy the example app to your github pages. See [deploying to the web](https://flutter.dev/docs/deployment/web#deploying-to-the-web)

**Comment by roman-petrov** [comment]
@bdlukaa, sure, I understand that I can deploy web app myself to **my** GitHub pages. I am asking about publishing web demo / storyboard on your GitHub pages to allow everyone to try Flutter Fluent UI in action in just a mouse click, not just see static screenshot images. 

Please feel free to just close this request if this gives no value to the package.

**Comment by bdlukaa** [comment]
I created a web version of this that can be accessed at https://bdlukaa.github.io/fluent_ui. Unfortunately it renderer is not as good as windows' renderer.

**Comment by roman-petrov** [comment]
@bdlukaa thank you! I think web rendering will improve in Flutter in future.
