### ISSUE TITLE
New widget

### ISSUE THREAD

**Issue by antoniopetricc** [bdlukaa/fluent_ui#127]
👋🏻 There is a widget I would like to use in my app which is currently not present in fluent_ui. The component is https://docs.microsoft.com/en-us/fluent-ui/web-components/components/data-grid. Could you possibly add it? I would really appreciate it!

- [ ] DataGrid

 ![image](https://user-images.githubusercontent.com/52720679/148677477-54e425a8-37e3-436c-b58e-96a5af137459.png)

**Comment by bdlukaa** [comment]
This actually isn't something I'd add to the project since it's not related to windows UI.

See other packages like https://pub.dev/packages/syncfusion_flutter_datagrid to get this done
