### ISSUE TITLE
Harmonize the structure with for example MaterialApp widget for easy switch

### ISSUE THREAD

**Issue by richard457** [bdlukaa/fluent_ui#132]
Hello, first thank you for this amazing library

I have been looking around this and one drawback is that choosing to use this on the existing app will not work since it is a new structure completely different to `MaterialApp` for example, would love that this library has the same structure as `MaterialApp` as it will make adoption quite easy.

Thank you for your comments on this or considerations.

**Comment by bdlukaa** [comment]
Could you explain more? You mean `FluentApp` vs `MaterialApp`?

About fluent app and material app, their implementation is the same, with the same methods provided:

```dart
FluentApp( // Could easily be replaced by MaterialApp
  title: 'My App',
  initialRoute: ....,
  routes: ...,
  theme: ....,
  themeMode: ...,
);
```

**Comment by richard457** [comment]
I was wrong !
