### ISSUE TITLE
🐛 Wrong theme color (dark mode) on ReorderableListView

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#133]
**Describe the bug**
Wrong theme color (dark mode) on ReorderableListView. See gifs below

**Expected behavior**

Render with Material:

![fluent_bugreorder_material](https://user-images.githubusercontent.com/8223773/149329287-0888aa08-9908-4f35-9410-e595fec78644.gif)

**Screenshots**

Render with Fluent:

![fluent_bugreorder_fluent](https://user-images.githubusercontent.com/8223773/149329367-e7316b69-03bc-42b2-8c17-d4518070a1be.gif)

**Comment by bdlukaa** [comment]
Could you post a reproducible code sample?

**Comment by WinXaito** [comment]
Yup, https://gist.github.com/WinXaito/1e767b25e34a67561603a6b63db4b45b

(Just switch the comment in main function for use MaterialApp or FluentApp)
