### ISSUE TITLE
Lazy expansion of TreeView nodes

### ISSUE THREAD

**Issue by timsneath** [bdlukaa/fluent_ui#135]
Firstly, this package is _fantastic_. What an incredible piece of work. So grateful for your work.

**Scenario**
I have a `TreeView` where it's computationally expensive to calculate the nodes. So what I want is a callback that I can use to lazily populate a node when it's opened. I've solved this temporarily by forking your code and adding an `onExpanded` callback. I've also added a non-visual `PlaceholderTreeViewItem` that ensures the node is expandable, and when the callback is fired, I check whether the child is a `PlaceholderTreeViewItem`. If so, I clear the children and populate at that point. 

The solution I have is workable, but you may well have a better one. 
https://github.com/timsneath/regedit/blob/main/lib/custom_tree_view_item.dart

Example usage:
https://github.com/timsneath/regedit/blob/main/lib/registry_tree_view.dart

**Comment by bdlukaa** [comment]
I have thought of only populating nodes when it's opened. That was the first implementation, but then I faced an issue: when I select an item, then close a parent node, the selected node is messed and its state is not kept.

I don't see a reason to add nodes only when it's opened. Could you explain more?

**Comment by timsneath** [comment]
In the scenario above, I'm using it for a registry editor. There are hundreds of thousands of nodes in total, and so iterating them all in advance is not viable for performance reasons. This is quite a fairly common scenario for tree view controls, since they're often used as a control for very deep data sources (another example would be the folder structure of the C:\ drive). 

Other TreeView controls handle this with the approach above or with a command. For example:
https://help.syncfusion.com/winui/treeview/load-on-demand
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-improve-the-performance-of-a-treeview?view=netframeworkdesktop-4.8
https://yui.github.io/yui2/docs/yui_2.9.0_full/examples/treeview/dynamic_tree.html

**Comment by bdlukaa** [comment]
Interesting. Marking as a valid request. 

UI reference:

![Loading GIF](https://help.syncfusion.com/winui/treeview/LoadOnDemand_images/winui-treeview-on-demand-loading.gif)
