### ISSUE TITLE
Table solution

### ISSUE THREAD

**Issue by benboughton1** [bdlukaa/fluent_ui#136]
**Is your feature request related to a problem? Please describe.**
I am not sure what to use for tables. 
Most packages seem to rely on Material which conflicts with fluent_ui when imported. 

**Describe the solution you'd like**
Just some clear advice on what my options are, and solutions others have used. I need a full page table with checkboxes.

**Describe alternatives you've considered**
I've tried data_table_2 and pluto_grid. Both rely on Material.

**Additional context**
I am fairly new to flutter so apologies if there is a simple solution to this. Maybe importing the part of Material required to get these tables running?

**Comment by bdlukaa** [comment]
You can use the `as` keyword when importing:

```dart
import 'package:flutter/material.dart';
import 'package:fluent_ui/fluent_ui.dart' as fluent_ui;
```

When using anything from the package, use:

```dart
fluent_ui.Checkbox();
```

This way conflicts will be gone!

**Comment by benboughton1** [comment]
Great, thanks so much.
