### ISSUE TITLE
Whether flutter_ui supports MacOS?

### ISSUE THREAD

**Issue by jonahzheng** [bdlukaa/fluent_ui#137]
I'd like fluent_ui,
whether flutter_ui supports MacOS and ios?

![@N2YLD OC9HQE`35S7MOMMH](https://user-images.githubusercontent.com/5125282/150050632-13eef037-c032-4f13-bb0c-473c7d070be8.png)
https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart

**Comment by bdlukaa** [comment]
fluent_ui can run anywhere flutter can run.

This warning is about http://pub.dev/packages/system_theme
