### ISSUE TITLE
Get to know how to achieve some stuff with this library.

### ISSUE THREAD

**Issue by richard457** [bdlukaa/fluent_ui#140]
This is not a bug but asking how to add localization can be done.

**Comment by richard457** [comment]
also, how can I do something like Theme.of(context).canvasColor
and InkWell seems to be not pleasant

**Comment by bdlukaa** [comment]
Hello!

For the localizations, it's just the same as Material localizations:
```dart
FluentApp(
  localizationsDelegates: [
    // your localizations goes here
  ],
);
```

For the canvas color, there isn't such thing like this in fluent ui, but you can get the mica background color (which I think is equivalent):

```dart
FluentTheme.of(context).micaBackgroundColor;
```

*Sorry for the delay :)*

**Comment by henry2man** [comment]
@richard457 Take a look on https://github.com/bdlukaa/fluent_ui/pull/216, which is present on the shiny new 3.10.0 release
