### ISSUE TITLE
How do I disable automatic focus widget.

### ISSUE THREAD

**Issue by jonahzheng** [bdlukaa/fluent_ui#145]
Press the up,down, left and right keys on the keyboard, will cause the automatic focus widget.
How do I disable this feature.
![auto_focus](https://user-images.githubusercontent.com/5125282/151482252-315dae8f-0b1e-40f3-a271-f05c1529997b.gif)

**Comment by bdlukaa** [comment]
It can't be disabled!

<https://docs.flutter.dev/cookbook/forms/focus>

You'd have to create new widgets without the `Focus` widget. Why is it a problem?

**Comment by jonahzheng** [comment]
I only want disabled button focus.
I set autofocus is false, but is invalid.
ex:

```
              TextButton(
                **autofocus: false,**
                child: const Text('Text Button'),
                onPressed: disabled
                    ? null
                    : () {
                        print('pressed text button');
                      },
              ),
```

**Comment by bdlukaa** [comment]
You can try create a focus node with `canRequestFocus: false`.

```dart
final focusNode = FocusNode(canRequestFocus: false);

return TextButton(
  focusNode: focusNode,
);
```

Also, if the button is disabled (`onPressed` is null), the widget will be ignored in the focus scope

<https://api.flutter.dev/flutter/widgets/FocusNode/canRequestFocus.html>
