### ISSUE TITLE
Help with navigation

### ISSUE THREAD

**Issue by harilet** [bdlukaa/fluent_ui#146]
**How do I set default to expand in compact?**
![image](https://user-images.githubusercontent.com/40688601/151498134-1b114940-e830-4759-a512-a590400ff9ad.png)

**And prevent auto collapsing?**

![image](https://user-images.githubusercontent.com/40688601/151498602-214d8244-4073-44c6-9a76-c42978460af2.png)

**Comment by jonahzheng** [comment]
```
    final appTheme = context.watch<AppTheme>();
    appTheme.displayMode = PaneDisplayMode.compact;
```

**Comment by harilet** [comment]
Is there AppTheme inside fluent_ui or do I have to implement??

**Comment by jonahzheng** [comment]
https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/theme.dart

or set
NavigationPane(
  displayMode: PaneDisplayMode.compact
)

**Comment by harilet** [comment]
That is what I did, but the navigation does not keep expanded to always collapsed
![image](https://user-images.githubusercontent.com/40688601/151505665-ab7c2ad8-7814-4e71-9813-9987efbc78d9.png)
Clicked it expanded

![image](https://user-images.githubusercontent.com/40688601/151505722-77854ed3-a882-42c8-af13-9f5c48ac1996.png)
Go to another view automatically collapsed back

**Comment by bdlukaa** [comment]
It's the default platform behavior. When in compact mode, the user can press the button to open it. If the screen is too small, it's still opened as an overlay. You can see this behavior on multiple native windows apps, and on XAML Gallery, in which this library is based on. 

To disable the button, use the `menuButton` property in `NavigationPane`:

```dart
NavigationPane(
  ...,
  menuButton: const SizedBox.shrink(),
  ...,
);
```

**Comment by harilet** [comment]
Ok thanks, I got it
