### ISSUE TITLE
make tab bar view 

### ISSUE THREAD

**Issue by mayur-16** [bdlukaa/fluent_ui#147]
![deletethis](https://user-images.githubusercontent.com/95608212/151744253-b15eaf71-fe07-4f3c-a990-a6b19790c2c3.JPG)

i want tab bar view like native windows application like above image ,
 i dont want tab view .

i want navigation pane in left of screen

**Comment by bdlukaa** [comment]
This kind of control isn't implemented in the package.

There is a native control for it called [pivot](https://docs.microsoft.com/en-us/windows/apps/design/controls/pivot), but it's deprecated.

You can use material's TabBar for it
