### ISSUE TITLE
how to change splash color of button? 

### ISSUE THREAD

**Issue by mayur-16** [bdlukaa/fluent_ui#148]
seems simple but still i didn't get to know about it.. 
am using default button.
there is not splash color property inside ButtonStyle.

**Comment by bdlukaa** [comment]
There is no such thing as splash color in `Button`, that a Material thing. What you can do is customize the background color to your needs:

```dart
Button(
  style: ButtonStyle(
    backgroundColor: ButtonState.resolveWith((state) {
      if (state.isPressing) return ...;
      if (state.isHovering) return ...;
      ....
    }),
  ),
),
```

You can also customize the foreground color, shadow color, shape, and so on...
