### ISSUE TITLE
Fluent UI is incompatible with Flutter Material

### ISSUE THREAD

**Issue by BugsOverBugs** [bdlukaa/fluent_ui#150]
This package is great but it doesn't work in a single codebase with material.

As an example I want to build a custom class called `AdaptiveCheckbox`. This class decides which Checkbox should be used:

```
if(Platform.isWindows) return Checkbox(); //Fluent UI

if(Platform.isAndroid) return Checkbox(); //Material
```

Errors occurre at `ThemeData`, `TextButton`, `Tab`, `Divider`, `Scrollbar`, `Tooltip`, `showDialog` `TextStyle` or `Colors`.

The error message is:
`The name 'ThemeData' is defined in the libraries 'package:fluent_ui/src/styles/theme.dart (via package:fluent_ui/fluent_ui.dart)' and 'package:flutter/src/material/theme_data.dart (via package:flutter/material.dart)'. (ambiguous_import at [demo] lib/src/constants/theme.dart:113)`
or
`'TextButton' isn't a function. (invocation_of_non_function at [demo] lib/src/widgets/buttons/blank_button.dart:136)`

*Solution*
Could you please rename overlapping class names to something like `FluentName` or `FlName`.

That would be so helpful.

**Comment by jolleekin** [comment]
Did you try using library prefix? https://dart.dev/guides/language/language-tour#using-libraries

```dart
import 'package:lib2/lib2.dart' as lib2;
```

**Comment by BugsOverBugs** [comment]
@jolleekin No, I didn't.

It may work but the linter doesn't fully support it (regarding suggestions). Or is there a option to enable this.

**Comment by bdlukaa** [comment]
Hello! You can use the `as` keyword when importing the package:

```dart
import 'package:fluent_ui/fluent_ui.dart' as fluent_ui;
import 'package:flutter/material.dart';
```

And use it using the prefix `fluent_ui`:

```dart
if(Platform.isWindows) return fluent_ui.Checkbox(); //Fluent UI

if(Platform.isAndroid) return Checkbox(); //Material
```
