### ISSUE TITLE
[Scrollbar] isPointerOverScrollbar() kind parameter

### ISSUE THREAD

**Issue by uintdev** [bdlukaa/fluent_ui#16]
Last month, there was a commit that changes isPointerOverScrollbar() so that it requires an additional parameter for 'kind' (PointerDeviceKind).
As a result, on newer builds of Flutter that has this change (at the time of creating this issue, at least on the dev branch [2.3.0-0.1.pre]), builds will fail due to the expectation of having two parameters rather than one.
https://github.com/flutter/flutter/commit/e02621b997c622d2805c9dbcac00bf6529017b60#diff-7ea53e627d4729db3a54ab440e8f6d2610cbfc44ac4f9718daef49b2b4645f2dL1177-R1213

**Comment by bdlukaa** [comment]
This commit hasn't landed on stable yet, so I can't update the code since almost all of the devs are on the stable branch (I am too). I don't see a reason for you to use the beta branch tho, since the desktop environment is now supported on the stable branch under an early reklease flag

**Comment by msoham123** [comment]
@bdlukaa As of Flutter 2.2, on stable branch, I'm receiving the same error. I think the commit might have landed?

**Comment by bdlukaa** [comment]
@msoham123  The commit hasn't been published to pub.dev yet. Please make sure you're using github's project as dependency:
```yaml
dependencies:
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
```

Version 2.1.0 will be released at June's 10, 2021 on pub

**Comment by msoham123** [comment]
@bdlukaa Ah okay, makes sense. I'll use the github repo instead!
