### ISSUE TITLE
🐛 Button's font not changed

### ISSUE THREAD

**Issue by slimyjimmy** [bdlukaa/fluent_ui#160]
Hi,
thanks for this great package first of all.

I noticed that changing the font of an app doesn't change the font of some buttons (TextButton, Button).

The result is an inconsistent look and feel.

**Comment by bdlukaa** [comment]
Can you provide a reproducible example?

**Comment by slimyjimmy** [comment]
Sure, here you go: https://github.com/slimyjimmy/wrong_font_example

**Comment by bdlukaa** [comment]
Sorry, but I can not reproduce this on the lastest version.

![](https://user-images.githubusercontent.com/45696119/185750494-612c9e78-04d2-439c-b172-eaac6753f380.png)
