### ISSUE TITLE
🐛 Date Picker and Time Picker only saves last changed dialer

### ISSUE THREAD

**Issue by mahmunk** [bdlukaa/fluent_ui#161]
**Describe the bug**
Date Picker and Time Picker only saves last changed dialer.

**To Reproduce**
1. Go Demo Page -> Forms
2. Change two or more in Date or Time Picker

**Expected behavior**
Expect all to remain

**Screenshots**
None

**Additional context**
None

**Comment by bdlukaa** [comment]
Date and Time pickers need a rework to make it look and feel native!

**Comment by altamirano88** [comment]
fix it please

**Comment by henry2man** [comment]
@mahmunk ... I'm now sure about how I can reproduce this specific issue. I've tested both date & time widgets and they look good for me... can you check it again and/or explain the issue in more details?

**Comment by mahmunk** [comment]
@henry2man If you change more then one value it will only save the last changed value.
You can test it in the demo
