### ISSUE TITLE
show error text in textbox. 

### ISSUE THREAD

**Issue by mayur-16** [bdlukaa/fluent_ui#175]
Is there any method to validate textbox ?
for example  when textbox is empty or contains invalid input show a error text around that like material Textformfield.

**Comment by WinXaito** [comment]
You can see an example in the readme: https://github.com/bdlukaa/fluent_ui#textbox

>If you want to validate the text box, use a TextFormBox:
> ```dart
> TextFormBox(
>   placeholder: 'Your email',
>   validator: (text) {
>     if (text == null || text.isEmpty) return 'Provide an email';
>   }
> ),
> ```
