### ISSUE TITLE
🐛 NavigationAppBar: actions isn't a list of widgets

### ISSUE THREAD

**Issue by Adria75** [bdlukaa/fluent_ui#177]
**Describe the bug**
I've tried to use the actions parametter of the NavigationAppBar as the widget documentation says but is not accepting a list of Widgets. I've seen that it's type is `Widget?` instead of  `List<Widget>?`

**To Reproduce**
Try to use the actions parametter as a list of widgets

**Comment by bdlukaa** [comment]
Use a `Row`

**Comment by Adria75** [comment]
Tried already. Using a `Row` or some Widgets that accept a list of children like `Wrap` or `Padding` the `Buttons` or `IconButtons` are not working as espected. The `Hover` and the `Click` events are not triggering like using only a `Button` as a Widget of the `actions` parametter.

**Comment by bdlukaa** [comment]
Can you share a reproducible example?

**Comment by Adria75** [comment]
Tried some things and the problem is not the `Row`. 

In the image you can see a NavigationAppBar with a `Padding` and a `Row` as a child. The buttons inside the `Row` without being wrapped into a `Padding` are working fine. When you wrap the `Row` inside a `Container` or `Padding`, the buttons are performing some issues with the events. 

![image](https://user-images.githubusercontent.com/38128402/153719772-8344de16-a239-4484-8406-2f911208c753.png)

**Comment by bdlukaa** [comment]
Is this solved?

**Comment by Adria75** [comment]
Nope, still happening.

Only with a ```Row()```:
![Animation](https://user-images.githubusercontent.com/38128402/154012027-703acb88-1d89-43e9-ab4d-5480dacbbff3.gif)

With a ```Padding()``` wrapping the ```Row()```:

![Animation2](https://user-images.githubusercontent.com/38128402/154012397-77565928-01b5-42ea-be75-9b975863ab73.gif)

As you can see, the hover event area has changed. I don't know how to align the buttons at the center withou changing the hover/click area.
