### ISSUE TITLE
🐛 Indicator too tiny for displaymode = top

### ISSUE THREAD

**Issue by alesimula** [bdlukaa/fluent_ui#178]
![image](https://user-images.githubusercontent.com/3057584/153717473-5d22469f-451c-426b-925c-4b23529051b9.png)
^ this is happening since Iast updated the library

![image](https://user-images.githubusercontent.com/3057584/153717484-db67c3de-026e-420a-b13f-77d2f98b262f.png)
^ plus off-center indicators

**Comment by bdlukaa** [comment]
That's the expected behavior. 

Check <https://www.microsoft.com/pt-br/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab>

> ^ plus off-center indicators

I'll take a look!

**Comment by alesimula** [comment]
@bdlukaa Well it's made by Microsoft, so I guess it's as accurate as it can get...

It really sucks tho NGL :D
Maybe you could add a flag to use a full indicator (like before) instead of a tiny one?

BTW congrats on getting your library featured on the Flutter Youtube channel
