### ISSUE TITLE
🐛 DropDownButton has rounded corner only on top and not correct in light theme

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#182]
According to `XAML Controls Gallery`, DropDownButton have rounded border (all corners):

![image](https://user-images.githubusercontent.com/8223773/153831637-92447966-4096-4f58-a719-d52a0c2e28a2.png)

Currently in Fluent, there is only rounded corner at top:

![image](https://user-images.githubusercontent.com/8223773/153831783-a6f5c56c-892b-47cc-8a89-8ac8c76c9f03.png)

And there is a bug with light theme:

![image](https://user-images.githubusercontent.com/8223773/153831850-d9bf34a3-a8c7-4de1-93f5-3f184fbbb64f.png)

Edit: and see if possible to put a lighter background on dropdown button

**Comment by bdlukaa** [comment]
Coloring in general needs an update.
