### ISSUE TITLE
🐛 Blurred effect on texts (in bold)

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#183]
I have the impression that there is sometimes a bit of blur on some text, especially the bold ones.

I don't know if it's directly related to Flutter or Fluent.

Maybe try increasing or decreasing the bold value a little bit.

![image](https://user-images.githubusercontent.com/8223773/153854637-822e5488-205b-438b-98bb-a7898aa2d299.png)

![image](https://user-images.githubusercontent.com/8223773/153854699-640b02fe-5f4f-4716-9345-b3fc824c9b10.png)

![image](https://user-images.githubusercontent.com/8223773/153854813-563acb2b-0686-42e4-abdc-3062b80a7485.png)

![image](https://user-images.githubusercontent.com/8223773/153854864-6da8e1e4-ae85-4603-9527-9a0b7b64d8bf.png)

Already indicated in #122

**Comment by bdlukaa** [comment]
That's an issue with Flutter web. Windows and Android embedder work fine!
