### ISSUE TITLE
Navigate through AutoSuggestBox using the keyboard

### ISSUE THREAD

**Issue by bdlukaa** [bdlukaa/fluent_ui#19]
By default, `AutoSuggestBox` should navigate through its items by using the keyboard arrow keys.

**Comment by amanc1361** [comment]
AutoSuggestBox did not navigate through its items by use the keyboard arrow keys.

**Comment by bdlukaa** [comment]
@amanc1361 yeah it's what this bug is reporting

**Comment by cedric-caberto** [comment]
Could it be possible that you can have an onFocus function on the focused item? Thanks
