### ISSUE TITLE
Question: Do you plan to submit your contributions to the official Flutter repository?

### ISSUE THREAD

**Issue by Rahul-Dixit** [bdlukaa/fluent_ui#20]
The work done by you is really commendable. You have put in significant efforts to improve the desktop experience provided by Flutter. I have a question: What do you plan to do with this project in the near future?

- Push your contributions to the official Flutter repository.
- Keep this project as an external package, the way it is now

**Comment by bdlukaa** [comment]
I don't think flutter wants a fluent ui library in it. See https://github.com/flutter/flutter/issues/46481

**Comment by Rahul-Dixit** [comment]
No, I think initially there were some technical restrictions. But you see that the issue was reopened as the community was interested. Even the Flutter team identified it as a valid features request.

**Comment by bdlukaa** [comment]
Either way, I think it fits more for a package than in the flutter framework

**Comment by bdlukaa** [comment]
> But you see that the issue was reopened as the community was interested.

That issue has the `P6` label. It won't get fixed and will be there for years.
