### ISSUE TITLE
🐛 TextFormBox expands not working

### ISSUE THREAD

**Issue by lucas3g** [bdlukaa/fluent_ui#202]
**Describe the bug**
TextFormBox prop expands not working. But with textbox it works perfectly.

**To Reproduce**
add a simple code
```dart
import 'package:fluent_ui/fluent_ui.dart';

class TestePage extends StatefulWidget {
  TestePage({Key? key}) : super(key: key);

  @override
  State<TestePage> createState() => _TestePageState();
}

class _TestePageState extends State<TestePage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.red,
      height: 200,
      child: TextFormBox(
        maxLines: null,
        minLines: null,
        expands: true,
      ),
    );
  }
}
```

**Expected behavior**
I expected the TextFormField to occupy all the space in the container

**Screenshots**
![image](https://user-images.githubusercontent.com/53888064/155579494-b6884162-798f-4ed4-9412-a197c64d422b.png)

**Comment by bdlukaa** [comment]
I am checking this now! It seems it's caused by the `FormRow` widget, used inside of `TextFormBox`

**Comment by BestOwl** [comment]
This bug appears again in the latest version 3.12.0.

**Comment by s42b** [comment]
@bdlukaa Please reopen this bug. This bug still occurs in the latest version 4.5.0.
