### ISSUE TITLE
🐛 Wrong color on back button

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#204]
Light/dark color must be inverted on back button

![sidebar_backbt](https://user-images.githubusercontent.com/8223773/155688821-48830bfd-f200-4f73-85ef-ad2c4c6b6b0b.gif)

**Comment by bdlukaa** [comment]
That's on purpose. If the button is enabled, the correct color is used

**Comment by WinXaito** [comment]
> That's on purpose. If the button is enabled, the correct color is used

Okay, maybe add more difference ? Like a real disabled button, because like that, this is ... unpleasant to the eye

**Comment by henry2man** [comment]
In this scenarios I always tend to use grey as neutral color because it's both visible in both light & dark modes.

But, to be honest, I've found a little bit weird having a disabled back button. Is this something inherited from Fluent UI?

**Comment by bdlukaa** [comment]
@henry2man take a look at the Settings app. If you haven't navigated yet, the back button is disabled!

**Comment by henry2man** [comment]
> @henry2man take a look at the Settings app. If you haven't navigated yet, the back button is disabled!

@bdlukaa Maybe I haven't explained myself well. What I find weird is having a back button disabled because in reality I would expect to see no button at all.

**Comment by bdlukaa** [comment]
> What I find weird is having a back button disabled because in reality I would expect to see no button at all.

The button is disabled because there should be a "back" functionality. When pressing that button, any navigation previosly executed, either by `Navigator.push` or by changing the index on `NavigationPane`, should be undone. [Learn more](https://docs.microsoft.com/en-us/windows/apps/design/basics/navigation-history-and-backwards-navigation)
