### ISSUE TITLE
Add PaneItemExpander to the NavigationPane

### ISSUE THREAD

**Issue by AKA-LinCoder** [bdlukaa/fluent_ui#205]
hi ,when i look at Readme file in pub,i found that navigation pane can have tree style , but when i use it ,i can not find how to build it ,is it not supported yet? or i just not find the right way to achieve， hope i can get your answer

**Comment by WinXaito** [comment]
I think you talk about that:

![sidebar_ms_expand](https://user-images.githubusercontent.com/8223773/155692628-8aef9335-850b-4776-885b-1750ea123380.gif)

That's currently not implemented (I took this capture from XAML Controls Gallery).

But I don't found that in Readme, maybe you confuse with TreeView ?

**Comment by AKA-LinCoder** [comment]
> I think you talk about that:
> 
> ![sidebar_ms_expand](https://user-images.githubusercontent.com/8223773/155692628-8aef9335-850b-4776-885b-1750ea123380.gif)
> 
> That's currently not implemented (I took this capture from XAML Controls Gallery).
> 
> But I don't found that in Readme, maybe you confuse with TreeView ?

yes,this is what i want,thanks

**Comment by AndreiLunga** [comment]
+1

**Comment by omar0141** [comment]
When will it be in fluent ui

**Comment by AKA-LinCoder** [comment]
nfg
