### ISSUE TITLE
Missing Localizations

### ISSUE THREAD

**Issue by IngeAlejandro** [bdlukaa/fluent_ui#213]
**Is your feature request related to a problem? Please describe.**
I want to use the library for an app in spanish, I was able to make a workaround for global tags but I can't translate de month in DatePicker.

**Describe the solution you'd like**
Allow more localizations or a locale parameter in DatePicker.

**Describe alternatives you've considered**
Current workaround is to extend DefaultLocalizations and overwrite all labels.

**Comment by henry2man** [comment]
@IngeAlejandro Nice one, I'm using the package in a Spanish localized app so I'm interested on this topic.

@bdlukaa @WinXaito Are you thinking of adding multi-language support? Maybe something based on the `intl` package or similar? Now that the package is gaining popularity this would be an interesting addition.

**Comment by WinXaito** [comment]
I think it’s a good idea. In futur, I will need to provide app in multiple language (French, English, German, Italian and maybe Portuguese).

But honestly, I never do a big app localized, so I don’t really know how that’s work…

**Comment by henry2man** [comment]
I've opened a branch on my fork and I'm going to try to make a prototype using `arb` files, which are easily maintainable. 

If it goes well I will do a PR with the results

**Comment by bdlukaa** [comment]
Awesome idea guys! @henry2man, please keep us posted! I'd love to do the translations to Portuguese

**Comment by henry2man** [comment]
@bdlukaa  _Winter is comming_ :)

<img width="310" alt="Captura de pantalla 2022-03-07 a las 9 44 03" src="https://user-images.githubusercontent.com/4610108/156997584-70fd092e-bb86-4184-86a6-b48a1f31b7b7.png">

**Comment by henry2man** [comment]
Hey folks, please take a look at https://github.com/bdlukaa/fluent_ui/pull/216

**Comment by henry2man** [comment]
@IngeAlejandro Just wait for #236, because #216 already solved commonly used labels for Spanish
