### ISSUE TITLE
Close minimal style NavigationPane from PaneItemAction.onTap()

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [bdlukaa/fluent_ui#219]
**Is your feature request related to a problem? Please describe.**
As some of my NavigationPane items push to the navigation stack instead of changing the NavigationView content, I would like to be able to close a minimal style NavigationPane. Currently the pane stays open after navigation, it is noticeable when you navigate back.

**Describe the solution you'd like**
I would like to be able to close the minimal style NavigationPane programatically.

**Describe alternatives you've considered**
None, I could not find any.

**Additional context**

**Comment by bdlukaa** [comment]
You can change the pane display mode with simple state management. You can see an example of how to do it on the example app: https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/theme.dart
