### ISSUE TITLE
[feature request] `Expander` without content

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [bdlukaa/fluent_ui#220]
**Is your feature request related to a problem? Please describe.**
As a developer creating a settings screen in my app, I would like to make it look and feel like the Windows 11 settings. For this we can use Extender, but that requires a content widget argument, while Windows 11 seem to use Extender like widgets without any content (e.g. with only a dropdown box at the end).

**Describe alternatives you've considered**
Alternative layout (simple listview, or perhaps based on some type of grid), or create a subclass of Extender to implement this.

**Additional context**
![Example from Windows 11 Settings](https://user-images.githubusercontent.com/2611894/157348828-b21c7f42-956e-4535-82e4-4c33081f0192.png)

**Comment by WinXaito** [comment]
You can do something like that:

```dart
Card(
  child: ListTile(
    leading: const Icon(FluentIcons.brightness),
    title: const Text('Title'),
    subtitle: const Text('Subtitle'),
    trailing: DropDownButton(title: const Text('DropDown'), items: [
      DropDownButtonItem(onTap: () {}, title: const Text('test'))
    ]),
  ),
),
```

Render:

![image](https://user-images.githubusercontent.com/8223773/157394193-ee4b4c83-c99c-453c-a4f7-7523f6cc2b41.png)

**Comment by bdlukaa** [comment]
This field on the Windows Settings App is a custom component of the app, not part of the fluent design system. You can check the complete list of fluent components [here](https://github.com/microsoft/microsoft-ui-xaml/tree/main/dev).

Closing as won't fix
