### ISSUE TITLE
Button state bug🐛 

### ISSUE THREAD

**Issue by AbrasiveBoar902** [bdlukaa/fluent_ui#230]
**Describe the bug**
When I click on a disabled Button ( onPressed: null ) and use setState to enable it, it will still be displayed gray as it is disabled

Like this:
Button(
  child: const Text('This is a text'),
  onPressed: SingletonClass.instance.buttonEnabled ? null : () {},
),

**Comment by bdlukaa** [comment]
Sorry, but I can't reproduce. Can you try?

```dart
Button(
  child: const Text('This is a text'),
  onPressed: SingletonClass.instance.buttonEnabled ? () {} : null,
),
```

**Comment by AbrasiveBoar902** [comment]
> Sorry, but I can't reproduce. Can you try?
> 
> ```dart
> Button(
>   child: const Text('This is a text'),
>   onPressed: SingletonClass.instance.buttonEnabled ? () {} : null,
> ),
> ```

Well I wrote wrong in the issue. That is not my source code.

https://user-images.githubusercontent.com/76773705/159133202-6af4d32a-d041-4112-b9c7-3387541940cc.mp4

**Comment by AbrasiveBoar902** [comment]
```dart
onPressed: () {
  GKernel.instance.converting = true;
  setState(() {});
  compute(convert, ConvertArgs(convertmethod: GKernel.instance.convertMethod, dithering: GKernel.instance.dithering)).then((value) {
    GKernel.instance.converting = false;
    setState(() {});
   });
 }),
```
```dart
RepaintBoundary(
  child: Button(
    child: const Text('保存为图片'),
    onPressed: GKernel.instance.converting ? null : () {},
  ),
),
```
