### ISSUE TITLE
Implement command bars

### ISSUE THREAD

**Issue by klondikedragon** [bdlukaa/fluent_ui#231]
Implement command bars as described [in the spec](https://docs.microsoft.com/en-us/windows/apps/design/controls/command-bar). For example:

![image](https://docs.microsoft.com/en-us/windows/apps/design/controls/images/controls-appbar-icons.png)

Initially it may seem that a Command Bar is just a row of buttons; however, there are certain expectations on height and spacing. More importantly, the logic can get complex once you consider the open/closed state capability as well as automatic dynamic overflow of items into the "secondary commands" menu (shown when "..." button is clicked).

Command bars will be used heavily in my project and so I've implemented a basic version as a starting point. I'll share a PR to see if it is an OK starting point. It does not have dynamic overflow, but instead provides either clipping, horizontal scrolling, or wrapping to handle overflow.

Also, it's not mentioned in the spec, but command bars are sometimes contained within a raised card. For example, the application-level command bar for desktop Microsoft Office apps looks like:

![image](https://user-images.githubusercontent.com/88254524/159104956-8f080c20-ba7e-4be8-a64a-fbf09ef466b8.png)

A `CommandBarCard` will be provided to standardize the look/feel for any "raised" command bars as well.

**Comment by WinXaito** [comment]
Closed with #232
