### ISSUE TITLE
FluentUI incompatible with system_theme Theme

### ISSUE THREAD

**Issue by mytja** [bdlukaa/fluent_ui#24]
When I use this code:
```dart
fluent.ThemeData(accentColor: SystemTheme.accentInstance.accent);
```

I get this error in VS Code:
```
The argument type 'Color' can't be assigned to the parameter type 'AccentColor?'.dart(argument_type_not_assignable)
```

<br>

Also, is there any possibility for usage like in Flutter Material UI, eg. like this:
```dart
material.ThemeData(brightness: material.Brightness.dark);
```
aka. using Brightness, and afterwards use it like this:
```dart
MaterialApp(theme: this.theme, darkTheme: this.darkTheme, themeMode: this.themeMode);
```
I know, that fluent_ui has themeMode argument, but it doesn't have `theme` and `darkTheme` args.

Is that possible?
Thanks

**Comment by bdlukaa** [comment]
On the fluent UI example app, here's how it's done:

```dart
AccentColor get systemAccentColor => AccentColor('normal', {
      'darkest': SystemTheme.accentInstance.darkest,
      'darker': SystemTheme.accentInstance.darker,
      'dark': SystemTheme.accentInstance.dark,
      'normal': SystemTheme.accentInstance.accent,
      'light': SystemTheme.accentInstance.light,
      'lighter': SystemTheme.accentInstance.lighter,
      'lightest': SystemTheme.accentInstance.lightest,
    });
```

> I know, that fluent_ui has themeMode argument, but it doesn't have theme and darkTheme args.

It has both. Check the example app

**Comment by mytja** [comment]
Oh, thanks.
I have just picked the code from README in Accent color section.
However, thanks.

PS
I know you have Discord, but I think you also should enable Discussions.
They are pretty nice.
