### ISSUE TITLE
Filter Combobox with keyboard & lazy loading

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#244]
**Is your feature request related to a problem? Please describe.**

Include the ability to filter `Combobox` items using plain text.

**Describe the solution you'd like**

And extended `Combobox` property like `filterFunction: List<T>? Function(String filter)` that allows activating a text field that would serve to filter the current items. This is a well-known Combobox pattern present if most UI toolkits:

![image](https://user-images.githubusercontent.com/4610108/160070852-96133b9c-d8d4-4662-a2af-ae04326aae7f.png)

The motivation of having an extended filter function is to add the ability for creating custom search functions (ex: search by an internal property like a code).

EDIT: Here it is another example from MS Sharepoint that could be used as an inspiration. I think this kind of UI will require to change the `Combobox.items` to `FutureOr<List<ComboboxItem<T>>?>? items`, in order to implement the "loading" behaviour.

![image](https://user-images.githubusercontent.com/4610108/160071096-a5f11811-5a19-4933-9bcb-b5a49f01346d.png)

**Describe alternatives you've considered**

I've considered `AutoSuggestBox` but I think this should be integrated into `Combobox` because such improvement could be easily added to existing codebase.

**Additional context**
n/a

**Comment by bdlukaa** [comment]
This looks like it's a `AutoSuggestBox`

**Comment by henry2man** [comment]
Yes, yesterday I was thinking on a `AutoSuggestBox` too. Let me check if I can use it as a replacement.

**Comment by henry2man** [comment]
More on this:

Combobox on web: https://docs.microsoft.com/en-us/fluent-ui/web-components/components/combobox (with autocomplete, this would be fantastic!)
<img width="748" alt="Captura de Pantalla 2022-06-21 a las 7 42 33" src="https://user-images.githubusercontent.com/4610108/174724665-5a23faa3-5f02-43f5-b4f2-99822a1df64a.png">

Related but different for this issue:
Editable Combobox (if you want to **add** new items to a list): https://docs.microsoft.com/en-us/windows/apps/design/controls/combo-box#make-a-combo-box-editable

**Comment by bdlukaa** [comment]
@henry2man I understand your use case, but I believe `AutoSuggestBox`, after the rework, is the best option for you. `Combobox` is used with static options, and can't be fetched asynchronously.

`AutoSuggestBox` has all the requested features!

**Comment by henry2man** [comment]
@bdlukaa I will try the new AutoSuggestBox, for sure 👍🏻 Thanks
