### ISSUE TITLE
🐛 NavigationPane + PaneDisplayMode.auto: state loss on window resize

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#245]
**Describe the bug**

When using `NavigationPane` + `PaneDisplayMode.auto` the content state is loss when app window is resized

**To Reproduce**
1. Run the Example app (by default is configured used `PaneDisplayMode.auto`)
2. Go to "Forms" demo page
3. Change state, toggle disabled...
4. Resize the window
5. See error: all changes were reverted because whole subtree is regenerated.

**Expected behavior**

Content region state is preserved.

**Screenshots**

https://youtu.be/QMNz4xoFboY

**Additional context**
N/a

**Comment by WinXaito** [comment]
Maybe what I describe here: https://github.com/bdlukaa/fluent_ui/issues/203#issuecomment-1061490025 ?

**Comment by henry2man** [comment]
@WinXaito Maybe I need to add a Key into my Content region widgets? Either it's an internal implementation issue, or a key needs to be used, because I can't think of any other alternative.

**Comment by WinXaito** [comment]
In my vision, the NavigationPane should be the same for all types.

With a difference in width and hidden widgets (Stack or Clip). And have the changes only using animations.

It avoids rebuilding and losing the widget, and it also allows to have something smoother and closer to the real behavior of WinUI3.

But this also requires a lot of refactoring work at this level.

**Comment by bdlukaa** [comment]
The state is loss on the view itself, not on the content area

**Comment by henry2man** [comment]
This makes sense. In my preliminary analysis I didn't found anything that could cause the issue... because I was looking for the wrong issue

**Comment by henry2man** [comment]
"A key" was the key! 

Well done @bdlukaa :)
