### ISSUE TITLE
How do I change the corners and lines of the screen?

### ISSUE THREAD

**Issue by Patrick386** [bdlukaa/fluent_ui#256]
I am testing this package.
I want to use the basics design style.

How do I change the corners and lines of the screen?

![스크린샷 2022-03-29 오후 2 28 28](https://user-images.githubusercontent.com/49754877/160540402-578bbb07-f0e7-493d-8f13-7b4545d0b5e8.png)

**Comment by bdlukaa** [comment]
You can use `NavigationView.contentShape` to change that. By default the following is used:

```dart
                RoundedRectangleBorder(
                  side: BorderSide(
                    width: 0.3,
                    color: FluentTheme.of(context).brightness.isDark
                        ? Colors.black
                        : const Color(0xffBCBCBC),
                  ),
                  borderRadius: const BorderRadiusDirectional.only(
                    topStart: Radius.circular(8.0),
                  ).resolve(direction),
                )
```
