### ISSUE TITLE
Show multiple views for an app

### ISSUE THREAD

**Issue by Patrick386** [bdlukaa/fluent_ui#257]
Show multiple views for an app
[https://docs.microsoft.com/en-us/windows/apps/design/layout/show-multiple-views](url)

Does this package have any features?
![multi-view](https://user-images.githubusercontent.com/49754877/160548298-3343b7e3-ecb6-42a5-ac48-c549674ac358.gif)

**Comment by WinXaito** [comment]
Currently Flutter doesn't support multiple window management, so no, it's not possible for the moment.

https://github.com/flutter/flutter/issues/30701
