### ISSUE TITLE
Implement menus and context menus

### ISSUE THREAD

**Issue by bdlukaa** [bdlukaa/fluent_ui#27]
Menus and context menus display a list of commands or options when the user requests them. Use a menu flyout to show a single, inline menu. Use a menu bar to show a set of menus in a horizontal row, typically at the top of an app window. Each menu can have menu items and sub-menus.

![](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/images/menu-bar-submenu.png)

Anatomy:
- MenuBar
       - MenuBarItem (Essentially a button)
              - MenuFlyoutItem (Essentially a tappable list tile)

The animation is a `SizeTransition` combined with ease curve and faster duration.

**Comment by WinXaito** [comment]
For context menu: 

![image](https://user-images.githubusercontent.com/8223773/146143513-5fa1b263-039f-403a-9878-5d0b5d3b4100.png)

![image](https://user-images.githubusercontent.com/8223773/146143524-0a4cf297-ea6b-4f09-990c-d42dc7cbd667.png)

[More...](https://docs.microsoft.com/en-us/windows/apps/design/controls/menus-and-context-menus)
