### ISSUE TITLE
🐛 NavigationPane sticky state not preserved

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#272]
**Describe the bug**

![fluent_pane_bug](https://user-images.githubusercontent.com/8223773/161985579-74862e03-281b-41d2-9daa-de4e831250a0.gif)

**To Reproduce**

You can see that on example app. Go the the settings pane and change theme (light, dark) and the sticky move from the previous selected pane to settings.

**Expected behavior**

The sticky must not be animate when we are already on the good pane.

Edit: 3.10.0 regression

**Comment by bdlukaa** [comment]
This happens something on the parent (NavigationView and above) is updated (setState). I believe global keys should be considered for each pane item

**Comment by WinXaito** [comment]
Thanks !
