### ISSUE TITLE
🐛 Sticky not animated on first change

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#274]
**Describe the bug**

![fluent_sticky](https://user-images.githubusercontent.com/8223773/162149971-0400f873-3854-4320-9979-e9ab67c1b3b5.gif)

Present after the hotfix for #272 

But this is not a major problem ;)

**Comment by AbrasiveBoar902** [comment]
This also happens in the example

**Comment by bdlukaa** [comment]
Not reproducible on the latest version
