### ISSUE TITLE
🐛 ScaffoldPage wrong background color if there is no NavigationView

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#275]
**Describe the bug**

With a light theme we had a black background color if no NavigationView is present.

With a dark theme, the page come more black.

**Screenshots**

![](https://media.discordapp.net/attachments/815669321183264779/961253440112193556/fluent_light1.gif)

![](https://cdn.discordapp.com/attachments/815669321183264779/961253440493879296/fluent_dark1.gif)

**Additional context**

The problem came with the version 3.10.0 with this commit: https://github.com/bdlukaa/fluent_ui/commit/50419a187aeb1d1487afab216099fae80c2840e1

As @bdlukaa said:

> scaffolds need a rework

**Comment by WinXaito** [comment]
So far I have encapsulated all my `ScaffoldPage` in a `NavigationView` and it works fine. We need to see if there is a way to simplify things so that we don't need a `NavigationView`. But it doesn't seem to be a priority anymore.

**Comment by klondikedragon** [comment]
I noticed the same, I have a few pages that are shown outside of a navbar context. For now I've just created a widget that replicates the same behavior, putting a `Mica` behind it with the same approach for picking a color. Probably using a NavigationView also like you mention would have been OK instead of this widget.
```dart
class StandaloneAppPage extends StatelessWidget {
  final Widget child;
  const StandaloneAppPage({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final theme = FluentTheme.of(context);
    return Mica(
      backgroundColor: theme.navigationPaneTheme.backgroundColor ??
          theme.micaBackgroundColor,
      child: child,
    );
  }
}
```

**Comment by bdlukaa** [comment]
This issue is not reproducible on the latest master. Can this be closed?
