### ISSUE TITLE
Setting `leading` of NavigationAppBar permanently sets the Leading icon of NavigationPane when it's displayMode is top🐛 

### ISSUE THREAD

**Issue by imp-sike** [bdlukaa/fluent_ui#284]
**Describe the bug**
When you set a leading icon using leading property of NavigationAppBar, it permanently sets the Leading icon of NavigationPane when it's displayMode is top. And I do not find any property or methods which can be used to override that icon.

**To Reproduce**
Code to Reproduce
```dart
 @override
  Widget build(BuildContext context) {
    return NavigationView(
        appBar: NavigationAppBar(
         // try removing leading
          leading: const FlutterLogo(),
          title: () {
            return const DragToMoveArea(
              child: Align(
                alignment: AlignmentDirectional.centerStart,
                child: Text("Statistics Helper"),
              ),
            );
          }(),
          actions: kIsWeb
              ? null
              : DragToMoveArea(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: const [Spacer(), WindowButtons()],
            ),
          ),
        ),
        pane: NavigationPane(

          selected: index,
          displayMode: PaneDisplayMode.top,
          onChanged: (i) => setState(() => index = i),
          size: const NavigationPaneSize(
            openMinWidth: 250,
            openMaxWidth: 320,
          ),


          indicator: () {
            return const EndNavigationIndicator();
          }(),
          items: [
            // It doesn't look good when resizing from compact to open
            // PaneItemHeader(header: Text('User Interaction')),


       
            PaneItem(
              icon: Container(),
              title: const Text('New File'),
            ),




          ],

          footerItems: [
            PaneItemSeparator(),
            PaneItem(

              icon:  Padding(
                padding: const EdgeInsets.all(8.0),
                child: Icon(FluentIcons.play_solid, color: m.Colors.green,),
              ),
              title: const Text('Process'),
            ),
          ],
        ),

        content: Container(
          width: context.width* 0.99,
          child: Column(
            children: [
              Text("Hell")
            ],
          ),
        )
    );
  }
```

**Expected behavior**
If this is bug, it must be resolved. If this is a hidden feature, there must be another property of NavigationPane to override the leading Widget.

**Screenshots**
![Check the leading images](https://user-images.githubusercontent.com/93368594/162788560-3795f483-bcf3-4075-bcdf-3670af31978a.png)

P.S. I this is a bug, I would be grateful in helping contributing to it.

**Comment by WinXaito** [comment]
See here: https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/view.dart#L538-L549

> ```dart
>   /// The widget at the beggining of the app bar, before [title].
>   ///
>   /// Typically the [leading] widget is an [Icon] or an [IconButton].
>   ///
>   /// If this is null and [automaticallyImplyLeading] is set to true, the
>   /// view will imply an appropriate widget. If  the parent [Navigator] can
>   /// go back, the app bar will use an [IconButton] that calls [Navigator.maybePop].
>   ///
>   /// See also:
>   ///   * [automaticallyImplyLeading], that controls whether we should try to
>   ///     imply the leading widget, if [leading] is null
>   final Widget? leading;
> ```

Do these comments answer your question? Or perhaps I have misunderstood.

**Comment by imp-sike** [comment]
![Add a subheading](https://user-images.githubusercontent.com/93368594/162880921-2b30d956-2c79-4d42-ad10-6f0ddbfc5c4c.png)

When I set 
          ```leading: const FlutterLogo(),```
in `NavigationAppBar` same icon seems to appear as `NavigationPane` leading icons as shown in the image above. And if I am correct, thers is no any `leading` property to either disable or change the `NavigationPane` icon.

**Comment by fraser-mendeco** [comment]
I'm having this issue too.

Minimal code to reproduce below. See the blue `CircleAvatar` is rendered twice. 

```dart
import 'package:fluent_ui/fluent_ui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return FluentApp(
      title: 'Flutter Demo',
      home: NavigationView(
        appBar: const NavigationAppBar(
          leading: CircleAvatar(),
          title: Text('Flutter Demo'),
        ),
        pane: NavigationPane(
          displayMode: PaneDisplayMode.top,
          items: [
            PaneItem(
              icon: const Icon(FluentIcons.add),
            ),
          ],
        ),
      ),
    );
  }
}
```

Result
![image](https://user-images.githubusercontent.com/93122686/162935614-16310cd6-ae0f-445d-a625-c84cd86e3178.png)

**Comment by WinXaito** [comment]
Okay, understood. This is effectively a bug.

**Comment by imp-sike** [comment]
Can i work on this BTW. I am new to contributing.

**Comment by WinXaito** [comment]
Yeah of course, don't hesitate to open a Pull request.

Don't hesite to join the discord for any help or discussion 

<a title="Discord" href="https://discord.gg/674gpDQUVq">
      <img src="https://img.shields.io/discord/809528329337962516?label=discord&logo=discord" />
    </a> 

;-)
