### ISSUE TITLE
Length option for Progress Bar

### ISSUE THREAD

**Issue by NexiaMoe** [bdlukaa/fluent_ui#292]
**Is your feature request related to a problem? Please describe.**
For now Progress Bar is good enough for creating progress when downloading (My Program is like download manager for specific game). But I can't change length of the progress bar, as for now it's on center of widget 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/25083343/163719124-4bfc3cfc-d657-4ea8-aedf-d8ea0f7658bf.png">
 

**Describe the solution you'd like**
Add length option for specified the length of progress bar.

if there any solution, please let me know ! 
Thank you for creating Fluent UI !

**Comment by WinXaito** [comment]
The size depend on the parent, so something like that should work:

```dart
SizedBox(
  width: double.inifity,
  child: ProgressBar(...),
)
```
