### ISSUE TITLE
Multiple selection combo box

### ISSUE THREAD

**Issue by valientegaston** [bdlukaa/fluent_ui#295]
Hi all.  Amazing work!
Does anybody know how to create a multiple choice combo box? I need it for a project but don't know if exists, I just found a simple selection combo. Thanks.

![RJt7Z](https://user-images.githubusercontent.com/4804726/164533794-849fc16e-9f7c-4fd1-8ea8-a62a3fa7471b.jpg)

**Comment by bdlukaa** [comment]
Hello! This behavior isn't shown on the microsoft docs. See https://docs.microsoft.com/en-us/windows/apps/design/controls/combo-box

Also, on the XAML Gallery, it says "[...] and when users select only one option at a time". Is there any native app that has this funcitonality?

You can probably use a Flyout with CheckBoxes instead.

**Comment by valientegaston** [comment]
Hi! Thanks for your reply. I dont know if any native app uses it, but I will try to find one.  

Meanwhile, please, Could you check below link? Thank you. 

https://developer.microsoft.com/en-us/fluentui#/controls/web/ComboBox

**Comment by valientegaston** [comment]
Microsoft Excel uses it when you set filters. 
![35615e05-8e47-45ff-91e8-010a7b5350a3](https://user-images.githubusercontent.com/4804726/165003041-f690f7d2-493f-4a7f-8a49-e3dbef805d88.jpg)

**Comment by bdlukaa** [comment]
Excel uses Fluent UI for Web (the link you sent to me). The multiple selection combobox seems to not be a native feature, thefore it won't be implemented.

Altough it should be simple to implement with a `Flyout`, if you want it.
