### ISSUE TITLE
🐛 No horizontal scrollbars for listviews

### ISSUE THREAD

**Issue by Tobivaria** [bdlukaa/fluent_ui#300]
**Describe the bug**
There is no scrollbar for horizontal aligned listviews. Therefore views like grids, cannot scroll to horizontally if there is content either left or right.

Ideally there will be a scrollbar on the right and on the bottom attached to the window.

**To Reproduce**
```Widget build(BuildContext context) {
    return ListView(
      scrollDirection: Axis.vertical,
      children: [
        SizedBox(
          height: 250,
          child: SingleChildScrollView(
            controller: ScrollController(),
            scrollDirection: Axis.horizontal,
            child: Row(
              children: [
                for (var i = 0; i < 20; i++) ...[
                  const Padding(
                    padding: EdgeInsets.all(20.0),
                    child: Text('data'),
                  ),
                ],
              ],
            ),
          ),
        )
      ],
    );
  }
```

**Expected behavior**
[X] Right scrollbar
[ ] Scrollbar on bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/47928547/164990899-7220e350-1e60-4cad-b358-c31eb0ccd3fd.png)

**Comment by bdlukaa** [comment]
You can add a scrollbar manually by wrapping your `ListView` into a `Scrollbar`, and using the same `ScrollController` for both:

```dart
final controller = ScrollController();

Scrollbar(
  controller: controller,
  child: ListView(
    controller: controller,
    ...,
  ),
),
```

**Comment by bdlukaa** [comment]
Can this be closed?

**Comment by Tobivaria** [comment]
Yes :)
