### ISSUE TITLE
Q: Is there a way to make fields smaller in height?

### ISSUE THREAD

**Issue by pamtbaau** [bdlukaa/fluent_ui#307]
I've searched the web and the sourcecode of fluent_ui, but haven't found an solution yet.  I would like to minimize the height of fields. Is there some generic way to do this?

Thanks.

**Comment by bdlukaa** [comment]
Hello!. No, it's currently not possible. Their default height is their min height, which is 32.0

**Comment by pamtbaau** [comment]
That's unfortunate... Thanks!
