### ISSUE TITLE
🐛 Cards with opacity have a wrong shadow

### ISSUE THREAD

**Issue by AbrasiveBoar902** [bdlukaa/fluent_ui#311]
**Describe the bug**
I added opacity to the background of a Card, and the shadow showed inside the Card.

**To Reproduce**
Add`backgroundColor: FluentTheme.of(context).cardColor.withOpacity(0.6)`

**Expected behavior**
I can see the things behind the Card, and the shadow works well.

**Screenshots**
![image](https://user-images.githubusercontent.com/76773705/166104593-2ceb7188-59eb-41a3-ad66-33656904de9e.png)

**Comment by bdlukaa** [comment]
How a shadow (elevation) works:
A black layer is rendered behind the widget with some offset to left-top or right-bottom. If a opacity is set to the background, the black layer will be visible behind the content. 

The only way to not show the shadow behind content is to set `elevation: 0`

**Comment by AbrasiveBoar902** [comment]
Is there any posibility to render the part of the layer that is outside the widget? Or only render the overlapped part of the black layers once?
