### ISSUE TITLE
How to make ios like blur effect with Acrylic？

### ISSUE THREAD

**Issue by dbsxdbsx** [bdlukaa/fluent_ui#314]
I want to create a  widget (like commandbar)  with [blur of ios style](https://miro.medium.com/max/1400/1*vi901HmyKeO1mnFPt1r6qQ.png). My code is like this:
```dart
  @override
  Widget build(BuildContext context) {
    return ConstrainedBox(
      constraints: const BoxConstraints(maxWidth: 250),
      child: Container(
        // Add the line below
        clipBehavior: Clip.antiAlias,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
          // border: Border.all(color: Colors.green, width: 2.0)
        ),

        child: Acrylic(
          blurAmount: 20,
          // shape: RoundedRectangleBorder(),
          child: CommandBar(
            overflowBehavior: CommandBarOverflowBehavior.clip,
            isCompact: true,
            primaryItems: [
              ...simpleCommandBarItems,
              const CommandBarSeparator(),
              ...moreCommandBarItems,
            ],
          ),
        ),
      ),
    );

```

But the result of Acrylic turns out to be  more white at center, and more transparent at the edge---I need to make it evenly blurred.  Though I can make it totally transparent, but this is not the blur effect I want.

If Acrylic is not the right way, is there some other suggestion to make this effect?

**Comment by bdlukaa** [comment]
You can take a look at the source code of the cupertino widgets library, more specifically to the CupertinoDialog

Acrylic is the implementation of Fluent Acrylic.
