### ISSUE TITLE
Is there a widget could pop up when mouse closes to window border?

### ISSUE THREAD

**Issue by dbsxdbsx** [bdlukaa/fluent_ui#315]
Just like the hidden windows task bar. It only shows up when mouse close to it. I want to  similar effect on windows app.  
At present, I've tried best with `commandbar` widget which is closest to what I want.  But it seems to not be able to be vertically layout. 

I don't know what this kind of widget is called in common.Is there any suggestion?

**Comment by bdlukaa** [comment]
Wdym?

**Comment by AbrasiveBoar902** [comment]
> Wdym?

Maybe he is looking for a collection of widgets that can automaticly pop out when the mouse is close to the window's border.

**Comment by bdlukaa** [comment]
If that's the case, a MouseRegion can be used globally, and close the popup when the pointer is close to the border

**Comment by dbsxdbsx** [comment]
@AbrasiveBoar902 ，thanks fro your explanation, and that is indeed what I want. And @bdlukaa ,I would  have a deep look at `MouseRegion`. By the way, is it possible to make `commandbar` lay out vertically? I want to make it stick on left or right border.

**Comment by bdlukaa** [comment]
> By the way, is it possible to make commandbar lay out vertically?

I don't think so

**Comment by dbsxdbsx** [comment]
> > By the way, is it possible to make commandbar lay out vertically?
> 
> I don't think so

Thanks anyway, I found `RotatedBox` is ok for vertical layout.
