### ISSUE TITLE
Programmatically validate TextFormBox

### ISSUE THREAD

**Issue by drandell** [bdlukaa/fluent_ui#316]
Hi, 

Sorry for another simple question but I don't see any examples in the docs. 
How would I programmatically validate a textformbox using a key and the current state field? 

My goal:
To have the validation set to onUserInteraction but be able to force a check programmatically when they try and click a button to submit a form.

**Comment by bdlukaa** [comment]
https://docs.flutter.dev/cookbook/forms/validation

You need to wrap your form in a `Form` widget, and validate it using a key!

**Comment by drandell** [comment]
I forgot to wrap in `Form()` widget! 

Thanks @bdlukaa
