### ISSUE TITLE
Selectable ListView and StickyNavigationIndicator fix

### ISSUE THREAD

**Issue by AbrasiveBoar902** [bdlukaa/fluent_ui#317]
**Is your feature request related to a problem? Please describe.**
I tried to make ListView selectable but I haven't found click callback para or selectionMode like TreeView. And my crude implementation is very ugly (only changed its tileColor)
The animation of StickyNavigationIndicator is strange. It is not continuous at the border of the PaneItems. This also appears in the example.
![image](https://user-images.githubusercontent.com/76773705/166433624-9b89ba89-a67b-4cb3-963a-509e0f82c6a5.png)

**Describe the solution you'd like**
Selectable ListView just like TreeView.
Fix the StickyNavigationIndicator (make it behaves like it used to be)

**Describe alternatives you've considered**
I tried to use TreeView instead but I can't change the height of it.

**Additional context**
![image](https://user-images.githubusercontent.com/76773705/166433704-73feb0ff-3233-4335-a7cc-7afdc117de0d.png)
![image](https://user-images.githubusercontent.com/76773705/166433885-4212c486-d0e2-4627-9716-a684c82c20f9.png)

**Comment by bdlukaa** [comment]
> The animation of StickyNavigationIndicator is strange. It is not continuous at the border of the PaneItems. 

This is the new behavior on Windows 11.

**Comment by AbrasiveBoar902** [comment]
> > The animation of StickyNavigationIndicator is strange. It is not continuous at the border of the PaneItems.
> 
> This is the new behavior on Windows 11.

Ok. But there is a bug that when I switch to another paneItem and then quickly switch back, the indicator will go missing.
https://user-images.githubusercontent.com/76773705/166613567-230975b7-1fe7-4ba7-849c-7d63b327df15.mp4

**Comment by AbrasiveBoar902** [comment]
The indicator at the orignal paneitem is strange. Maybe the dispear of it needs an animation like before...

https://user-images.githubusercontent.com/76773705/166626077-f94e5de1-6b9a-4ead-a7f6-0283fc4539dc.mp4

**Comment by MahdiBaghbani** [comment]
> > The animation of StickyNavigationIndicator is strange. It is not continuous at the border of the PaneItems.
> 
> This is the new behavior on Windows 11.

Hi, sorry to interrupt, is it possible to keep the old continuous one under different name? like theming you did with aero, acrylic and mica. I really miss old one.

**Comment by bdlukaa** [comment]
> is it possible to keep the old continuous one under different name?

Well, not really! The old implementation was buggy, unperformant and unpleasant to eyes. The indicator was overlapping, the animation was incorrect (curves, animation), and it didn't look good :/

> Selectable ListView just like TreeView.

About the original request, it's going to be tracked on #409

Closing this as stale
