### ISSUE TITLE
ToolTip not working properly when assigned to a button 🐛 

### ISSUE THREAD

**Issue by tobiasht** [bdlukaa/fluent_ui#318]
**Describe the bug**
When wrapping a button (or it's child) in a ToolTip. I get the following behaviour:

![Screen Recording 2022-05-03 at 12 58 40](https://user-images.githubusercontent.com/20655261/166442034-13a4df23-7061-4482-9f39-1979e36daed4.gif)

**To Reproduce**
Wrap a ToolTip around a Button.

**Expected behavior**
See the ToolTip until i move the cursor away

**Comment by tobiasht** [comment]
Apparently, the tooltip works correctly if the character count is 8 or less—no idea why.

**Comment by bdlukaa** [comment]
I can not reproduce this issue.

You can test it on the example app (https://bdlukaa.github.io/fluent_ui/). Open the app and go to `Tooltip` tab. If you hover the button, the tooltip is displayed correctly.

Can you post here a reproducible code snippet?
