### ISSUE TITLE
🐛 Scrollbar will not work currectly with Expander

### ISSUE THREAD

**Issue by AbrasiveBoar902** [bdlukaa/fluent_ui#319]
**Describe the bug**
When a Expander in a list is opened, the scrollbar will not work properly. (maybe something wrong with the caculating of the list length)

**Screenshots**
https://user-images.githubusercontent.com/76773705/166494053-f8bb5d14-bb8e-490d-97be-88c39b8895b9.mp4

**Comment by bdlukaa** [comment]
This is an issue with flutter's `RawScrollbar`. The same happens to material
