### ISSUE TITLE
Window control buttons oddly duplicated when mica theme is used🐛 

### ISSUE THREAD

**Issue by andrelrf1** [bdlukaa/fluent_ui#321]
**Describe the bug**
I've known fluent_ui since the presentation the Flutter team made and I've been wanting to use it ever since. I recently started testing with the package using the application provided as an example for this, that's when I realized that when I use mica transparency this problem happens. I'm not sure if it's a problem with fluent_ui or flutter_acrylic or if it's a problem with me, so I decided to post it here.

**To Reproduce**
1. Just run an application with mica transparency, the example provided in the fluent_ui repository for example.
2. And maximize screen.

**Screenshots**
Here is the image of the problem:
![image](https://user-images.githubusercontent.com/42091869/167014624-16751f39-e4a4-42da-b037-bc1c727086b9.png)

**Additional context**
I use Windows 11 on the latest public build.

**Comment by bdlukaa** [comment]
cc: @alexmercerind

**Comment by AbrasiveBoar902** [comment]
I think this is a bug of win11. This happens with window_manager and bitdojo_window when using half transparent effects on win11.
https://github.com/leanflutter/window_manager/issues/106

**Comment by tangenx** [comment]
Use `Window.hideWindowControls()` from `flutter_acrylic`. This worked for me.

![Initial bug](https://i.imgur.com/7oOoEAl.png)

![With Window.hideWindowControls()](https://user-images.githubusercontent.com/46501450/167402780-4e4b27f0-de02-4c53-a223-1a73e92512ed.png)

(My window buttons are brown)

**Comment by andrelrf1** [comment]
It worked! Thank you very much!
