### ISSUE TITLE
Slight change for Chip text

### ISSUE THREAD

**Issue by MahdiBaghbani** [bdlukaa/fluent_ui#322]
I'm new to developing with flutter and my as first ever project I used your library, so this issue might be solved easier than I think,

**Is your feature request related to a problem? Please describe.**
I had to implement a list of users with full names and picture ID, so basically I copied ```Chip()``` exactly as it is from your example provided. sometimes user full names are too long, an as described in documents and stackoverflow I used ```Text()``` like this:

```
// simplified version
Chip(
  text: const Text(
    "A very very long string fetched from api",
    maxLines: 1,
   overflow: TextOverflow.ellipsis,
  ),
),
``` 
it didn't work, and then I tried other solutions like putting ```Text()``` inside``` Expanded()``` or ```Flexible()```, which gives error.

```
// simplified version
Chip(
  text: const Expanded(
    child: Text(
      "A very very long string fetched from api",
      maxLines: 1,
      overflow: TextOverflow.ellipsis,
    ),
  ),
),
``` 

**Describe the solution you'd like**
following error messages generated by flutter I realized I cannot put ```Flexible()``` inside ```Padding()``` but I wasn't using any ```Padding()```.

Padding is done inside ```Chip()```

https://github.com/bdlukaa/fluent_ui/blob/dc4ea6719ff5c5b8d7f46d86d9728575db74022c/lib/src/controls/inputs/chip.dart#L113-L118

so I edited the file and added ```Flexible()``` here:
```
Flexible(
  child: Padding(
  padding: EdgeInsets.only(
    right: spacing + visualDensity.horizontal),
    child: text,
    ),
 )
```

now the ```Text()``` doesn't overflow anymore.

so I think it should be like that as default.

**Describe alternatives you've considered**
Nothing really.

**Additional context**
Is there and other way to make ```Text()``` not overflow?

**Comment by bdlukaa** [comment]
You can try to wrap the chip itself inside of a `Flexible`, if you're using a Row

**Comment by MahdiBaghbani** [comment]
it is inside ```ListView.separated()``` which is inside ```Column()```, I guess that's the problem.
