### ISSUE TITLE
Acrylic should be used on `ComboBox`

### ISSUE THREAD

**Issue by kolyneh** [bdlukaa/fluent_ui#323]
In `acrylic.dart`:
you have 
`final disabled = DisableAcrylic.of(context) != null;`
but for ComboBox acrylicEnabled should be reversed:
https://github.com/bdlukaa/fluent_ui/blob/dc4ea6719ff5c5b8d7f46d86d9728575db74022c/lib/src/controls/form/combo_box.dart#L1180

**Comment by bdlukaa** [comment]
This should be removed because `ComboBox` doesn't make use of `Acrylic` anymore

**Comment by bdlukaa** [comment]
It was removed because it's no longer used in the latest native implementation. `menuColor` is now used instead

**Comment by kolyneh** [comment]
Ok, thank you!

**Comment by kolyneh** [comment]
Forgive me but I can't find that `Acrylic` is removed from native implementation.
Check here: [https://github.com/microsoft/WinUI-Gallery](https://github.com/microsoft/WinUI-Gallery).
Screenshot:
![image](https://user-images.githubusercontent.com/13062910/168205106-b77b4e6b-5613-4f63-9275-4f69d94c2c42.png)

**Comment by bdlukaa** [comment]
Indeed, it's still there!
