### ISSUE TITLE
🐛 When changing to FluentApp the app does not start.

### ISSUE THREAD

**Issue by KaloyanStoyanov06** [bdlukaa/fluent_ui#329]
**Describe the bug**
Whenever I use FluentApp instead of MaterialApp, the app will not run anymore. The error I get is

> error MSB8066: Custom build for 'C:\Dev\Flutter\school_windows\build\windows\CMakeFiles\cc8a942557464ba4831e718ea
> 599d009\flutter_windows.dll.rule;C:\Dev\Flutter\school_windows\build\windows\CMakeFiles\1cf43367a97fce96135f50956e09e3b3\flutter_assemble.rule' exited with code 1.

**To Reproduce**
1. Create a new Windows project
2. Run it without changing anything
3. Install FluentUI latest version
4. Change MaterialApp to FluentApp
5. Try to run it again

**Expected behavior**
It should just run as a normal App

**Screenshots**

**Additional context**
Flutter doctor -v

> [√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22616.1], locale en-GB)
>     • Flutter version 3.0.0 at D:\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
>     • Engine revision d1b9a6938a
>     • Dart version 2.17.0
>     • DevTools version 2.12.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
>     • Android SDK at C:\Users\kaloy\AppData\Local\Android\Sdk
>     • Platform android-32, build-tools 32.1.0-rc1
>     • ANDROID_HOME = C:\Users\kaloy\AppData\Local\Android\Sdk
>     • Java binary at: C:\Users\kaloy\.jdks\corretto\jdk17.0.3_6\bin\java.exe
>     • Java version OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
>     • Visual Studio Community 2022 version 17.1.32421.90
>     • Windows 10 SDK version 10.0.22000.0
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2021.3)
>     • IntelliJ at C:\Users\kaloy\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.7172.25
>     • Flutter plugin version 66.0.3
>     • Dart plugin version 213.7371
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2022.1)
>     • IntelliJ at C:\Users\kaloy\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5080.210
>     • Flutter plugin version 67.1.4
>     • Dart plugin version 221.5588
> 
> [√] VS Code (version 1.67.1)
>     • VS Code at C:\Users\kaloy\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.40.0
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22616.1]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 1 category.

**Comment by bdlukaa** [comment]
Flutter 3 is not supported *yet*. Its support may come on the next versions. See #327

**Comment by KaloyanStoyanov06** [comment]
I just downgraded. And it does work. Thank you!
