### ISSUE TITLE
Popup menu using Flyout doesn't close🐛 

### ISSUE THREAD

**Issue by pamtbaau** [bdlukaa/fluent_ui#332]
**Describe the bug**
I've implemented popup menu using the sample from the demo website. However, the menu doesn't close when tapping a menu item. Same happens with the menu flyouts on the demo website. 

Also when opening a submenu, one must click twice outside the menu to close it.

**To Reproduce**
Open demo website and click "Click to show flyout" or "Click to show flyout with subitem"

**Expected behavior**
I would expect the menu to close when tapping a menu item. I see no use-case for leaving the menu open after tapping.

**Screenshots**

**Additional context**

**Comment by pamtbaau** [comment]
Thanks for your switch answer! 

Just tested the Navigator.pop(context);. It does work for the current menu-item. It doesn't close the parent menu-item though.

Saw your shout-out for maintainers, I'm sorry I cannot help. Flutter still has so many secrets for me...

**Comment by bdlukaa** [comment]
@pamtbaau Menus with subitems will be reworked soon. I have already a sketch of how it'd look like, but I currently don't have the time to dedicate to this issue!
