### ISSUE TITLE
🐛 Double navigation bar

### ISSUE THREAD

**Issue by phorcys420** [bdlukaa/fluent_ui#336]
**Describe the bug**
Another empty navigation bar appears after expanding and downsizing the window

**To Reproduce**
1. Enlarge the window
2. Shrink the window
3. Click on the navigation button

**Expected behavior**
Only one navigation bar appears

**Screenshots**

https://user-images.githubusercontent.com/57866459/168448207-ef654d14-e94d-4e5d-a957-1914b35ebbaa.mp4

**Comment by bdlukaa** [comment]
Weird! I can not reproduce this on the example app. Can you post some reproducible code here?

**Comment by phorcys420** [comment]
> Weird! I can not reproduce this on the example app. Can you post some reproducible code here?

It happens in my ["Foreplay"](https://github.com/phorcys420/foreplay) app, but I couldn't manage to make reproducible code.. I thought it was due to me changing the size but I'm not sure anymore. (If you wanna do a quick test, I sat up actions just for this <3)

Also, I've noticed that it's kind of random and sometimes the navigation bar is double and sometimes it isn't.
https://user-images.githubusercontent.com/57866459/169702383-6525b4fa-4fc6-43e0-9115-4f25bb581266.mp4

**Comment by bdlukaa** [comment]
Looks like an issue with `NavigationPaneSize`. I can now reproduce with

```dart
size: const NavigationPaneSize(
          openMinWidth: 110,
          openMaxWidth: 110,
        ),
```
