### ISSUE TITLE
🐛 Touch screen keyboard will not popup when click the `TextFormBox`.

### ISSUE THREAD

**Issue by kolyneh** [bdlukaa/fluent_ui#343]
**Describe the bug**
Touch screen keyboard will not popup when click the `TextFormBox`.

**To Reproduce**
1. Run the sample app on a touch screen Windows tablet.
2. Click on 'Form'
3. Click the email text box.

**Expected behavior**
Touch screen keyboard should popup when click the `TextFormBox`.

**Comment by kolyneh** [comment]
Touch screen keyboard is showing up with the `Web` example though.

**Comment by bdlukaa** [comment]
Does the keyboard show up when using materia's `TextField`?

**Comment by kolyneh** [comment]
Yes,  It does!

**Comment by kolyneh** [comment]
Added a `TextFormField` to the forms page's head.

```
material.Card(
    child: material.TextFormField(),
),
```

https://user-images.githubusercontent.com/13062910/169434511-653a9f58-b8d0-45a5-9a20-5abd6396da45.mp4

**Comment by bdlukaa** [comment]
Is it an issue with only `TextFormBox`? `TextBox` works?

**Comment by kolyneh** [comment]
Neither. In the video you can see the `Password` form which is a `TextBox`. It did not pop keyboard.
