### ISSUE TITLE
TextBox has not ‘initialValue’

### ISSUE THREAD

**Issue by jonahzheng** [bdlukaa/fluent_ui#344]
TextFormBox has ‘initialValue’, but TextBox has not.
![~VAN)X1FF7%@_Q ~1JE09}M](https://user-images.githubusercontent.com/5125282/169268947-eba47e67-239c-4a6f-8283-87e5b4d5aa98.png)

**Comment by harysuryanto** [comment]
I think TextFormBox and TextBox use reference from TextFormField and TextField from Material, where TextFormField has `initialValue`, and TextField does not. However, you can use `controller` to set initial value to both widgets.
