### ISSUE TITLE
🐛 DatePicker & TimePicker freeze

### ISSUE THREAD

**Issue by Alphamplyer** [bdlukaa/fluent_ui#363]
**Describe the bug**
The DatePicker and the TimePicker freeze the whole app while scrolling slowly for a certain amount of time.

**To Reproduce**
1. Open Example App
2. Click on 'Form'
3. Open the DatePicker or the TimePicker
4. Slowly scroll down one column (day, hour, day, ...)
5. See error

**Expected behavior**
We expect the DatePicker or the TimePicker to not freeze the whole app when scrolling.

**Screenshots**
![DatePickerTest](https://user-images.githubusercontent.com/42153930/169700136-07156096-daea-4390-bf8c-42ce78cd36c4.gif)

**Additional context**
Nothing

**Comment by bdlukaa** [comment]
This issue is no longer reproducible in the latest version
