### ISSUE TITLE
Combobox to ComboboxFormField 

### ISSUE THREAD

**Issue by catapult0** [bdlukaa/fluent_ui#373]
Hi,

I'm trying to find an elegant and speedy manner to transform Combobox to a ComboboxFormField. My intention is to use this filed in a regular form and have access to certain FormField class properties and styling, such as : 

* display validation error message, when input is empty for example
* have initial value property
* textInputAction
* etc.

Similarly, AutoSuggestBox could use the same features.

By the way, I found a comment in the Combobox class : 
// When adding new arguments, consider adding similar arguments to
// ComboboxFormField.

this "ComboboxFormField" is no where to be found, is it legacy code ?

Anyways, would greatly appreciate a tip from you guys ;) @bdlukaa 

Best

**Comment by bdlukaa** [comment]
<https://docs.microsoft.com/en-us/windows/apps/design/controls/combo-box#make-a-combo-box-editable>
