### ISSUE TITLE
🐛 Combobox animation is not correct

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#379]
**Describe the bug**

Dropdown has transparent effect and close is delayed, see the gif below:

![fluent_dropdown](https://user-images.githubusercontent.com/8223773/171201434-88e4ddfc-4b01-44ef-80c4-fe59bbdb0a5f.gif)

After update fluent_ui dep (currently on master).

(Windows 10)

**Comment by bdlukaa** [comment]
You mean `ComboBox`, right?

**Comment by WinXaito** [comment]
Uhh, not sure, I need to check that. ComboBox/DropDown is a change since fluent_ui 3.8.0 ?

**Comment by WinXaito** [comment]
Ok, after testing, removing `DisableAcrylic` fix the transparency problem, but ... I have Acrylic :( I don't want it.

And the freeze-problem is still present.

**Comment by bdlukaa** [comment]
Are you running it in debug mode? Can you try profile or release mode?

**Comment by WinXaito** [comment]
I'm in debug mode, but that was work before.

I see the same effect on the web demo (and this is release mode..) 

https://bdlukaa.github.io/fluent_ui/

-> Forms -> Color ComboBox
Or: InfoBar -> see the combobox

**Comment by DemoJameson** [comment]
looks like it was introduce by this commit
https://github.com/bdlukaa/fluent_ui/commit/75390875393c2b87cc8b425c55882875aef324aa
