### ISSUE TITLE
🐛Scrollable Horizontal List within a Scrollable Vertical List doesn't scroll

### ISSUE THREAD

**Issue by bariccattion** [bdlukaa/fluent_ui#403]
**Describe the bug**
I am trying to achieve a very common behavior nowadays which is to have a Scroll-able Horizontal List within a Scroll-able Vertical List.

However, that doesn't seem to work while using FluentUI. It may be something that I'm doing wrong, but I've tried multiple ways to do it, and they all don't work. 

The Inner Horizontal List doesn't scroll, and just crops the remaining items inside

**To Reproduce**
1. Go to [This Repo](https://github.com/bariccattion/fluent_ui_horscroll_bug)
2. Clone it
3. Run 'flutter create .' in the terminal to generate the platform specific builds
4. Run 'flutter run' to start the App

**Expected behavior**
Example of what it should do
![MRXOq](https://user-images.githubusercontent.com/19714408/175059547-480bac4c-9dc5-4881-a5a5-9dc3aef8c680.gif)

**Screenshots**
![HorizontalBug](https://user-images.githubusercontent.com/19714408/175059360-925e0589-39c9-418a-b5df-82d99a57eb40.gif)

**Comment by bariccattion** [comment]
Any updates on this? 🥲

**Comment by bariccattion** [comment]
Any updates on this? 🥲 (closed by mistake)

**Comment by bdlukaa** [comment]
I am almost sure this is an issue with flutter, not fluent ui. I will do some testings

**Comment by bdlukaa** [comment]
I can scroll with my trackpad horizontally, but not with my mouse. This is Flutter issue. We have the same issue with `TabView`, and we use a workaround with `Listener`

- https://github.com/flutter/flutter/issues/75180
- https://stackoverflow.com/a/70916607/11622876
- https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/tab_view.dart#L378-L395

Closing as invalid
