### ISSUE TITLE
🐛 [UI/Fidelity] DatePicker: Year in two lines

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#404]
**Describe the bug**

In `DatePicker` widget the year is displaying using two lines.

**To Reproduce**
1. Go to new FluentUI Showcase app ( https://bdlukaa.github.io/fluent_ui/ )
2. Click on 'DatePicker'
3. Click on first component

**Expected behavior**
Year is shown with one line

**Screenshots**

<img width="258" alt="Captura de Pantalla 2022-06-23 a las 7 35 36" src="https://user-images.githubusercontent.com/4610108/175223111-59941196-fa48-469f-9486-d058baf6d6b0.png">

**Additional context**

Maybe this is related with locale and too long contents for month literals? In Spanish we have month names as long as "_Septiembre_".

Similar but probably not related with https://github.com/bdlukaa/fluent_ui/issues/382

**Comment by bdlukaa** [comment]
This only happens with the web version
