### ISSUE TITLE
Slider size customizations

### ISSUE THREAD

**Issue by T99Rots** [bdlukaa/fluent_ui#405]
Currently it's not possible to customize the size of the slider thumb or slider track. Exposing the `disabledThumbRadius`, `enabledThumbRadius` and `trackHeight` values through either the theme of just directly through the `Slider` class would solve this!

About the part of the track after the slider thumb, I'm not sure about how to change in height based on reading the code, but being able to make it the same height as the first part of the slider track would be a great option as well and should maybe be the default when looking at the fluent design example.

**Comment by bdlukaa** [comment]
Please, next time fill the issue template!

About the inactive track height, indeed, it should be the same.
