### ISSUE TITLE
DatePicker does not show selected date🐛 

### ISSUE THREAD

**Issue by pamtbaau** [bdlukaa/fluent_ui#415]
**Describe the bug**
DatePicker shows placeholder texts 'year', 'month' and 'day' when value of property 'selected' is null;
DatePicker is empty when value of property 'selected' is set to a valid DateTime.

**To Reproduce**
Add the following to widget:
```
DatePicker(
  selected: selectedDate,
  fieldOrder: const [DatePickerField.year, DatePickerField.month, DatePickerField.day],
  onChanged: (DateTime date) {
    selectedDate = DateTime(date.year, date.month, date.day);
    setState(() {});
  },
)
```
- On first paint of widget, variable 'selectedDate' is null. DatePicker shows placeholders. 
![image](https://user-images.githubusercontent.com/5120011/177515135-730e055b-2e58-47db-aa15-cd5715de0e7d.png)

- After selecting a date, fields year, month, day remain empty.
![image](https://user-images.githubusercontent.com/5120011/177515303-4c584b3e-b366-4e22-a760-d746153443cf.png)

- When opening the datepicker, it shows correctly the date from variable 'selectedDate'

**Expected behavior**
I expect the fields year, month, day to be filled with the selected date.

**Screenshots**

**Additional context**

**Comment by bdlukaa** [comment]
looks like the text color isnt applied to them

**Comment by pamtbaau** [comment]
Downloaded latest master and DatePicker is working fine. Thanks!
