### ISSUE TITLE
Data Table in fluent ui

### ISSUE THREAD

**Issue by Arpit1496** [bdlukaa/fluent_ui#420]
Wouldn't it be nice if we had a Data Table kind of view/widget to replicate excel sheets on flutter ? 
Using material data table third party libraries need material app as parent widget.

**Comment by gucci-quoci** [comment]
Duplicate of [#249](https://github.com/bdlukaa/fluent_ui/issues/249)

**Comment by gucci-quoci** [comment]
If you still want to use the DataTable from Material, you can wrap it with a [Material](https://api.flutter.dev/flutter/material/Material-class.html).
```
Material(
  child: DataTable()
)
```

**Comment by bdlukaa** [comment]
Closing as duplicate
