### ISSUE TITLE
Mouse state colors should not be animated

### ISSUE THREAD

**Issue by Arpit1496** [bdlukaa/fluent_ui#421]
Why is the animation for highlight slow when cursor hover is triggered ?

**Comment by bdlukaa** [comment]
wdym?

**Comment by Arpit1496** [comment]
If you go to official demo page and see it in navigation pane, when we bring cursor to any item, the time taken to highlight the currently pointed item is very high.

**Comment by bdlukaa** [comment]
Indeed. See https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/NavigationView/NavigationView_rs1_themeresources.xaml
