### ISSUE TITLE
🐛 Flyout Widgetis not hot reload friendly

### ISSUE THREAD

**Issue by Arpit1496** [bdlukaa/fluent_ui#429]
Whenever we hot reload a widget which has Flyout as a child, the Flyout does not open(with clock by controller) after hot reload until we re-build the parent.

**Comment by RedyAu** [comment]
Flyout controllers are not reliable in general. I have Flyouts on DataCells, and when I change pages on the DataTable, the Flyouts don't open anymore on the new page, only when I re-initialize the whole page.
Please let me know what other info I can provide to help you track this down

**Comment by RedyAu** [comment]
Update: It got fixed by assigning a GlobalKey() to the Flyout. It feels like this shouldn't be necessary? I may be wrong.
