### ISSUE TITLE
list_tile.dart at  v.3.12.0

### ISSUE THREAD

**Issue by longfit** [bdlukaa/fluent_ui#432]
Since I try to use examples of tiles.dart but some list_tiitle.dart changed !

I don't know how to correct the example 
Could you show me how to change

const contacts = ['Kendall', 'Collins', ...];

ListView.builder(
  itemCount: contacts.length,
  itemBuilder: (context, index) {
    final contact = contacts[index];
    return ListTile.selectable(
      title: Text(contact),
      selected: selectedContact == contact,
      onSelectionChange: (v) => setState(() => selectedContact = contact),
    );
  } 
)

**Comment by bdlukaa** [comment]
What version are you using? These tiles are from the latest version (4.0.0-pre.1)

You can see the documentation for 3.12.0 [here](https://pub.dev/documentation/fluent_ui/latest/fluent_ui/ListTile-class.html)

**Comment by longfit** [comment]
Noted with thanks

I am using 4.0.0-pre.1 

for example tiles.dart.
Don't know how to make use of TappableTitle to modify the example

ListViewItems with many properties applied
ListViewItems with images

**Comment by bdlukaa** [comment]
Oh, tiles were implemented on #422 but it hasn't reached pub.dev yet! To try it out, you can use the git version. See [installation instructions here](https://github.com/bdlukaa/fluent_ui#installation)

**Comment by bdlukaa** [comment]
Published a new version where tiles are included. Check it out on https://pub.dev/packages/fluent_ui/versions/4.0.0-pre.2
