### ISSUE TITLE
🐛CPU usage is too high.

### ISSUE THREAD

**Issue by j787701730** [bdlukaa/fluent_ui#44]
use  https://github.com/bdlukaa/fluent_ui/tree/master/example  example code
![image](https://user-images.githubusercontent.com/23625690/120618648-d94bfa00-c48d-11eb-98a7-c9433d8eaa88.png)

**Comment by bdlukaa** [comment]
It's not related to the package, but flutter itself. See https://github.com/flutter/flutter/issues/78517#issuecomment-846436969 to solve it

**Comment by j787701730** [comment]
@bdlukaa thank you
