### ISSUE TITLE
Add option to make tooltip not automatically go away when itself is hovered

### ISSUE THREAD

**Issue by damywise** [bdlukaa/fluent_ui#443]
**Is your feature request related to a problem? Please describe.**
The tooltip automatically goes away when hovered, and then immediately shows itself again, infinitely.

**Describe the solution you'd like**
Add an option to Tooltip, like so:
```dart
Tooltip(
  ...
  hideOnHover: false,
  ...
)
```

**Describe alternatives you've considered**
None

**Additional context**
Record of current state: (tooltip is at top right)

https://user-images.githubusercontent.com/25608913/181230152-e5267256-671e-4dfe-9b8f-ff18c639eb09.mp4

**Comment by bdlukaa** [comment]
Can you post here a reproducibe snippet of this issue?

**Comment by damywise** [comment]
Here you go
```dart
import 'package:fluent_ui/fluent_ui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FluentApp(
      title: 'Flutter Demo',
      home: Align(
        child: Tooltip(
          style: const TooltipThemeData(
            verticalOffset: -1,
          ),
          message: "Issue #443",
          child: Container(
            color: Colors.red,
            width: 32,
            height: 32,
          ),
        ),
      ),
    );
  }
}
```
