### ISSUE TITLE
Why not add footer into NavigationPane?

### ISSUE THREAD

**Issue by ccl0326** [bdlukaa/fluent_ui#448]
**Is your feature request related to a problem? Please describe.**
In my case i want to use pane only in NavigationView, if there is no app bar i should add WindowCaption in to pane's right side, but there is no widget can fit. 

**Describe the solution you'd like**
add footer not only footer item in to NavigationPane.

**Comment by ccl0326** [comment]
Sorry, i think customPane can help me.

**Comment by bdlukaa** [comment]
You can use a custom pane item:

https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart#L483-L522

**Comment by ccl0326** [comment]
@bdlukaa thx
