### ISSUE TITLE
🐛 actions property in NavigationAppBar not showing the widget in fluent_ui: ^4.0.0-pre.2

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#449]
In previous version the WindowCaption was showed but to this prerelease the window buttons were not showing.
<img width="1180" alt="Screen Shot 2022-08-04 at 9 11 30 AM" src="https://user-images.githubusercontent.com/40779451/182741859-08e28b77-479a-4ddb-820b-5ce3878b36d1.png">

**Comment by bdlukaa** [comment]
Sorry, but I can not reproduce it :/

Can you try the following steps?

- close the app
- run `flutter clean`
- run the app again

**Comment by adpmhel24** [comment]
I already did that. The widgets in actions property will show only if the automaticallyImplyLeading set to true. This bug occur in version 4.0.0pre2

**Comment by bdlukaa** [comment]
Sorry, but I can not reproduce this issue in the example app.

`automaticallyImplyLeading: true`:

![example 10_08_2022 18_36_41](https://user-images.githubusercontent.com/45696119/184024937-4515e65c-2bc6-4639-a020-54456b1d7b36.png)

`automaticallyImplyLeading: false`:

![example 10_08_2022 18_38_22](https://user-images.githubusercontent.com/45696119/184025067-aa6ef504-dde1-4444-957c-dd211e5729c1.png)
