### ISSUE TITLE
[example app] Splash on linux

### ISSUE THREAD

**Issue by 21pages** [bdlukaa/fluent_ui#451]
**Describe the bug**
 Splash on linux

**To Reproduce**
1. cd example
2. flutter create .
3. flutter run -d linux

**Screenshots**

![1659661916568](https://user-images.githubusercontent.com/14891774/182980654-4efbdd0c-5c3c-4cb5-b4ed-f2774fdf8b13.png)

**Comment by bdlukaa** [comment]
Do you have any window features on?

**Comment by 21pages** [comment]
> Do you have any window features on?

all default
ubuntu 22.04
