### ISSUE TITLE
v4: When AutoSuggestBox resizes, it re-opens its dropdown🐛 

### ISSUE THREAD

**Issue by pamtbaau** [bdlukaa/fluent_ui#456]
**Describe the bug**
I have a Row that contains two widgets:
- AutoSuggestBox inside an Expanded
- TextBox inside an IntrinsicWidth

When a selection is made with AutoSuggestBox, in its onSelected event, the controller.text is set for the TextBox. Since the TextBox is inside an IntrinsicWidth, it resizes when the length of its content changes, which in turn causes a resize of the AutoSuggestBox.

When the resize of the AutoSuggestBox happens, it re-opens its dropdown.

This behaviour happens with **version 4.0.0-pre.2** and not with **version 3**.

**Note:** This behaviour does not occur when the resize of the AutoSuggestBox happens due to a Button click. It only happens when the resize is caused during the onSelected event of the AutoSuggestBox.

**To Reproduce**
A reproducible case is available

**Expected behavior**
Like with v3 of fluent_ui, I expect the dropdown not to re-open when the AutoSuggestBox resizes.

**Screenshots**

**Additional context**

**Comment by bdlukaa** [comment]
For reference: https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/form/auto_suggest_box.dart#L396-L400

We must check if popup is open before opening it

**Comment by pamtbaau** [comment]
Tested and working fine!

Thank you very much :-)
