### ISSUE TITLE
TextFormBox Validator is dont work🐛 

### ISSUE THREAD

**Issue by BardoGOD** [bdlukaa/fluent_ui#462]
**Describe the bug**
I am using the validator correctly but it does not work or show any error in the field used

**To Reproduce**
    return TextFormBox(
        controller: _controller,
        header: _txtlabel,
        validator: (text) {
          if (text == null || text.isEmpty) return 'obligatorio';
        });
**Screenshots**
![image](https://user-images.githubusercontent.com/99101666/184202563-9cde842b-489f-4f3b-a591-2eb5e264b697.png)

**Comment by bdlukaa** [comment]
You must use a `Form` widget to valide or enable auto validation
