### ISSUE TITLE
🐛 DisableAcrylic and comboboxColor not working.

### ISSUE THREAD

**Issue by wachidsusilo** [bdlukaa/fluent_ui#468]
**Describe the bug**
1. How to disable Acrylic? `DisableAcrylic` seems not working, my `ComboBox` still transparent.
2. How to disable animation? The animation seems wrong to me, it happen from bottom to top, when it should be the opposite.
3. `comboboxColor` seems not working. No matter what color i choose, there is no different.

**To Reproduce**
```dart
DisableAcrylic(
  child: Combobox<String>(
    comboboxColor: Colors.green,
    value: 'COM4',
    items: [
      ComboboxItem(
        value: 'COM1',
        child: Text('COM1'),
      ),
      ComboboxItem(
        value: 'COM2',
        child: Text('COM2'),
      ),
      ComboboxItem(
        value: 'COM3',
        child: Text('COM3'),
      ),
      ComboboxItem(
        value: 'COM4',
        child: Text('COM4'),
      ),
      ComboboxItem(
        value: 'COM5',
        child: Text('COM5'),
      ),
    ],
    onChanged: (com) {
      print(com);
    },
  ),
);
```

**Expected behavior**
1. When disabled, The `ComboBox` should not be transparent anymore. What is the purpose of creating another `Widget` anyway? Why not just add parameter to the `ComboBox` widget it self? I think it would be more intuitive,
2. Animation should happen from top to bottom (or at least give option to change the direction or disable it).
3. `ComboBox` background color should be changed according to the `comboboxColor` value.

**Comment by bdlukaa** [comment]
What version are you using?

**Comment by wachidsusilo** [comment]
@bdlukaa Thanks for the quick response, really appreciate it.
Well, i started using flutter 2 days ago. I'm not familiar with this `dart` and `pub` things yet. I guess i use the same version as in here (Github).
here is my `pubspec.yaml`:
```yaml
dependencies:
  flutter:
    sdk: flutter
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
```
