### ISSUE TITLE
Bug TextFormBox minLines or maxLines: "no ScrollPosition attached"🐛 

### ISSUE THREAD

**Issue by BardoGOD** [bdlukaa/fluent_ui#474]
**Describe the bug**
Hello, when I use the fields of maximum or minimum lines in my TextFormBox they work well but when reducing the size of the flutter page it gives the following error:

"The Scrollbar's ScrollController has no ScrollPosition attached."

I already tried different methods and the only solution I find is to remove the maximum and minimum lines of my forms

**Screenshots**
![image](https://user-images.githubusercontent.com/99101666/185168867-b2d74319-7325-4f98-94e5-a1782d45d6f8.png)

**Comment by bdlukaa** [comment]
What version are you using? Could you provide a reproducible snippet?

**Comment by BardoGOD** [comment]
> 
Versión: 
Fluent: 4.0.0-pre.2

Code (In row widget):
TextFormBox(
      minLines: 1,
      maxLines: 3,
      controller: _controller,
      header: _txtlabel,
      autovalidateMode: AutovalidateMode.onUserInteraction,
      key: _formKey,
      validator: (value) =>
          value != null && value.isEmpty ? '$_txtlabel es obligatorio' : null,
    );

**Comment by bdlukaa** [comment]
Sorry, but I can't reproduce this issue.

**Comment by BardoGOD** [comment]
fixed with scrollbar controller on the field text
