### ISSUE TITLE
Missing right click functionality

### ISSUE THREAD

**Issue by Auties00** [bdlukaa/fluent_ui#489]
**Is your feature request related to a problem? Please describe.**
An important feature for desktop platforms is to be able to execute code if an element is clicked with the right button of the mouse. 
This is, as far as I can tell, not possible currently.

**Describe the solution you'd like**
This can be easily implemented using the Listener class(from the library itself), implementing the onPointerDown method and checking if the device type is a mouse and the buttons field == kSecondaryMouseButton (aka 0x02). 
The implementation is quite simple, but many widgets only support particular children types so you can't wrap them with a listener yourself(ex. DropDownButton which takes List<MenuFlyoutItem>)

**Describe alternatives you've considered**
An alternative is to make all widgets with a children field accept any widget instead of only particular types. This may be helpful even with this feature introduced as I explained.

**Comment by b34st80y** [comment]
Hello,

Maybe I am misunderstanding, but; 

> many widgets only support particular children types so you can't wrap them with a listener yourself

Why exactly would you want the Listener as a child of DropDownButton?

I was able to wrap a DropDownButton in a Listener and use the strategy you mentioned (device type is a mouse and the buttons field == kSecondaryMouseButton)

![image](https://user-images.githubusercontent.com/19982841/186978701-5d8fa636-4e54-48f3-8ae9-31006e299bb1.png)


This produces a result like this: 
![image](https://user-images.githubusercontent.com/19982841/186978257-f314260a-f496-4e36-9776-200a0cab869d.png)

If you are trying to make each dropdown item have a right click menu that can be accomplished as well like so:

![image](https://user-images.githubusercontent.com/19982841/186979033-1f860088-3150-4a57-998b-ae1c29c07d19.png)

![image](https://user-images.githubusercontent.com/19982841/186978984-a1323f32-93d3-4bec-b14b-91fe3e39bda7.png)

**Comment by bdlukaa** [comment]
@Auties00 what widgets are you talking about?

**Comment by Auties00** [comment]
> Hello,
> 
> Maybe I am misunderstanding, but;
> 
> > many widgets only support particular children types so you can't wrap them with a listener yourself
> 
> Why exactly would you want the Listener as a child of DropDownButton?
> 
> I was able to wrap a DropDownButton in a Listener and use the strategy you mentioned (device type is a mouse and the buttons field == kSecondaryMouseButton)
> 
> ![image](https://user-images.githubusercontent.com/19982841/186978701-5d8fa636-4e54-48f3-8ae9-31006e299bb1.png)
> 
> This produces a result like this: ![image](https://user-images.githubusercontent.com/19982841/186978257-f314260a-f496-4e36-9776-200a0cab869d.png)
> 
> If you are trying to make each dropdown item have a right click menu that can be accomplished as well like so:
> 
> ![image](https://user-images.githubusercontent.com/19982841/186979033-1f860088-3150-4a57-998b-ae1c29c07d19.png)
> 
> ![image](https://user-images.githubusercontent.com/19982841/186978984-a1323f32-93d3-4bec-b14b-91fe3e39bda7.png)

Oh yeah I guess that would work, I didn't think about that, but for example if you had a leading or a trailing you would have needed to duplicate the Listener which is kind of annoying. That's why i was proposing it as a first party feature, I could open a PR myself if it's something people want

**Comment by bdlukaa** [comment]
@Auties00 for `DropDownButton`, specifically, you can create a new class that extends `MenuFlyoutItem` and use it on the dropdown button. Something like `PaneItem`.

Here's an example:

```dart
class CustomItem extends MenuFlyoutItem {

...

  Widget build(BuildContext context) {
    return Listener(
       child: super.build(context);
    );
  }

...

}
```

**Comment by Auties00** [comment]
> @Auties00 for `DropDownButton`, specifically, you can create a new class that extends `MenuFlyoutItem` and use it in the `items`. Something like `PaneItem`.
> 
> Here's an example:
> 
> ```dart
> class CustomItem extends MenuFlyoutItem {
> 
> ...
> 
>   Widget build(BuildContext context) {
>     return Listener(
>        child: super.build(context);
>     );
>   }
> 
> ...
> 
> }
> ```

yeah thanks. Sorry for the late response!
