### ISSUE TITLE
🐛 TabView: No MaterialLocalizations found 

### ISSUE THREAD

**Issue by huntergps** [bdlukaa/fluent_ui#492]
I am trying to use the TabView control with Getx, but when displaying the window with the component it shows the error "No MaterialLocalizations found."

![image](https://user-images.githubusercontent.com/955008/186950297-bd64e4dc-ca91-4ec5-82e8-f1d16759efdd.png)

This is the initialization code
![image](https://user-images.githubusercontent.com/955008/186950469-7594f5e8-d780-4163-a972-1c586d38aaae.png)

Help please!!!

**Comment by bdlukaa** [comment]
For a workaround, add `DefaultMaterialLocalizations.delegate` yo your delegates
