### ISSUE TITLE
Match the new Windows Design System

### ISSUE THREAD

**Issue by bdlukaa** [bdlukaa/fluent_ui#50]
> Windows 11 marks a visual evolution of the operating system. We have evolved our design language alongside with Fluent to create a design which is human, universal and truly feels like Windows.

[Learn more](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/design-principles)

![Controls Preview](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/images/color_dark_controls_940.png)

The following widgets needs to be updated (ordered alphabetically):

- [x] Button (#57)
- [x] Checkbox (#60)
- [x] ComboBox (#64)
- [x] ContentDialog (#54)
- [x] InfoBar (#63)
- [x] NavigationView (#52)
- [ ] ProgressBar
- [x] RadioButton (#56)
- [x] Scrollbar (#62)
- [x] Slider
- [x] TextBox (#55)
- [x] ToggleButton (#57)
- [x] ToggleSwitch (#61)

**Comment by bdlukaa** [comment]
<https://github.com/microsoft/microsoft-ui-xaml>

**Comment by bdlukaa** [comment]
NavigationView reworked on #52 
![image](https://user-images.githubusercontent.com/45696119/124169952-36cb6a80-da7d-11eb-8dec-0634fdde842c.png)

**Comment by bdlukaa** [comment]
ContentDialog reworked on #54
![ContentDialog](https://user-images.githubusercontent.com/45696119/124335462-bb4ae580-db70-11eb-8045-5fea9d38e8a3.png)

**Comment by bdlukaa** [comment]
TextBox reworked on #55 

![](https://user-images.githubusercontent.com/45696119/124392676-7a1c1800-dccd-11eb-980a-76b96da31848.png)

**Comment by CodeDoctorDE** [comment]
Hi, can this be an configurable? It would be cool, if I can select this by an property to change this if you use windows 11 or windows 10

**Comment by bdlukaa** [comment]
you can use the 2.x.x versions on pub or the 2.0.0 branch from GitHub. These 2.x.x versions will still be updated
