### ISSUE TITLE
Use `flutter gen-l10n` command instead of `flutter intl` plugin to generate localizations

### ISSUE THREAD

**Issue by DemoJameson** [bdlukaa/fluent_ui#500]
**Is your feature request related to a problem? Please describe.**
If both app and fluent_ui localizations are generated via `flutter intl plugin`, then they cannot work together
https://github.com/localizely/flutter-intl-intellij/issues/22

**Describe the solution you'd like**
Use `flutter gen-l10n` command instead of `flutter intl` plugin
https://docs.flutter.dev/development/accessibility-and-localization/internationalization

**Comment by DemoJameson** [comment]
It doesn't seem to be fixed
![image](https://user-images.githubusercontent.com/181192/187580815-163c1908-4956-46b6-b6a0-f9835f3b7208.png)
![image](https://user-images.githubusercontent.com/181192/187581003-27dfd700-2cc0-47cb-826f-a20e8b28c4da.png)

**Comment by bdlukaa** [comment]
Are you using the latest master?

 `S` was renamed to `FluentS`. I tested on the example app and localization is working as expected

**Comment by DemoJameson** [comment]
> Are you using the latest master?
> 
> `S` was renamed to `FluentS`. I tested on the example app and localization is working as expected

it doesn work, you can check the details from plugin issue
![image](https://user-images.githubusercontent.com/181192/188896649-aea853e0-d4ab-4d27-8892-2ec82ffa9c95.png)

**Comment by bdlukaa** [comment]
Can you post the error stacktrace here?

**Comment by DemoJameson** [comment]
there is no error is thrown, you can check my test example
https://github.com/DemoJameson/fluent_ui/commit/7161fafec39afaff0e79784f802b0f41fbc2fbed
