### ISSUE TITLE
I have the following needs: PaneItemExpander

### ISSUE THREAD

**Issue by CurrentIndex** [bdlukaa/fluent_ui#506]
**Is your feature request related to a problem? Please describe.**
```dart
NavigationView(
  appBar: const NavigationAppBar(
    title: Text('NavigationView'),
  ),
  pane: NavigationPane(
    selected: topIndex,
    onChanged: (index) => setState(() => topIndex = index),
    displayMode: displayMode,
    items: [
      PaneItem(
        icon: const Icon(FluentIcons.issue_tracking),
        title: const Text('Track an order'),
        infoBadge: const InfoBadge(source: Text('8')),
      ),
      // I saw it in the web example.
      // I have the following needs:
      PaneItemExpander(
        icon: const Icon(FluentIcons.account_management),
        title: const Text('Account'),
        items: [
          PaneItem(
            icon: const Icon(FluentIcons.mail),
            title: const Text('Mail'),
          ),
        ],
      ),
    ],
  ),
  body: ...
```
**Describe the solution you'd like**
> I want to know which version of paneitemexpander is available so that I can modify and add it to the project

**Describe alternatives you've considered**
.

**Additional context**
```text
NavigationView -> NavigationPane -> PaneItemExpander,
```
> ![image](https://user-images.githubusercontent.com/59065234/187763201-c86b43ec-a02f-4c0a-9bc0-6b6e4ce74cf7.png)

**Comment by bdlukaa** [comment]
The version has not been published yet :/ You can use the github version: https://github.com/bdlukaa/fluent_ui#installation

https://github.com/bdlukaa/fluent_ui/blob/master/CHANGELOG.md
