### ISSUE TITLE
🐛 The name 'Colors' is defined in the libraries 'package:fluent_ui/src/styles/color.dart (via package:fluent_ui/fluent_ui.dart)' and 'package:flutter/src/material/colors.dart (via package:flutter/material.dart)'.

### ISSUE THREAD

**Issue by Patrick386** [bdlukaa/fluent_ui#51]
Flutter Web:

I want to use this package, but I can't use it because of the following problem. How can I solve this?

![스크린샷 2021-06-27 오후 4 23 12](https://user-images.githubusercontent.com/49754877/123536246-302eb180-d764-11eb-8fe7-ce386bd9b5f0.png)

**Comment by bdlukaa** [comment]
you're trying to import both fluent and material libraries. Please import only one.

If you need to import both, use:

```dart
import 'package:flutter/material.dart' as material;
import 'package: fluent_ui/fluent_ui.dart';
```

**Comment by bdlukaa** [comment]
Do you still see this issue?

**Comment by Patrick386** [comment]
Unfortunately, that doesn't solve the problem.

![2021-07-02_135741](https://user-images.githubusercontent.com/49754877/124222914-a012b280-db3d-11eb-887e-42198951a6c3.png)

![2021-07-02_135805](https://user-images.githubusercontent.com/49754877/124222906-9db05880-db3d-11eb-82e2-bb3b6a57361d.png)

![2021-07-02_135818](https://user-images.githubusercontent.com/49754877/124222918-a2750c80-db3d-11eb-9a03-e189912cbc2c.png)

**Comment by JohnOyekanmi** [comment]
> Unfortunately, that doesn't solve the problem.
> 
> ![2021-07-02_135741](https://user-images.githubusercontent.com/49754877/124222914-a012b280-db3d-11eb-887e-42198951a6c3.png)
> 
> ![2021-07-02_135805](https://user-images.githubusercontent.com/49754877/124222906-9db05880-db3d-11eb-82e2-bb3b6a57361d.png)
> 
> ![2021-07-02_135818](https://user-images.githubusercontent.com/49754877/124222918-a2750c80-db3d-11eb-9a03-e189912cbc2c.png)

To use scaffold you'll have to do: `material.Scaffold(...)`

To use any api, widget or Classes defined in the material Libraries you'll have to add a `material.` (or the name used in importing the material Library) prefix before the concerned item.

You can try hiding the `Colors` class api from being exposed by importing the material library this way:

`import 'package:flutter/material.dart'  hide Colors;
import 'package: fluent_ui/fluent_ui.dart';`

This will hide the Colors api from being exposed in the import. You can also use this same method to hide it from the fluent_ui package as well.

**Comment by bdlukaa** [comment]
Yes! I don't see why to use both libraries together, anyways.

Can this issue be closed?

**Comment by Patrick386** [comment]
Yes, you can close it.
It's a great package. Thank you.

**Comment by bdlukaa** [comment]
thanks :)
