### ISSUE TITLE
Background blur with Acrylic does not work

### ISSUE THREAD

**Issue by BardoGOD** [bdlukaa/fluent_ui#513]
I need to apply this background effect throughout the app but I can't do it, acrylic only modifies the windows control bar

reference: 
https://github.com/bdlukaa/fluent_ui/issues/21

![image](https://user-images.githubusercontent.com/99101666/188502008-8b06c021-47b2-4047-ba13-1b7adc21b616.png)

Code:
![image](https://user-images.githubusercontent.com/99101666/188502024-e58f260e-870b-497c-9df9-bc5810b0291f.png)

**Comment by bdlukaa** [comment]
You need to set the `NavigationView` background color to transparent.

https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart#L120-L125

**Comment by BardoGOD** [comment]
The navigation Pane is changed and work, but the navigation body dont change.

![image](https://user-images.githubusercontent.com/99101666/189717347-2b993de0-fefa-4d98-a5bb-de66fe481028.png)

Code:
![image](https://user-images.githubusercontent.com/99101666/189717495-16698903-98c1-4750-b299-00a62479ae9f.png)
