### ISSUE TITLE
TreeView: lazy loading

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#522]
1. I would like to delegate the lazy loading to TreeViewItem. Currently, the user has to set the `loading` flag and add the children themself. See my comments in your showcase example:

```
final lazyItems = [
  TreeViewItem(
    content: const Text('Work Documents'),
    lazy: true,
    children: [],
    onInvoked: (item) async {
       if (item.children.isNotEmpty) return;
      setState(() => item.loading = true);                  // I think this is something TreeViewItem should do internally
      await Future.delayed(const Duration(seconds: 2));
      setState(() {
        item
          ..loading = false                                 // same here
          ..children.addAll([                               // same here
 ...
```
2. Also it feels unintuitive to me, that the loading starts when invoking the item. It should only start when the user tries to expand the item.

**Solution proposal**
For 1.:
Maybe we could have a separate `onLazyLoad` callback which explicitly handles lazy loading. Something like 
`final Future<List<TreeviewItem>> Function(TreeViewItem item)? onLazyLoad` for `TreeViewItem` and 
`final Future<List<TreeviewItem>> Function(TreeViewItem item)? onItemLazyLoad` for `TreeView`.

As you can see, it has to return a `List<TreeViewItem>` that can be set internally as the item's children.

For 2.:
This is the behaviour, I'd expect:
![Fluent_UI_TreeView_Lazy_onExpand](https://user-images.githubusercontent.com/103884835/189169342-a59ba3c7-8ac4-446b-a06b-f8bd1ebbd363.gif)

As you can see, the loading doesn't start when invoking the item but when expanding it. Also, lazy loading can be used even if the parent containing TreeView is Stateless.

This would be the code then needed to setup a TreeViewItem that loads is children lazily:
```
final lazyItems = [
   TreeViewItem(
      content: const Text('Item with lazy loading'),
      lazy: true,
      children: [],
      onLazyLoad: (item) async {
         if (item.children.isNotEmpty) return item.children;

         return await someFunctionThatReturnsAListOfTreeViewItems;
      }),
...
]
```

**Alternatives**
Maybe I am using TreeView and the lazy-flag wrong and my proposed changes are not necessary at all. Then I'm happy to learn how it's actually done. ; )

**Comment by bdlukaa** [comment]
> setState(() => item.loading = true);                  // I think this is something TreeViewItem should do internally

The dev should have control on whether the item is loading or not, regardless of invoking or not. This opens possibilities for a variety of possible behaviors. Yet, this is the same behavior as any other loading widget (e.g `ProgressRing`, `ProgressBar`)
