### ISSUE TITLE
🐛 API reference to latest version missing on pub.dev

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#527]
Since pre-release 4 of 4.0.0, the API reference to the latest version is missing on pub.dev.

**To Reproduce**
1. Go to https://pub.dev/packages/fluent_ui or https://pub.dev/packages/fluent_ui/versions
2. Look for documentation for v3.12.0

**Screenshots**
![grafik](https://user-images.githubusercontent.com/103884835/189849222-b1fe0d41-9014-4943-a4eb-5afc2efd65fe.png)

**Comment by WinXaito** [comment]
I think that because `dartdoc` fail: https://pub.dev/packages/fluent_ui/score

**Comment by robkri** [comment]
Can I help with this somehow?

**Comment by WinXaito** [comment]
In fact, that work on 4.0.0-pre4  (current version in development), So, I think this more a problem with the analyse on pub.dev)

And I think we can just wait for the release of the version 4.0.0 ?

**Comment by robkri** [comment]
All seems fine again.
