### ISSUE TITLE
Error with upgrade from 2.0.3 to 2.2.1🐛 

### ISSUE THREAD

**Issue by detroxx92** [bdlukaa/fluent_ui#53]
**Describe the bug**
After updating the package from 2.0.3 to 2.2.1 i get the following error message:

════════ Exception caught by rendering library ═════════════════════════════════
Expected a value of type 'SkDeletable', but got one of type 'Null'
The relevant error-causing widget was
NavigationView
lib\app.dart:41

Exception caught by acrylic.dart._generateImageTileRects -> (something with the assignment of colorFilter to paint.colorFilter.
colorFilter is not in the correct internal state.

**To Reproduce**
I do not have the acrylic or system_theme packages.

**Comment by bdlukaa** [comment]
Did you set `useAcrylic` to `false`?

**Comment by detroxx92** [comment]
I searched where i could set it.

But the only place i found was in NavigationView. With the release of 2.2.0 the property cannot be set anymore.

The error occures, when the displayMode of NavigationView changes from compact to open.

**Comment by bdlukaa** [comment]
This may be due to the Acrylic rework (https://github.com/bdlukaa/fluent_ui/pull/47). Can you post your `flutter doctor` and the full log please?

**Comment by detroxx92** [comment]
Sure can i :)

flutter doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1052], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.5)
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.57.1)
[√] Connected device (3 available)

• No issues found!

=====================================================

Log:

Launching lib\main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:58637/IJctiNEGjwg%3D/ws
Debug service listening on ws://127.0.0.1:58637/IJctiNEGjwg=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:58637/IJctiNEGjwg=/ws

════════ Exception caught by rendering library ═════════════════════════════════
The following TypeErrorImpl was thrown during paint():
Expected a value of type 'SkDeletable', but got one of type 'Null'

The relevant error-causing widget was
NavigationView
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3    castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 266:34   as
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 146:55    new
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/color_filter.dart 16:3           new
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#82357 relayoutBoundary=up5
RenderObject: RenderCustomPaint#82357 relayoutBoundary=up5
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=1329.0, 0.0<=h<=932.0)
    size: Size(40.0, 932.0)
    child: RenderCustomPaint#feddd relayoutBoundary=up6 NEEDS-PAINT
        needs compositing
        parentData: <none> (can use size)
        constraints: BoxConstraints(0.0<=w<=1329.0, 0.0<=h<=932.0)
        size: Size(40.0, 932.0)
        child: _RenderInkFeatures#4bec5 relayoutBoundary=up7 NEEDS-PAINT
            needs compositing
            parentData: <none> (can use size)
            constraints: BoxConstraints(0.0<=w<=1329.0, 0.0<=h<=932.0)
            size: Size(40.0, 932.0)
            child: RenderConstrainedBox#8e198 relayoutBoundary=up8 NEEDS-PAINT
                needs compositing
                parentData: <none> (can use size)
                constraints: BoxConstraints(0.0<=w<=1329.0, 0.0<=h<=932.0)
                size: Size(40.0, 932.0)
                additionalConstraints: BoxConstraints(w=40.0, 0.0<=h<=Infinity)
                child: RenderCustomPaint#65b10 relayoutBoundary=up9 NEEDS-PAINT
                    needs compositing
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=40.0, 0.0<=h<=932.0)
                    size: Size(40.0, 932.0)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Expected a value of type 'SkDeletable', but got one of type 'Null'
The relevant error-causing widget was
NavigationView
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Expected a value of type 'SkDeletable', but got one of type 'Null'
The relevant error-causing widget was
NavigationView
════════════════════════════════════════════════════════════════════════════════
...(repeating error)

**Comment by bdlukaa** [comment]
I am also getting this error when runnin on the web. On Windows works fine

**Comment by parikh20** [comment]
Any update on this issue?

**Comment by bdlukaa** [comment]
Not really. This is an issue with the web renderer

**Comment by bdlukaa** [comment]
This issue is now fixed on version 3.0.0. https://pub.dev/packages/fluent_ui/changelog
