### ISSUE TITLE
does its code also support macos?

### ISSUE THREAD

**Issue by lucasjinreal** [bdlukaa/fluent_ui#534]
does its code also support macos?

**Comment by bdlukaa** [comment]
yes

**Comment by quasivivo** [comment]
Is this still accurate for flutter stable channel? On macos (Ventura 13.5), the example app launches, but resizing the window or performing any action beachballs it, requiring force close. 

Works & looks great on windows.

**Comment by bdlukaa** [comment]
> Update: It was crashing on the list of image urls within sponsor.dart. Commenting those out fixed the macos issue for me. Perhaps something to do with CSP on macos, but I didn't dig any deeper.

Could you file a PR for the fix? I don't have access to a macOS, so I'd appreciate it a lot
