### ISSUE TITLE
High gpu usage when TextBox or AutoSuggestBox is focused🐛 

### ISSUE THREAD

**Issue by Chiggy-Playz** [bdlukaa/fluent_ui#536]
**Describe the bug**
High gpu usage when TextBox or AutoSuggestBox is focused. 

**To Reproduce**
1. Click or focus on a textbox

**Expected behavior**
The gpu usage should not skyrocket

**Screenshots**
The below screenshots were taken in release mode
When the textbox is not focused:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/49774426/190875953-314d0b76-5247-43a9-8972-0750a4719521.png">
When it is focused:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/49774426/190875983-a72a6f6e-feb9-4a7f-8e2f-a186cc774b9b.png">

**Additional context**
It happens on the demo site too, https://bdlukaa.github.io/fluent_ui/
My gpu is integrated, and my cpu is i7-5600U but it still shouldn't use this much gpu.

**Comment by bdlukaa** [comment]
Does the same happen when using material's `TextField` or cupertino's `CupertinoTextField`?

**Comment by Chiggy-Playz** [comment]
Following usage is for release mode builds. 
This is when using fluent. You can clearly see the spike.
![image](https://user-images.githubusercontent.com/49774426/209432388-1105b624-d718-495c-8ea4-517bf31f1e71.png)

This is when using material's TextFormField. I've highlighted when I focused it and when I focused out.
![image](https://user-images.githubusercontent.com/49774426/209432489-faf439b7-58ae-4117-9bab-85436e2cde7d.png)
