### ISSUE TITLE
AutoSuggestBox==>No results found

### ISSUE THREAD

**Issue by LinHaoLove** [bdlukaa/fluent_ui#542]
Hi,Sir
I wanted to use the AutoSuggestBox as an input history.
1. So can we not show "No Results found" in the future? Or custom styles?
2. Why does the AutoSuggestBox have no inputFormatters?InputFormatters are in great need. If I choose to use Validator, I can't undo the wrong action after "return "balabala"", and the experience doesn't seem friendly

**Comment by LinHaoLove** [comment]
The TextBox, TextFormBox, and AutoSuggestBox are merged into a textField.

**Comment by bdlukaa** [comment]
> 
The TextBox, TextFormBox, and AutoSuggestBox are merged into a textField.

What do you mean?

**Comment by LinHaoLove** [comment]
Actually, I'm not very good at English.
These are just some of my thoughts. I hope these ideas are useful.

"AutoSuggestBox" already contains both "TextBox" and "TextFormBox".
So  The "AutoSuggestBox" is more than enough. Both "TextBox" and "TextFormBox" can be private.
But "AutoSuggestBox" doesn't provide enough attributes, but "TextBox" and "TextFormBox" do.

I had to copy it to add these properties.
Such as these：

`  final List<TextInputFormatter>? inputFormatters;
  final bool obscureText;
  final TextSelectionControls? selectionControls;
  final ToolbarOptions? toolbarOptions;
  final TextInputType? keyboardType;
`
So provide more attributes for user customization.
And I not find where I can change the shading under the underline of "AutoSuggestBox".

If merged into a single widget.Overlay can be controlled by items.
"items==null" means no overlay.The associated code is not called. Is equivalent to "TextBox" or "TextFormBox".





> > 
> 
> The TextBox, TextFormBox, and AutoSuggestBox are merged into a textField.
> 
> What do you mean?

**Comment by bdlukaa** [comment]
>  If I choose to use Validator, I can't undo the wrong action after "return "balabala"", and the experience doesn't seem friendly

You can use a text controller
