### ISSUE TITLE
4.0.1 at ios🐛 

### ISSUE THREAD

**Issue by longfit** [bdlukaa/fluent_ui#549]
since I try to run fluent_ui 4.0.1 example  at ios but

 throw MissingPluginException('No implementation found for method $method on channel $name');

But I can run example when I ignore this
Is Windows_manager Caused max /min windows ?

How to fix my project run at ios , android, windows ?

thanks

**Comment by bdlukaa** [comment]
Can you post the whole error message?

**Comment by longfit** [comment]
Linux and windows work properly
and 
I switch android , ios at  method = isMaximized, arguments =null


@optionalTypeArgs
  Future<T?> _invokeMethod<T>(String method, { required bool missingOk, dynamic arguments }) async {
    assert(method != null);
    final ByteData input = codec.encodeMethodCall(MethodCall(method, arguments));
    final ByteData? result =
      !kReleaseMode && debugProfilePlatformChannels ?
        await (binaryMessenger as _ProfiledBinaryMessenger).sendWithPostfix(name, '#$method', input) :
        await binaryMessenger.send(name, input);
    if (result == null) {
      if (missingOk) {
        return null;
      }
      throw MissingPluginException('No implementation found for method $method on channel $name');
    }
    return codec.decodeEnvelope(result) as T?;
  }
![Screenshot from 2022-10-02 08-40-21](https://user-images.githubusercontent.com/4157794/193433229-5c040e6a-2ba8-4d64-bd02-3ee8a90f467c.png)
