### ISSUE TITLE
Navigation : How to navigate when clicking on a widget

### ISSUE THREAD

**Issue by catapult0** [bdlukaa/fluent_ui#554]
Hi @bdlukaa,

I'd like to trigger a change of page from clicking on a widget instead of using the panel.

Is there a way to do that ?

Best.

**Comment by klondikedragon** [comment]
One possible method is to use a Navigator such as vRouter as shown in https://github.com/bdlukaa/fluent_ui/issues/226#issuecomment-1070267070. With a navigator-driven approach, you can get the navigator singleton from a GlobalKey, and then use the navigator to programmatically change the route from anywhere (from a widget that is pressed, or from some other action, etc.).

Flutter is amazingly flexible, so I'm sure there are lots of other ways to do this.

Note that for this specific approach to work in fluent_ui >= 4.0.x you'd need #553 to be merged first and to make use of the new `paneBodyBuilder` as shown in the new example in the PR description.

**Comment by klondikedragon** [comment]
With #553 merged, the example in #226 has been updated, which shows how to use a navigator with routes, which you could then programmatically change from anywhere.
