### ISSUE TITLE
The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem'.🐛 

### ISSUE THREAD

**Issue by umutocak** [bdlukaa/fluent_ui#561]
Because of this error, the project does not work. Needs urgent regulation.

error: The method 'VoidCallbackIntent' isn't defined for the class '_TreeViewItem'.

**Comment by bdlukaa** [comment]
Can you post the logs of `flutter doctor -v` here?

**Comment by umutocak** [comment]
Flutter 3.0.5 is installed, do I need to use the latest version for this error to go away?

**Comment by umutocak** [comment]
The situation got better after I updated the Flutter version to the latest.

**Comment by sunnykarira-ms** [comment]
@umutocak  What is your version now. I am seeing this issue in latest flutter version as well on linux platform.

**Comment by umutocak** [comment]
@sunnykarira-ms  my flutter version 3.3.3
