### ISSUE TITLE
🐛 Error on Scrolling widgets inside Navigation

### ISSUE THREAD

**Issue by bobobekturdiyev** [bdlukaa/fluent_ui#565]
I have used GridView.builder in one of the navigation pane content. When I scroll the items on this page, following error is occuring:
How to solve it?

Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 3012 pos 12: '!debugNeedsLayout': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)

**Comment by bdlukaa** [comment]
Can you post a code snippet?

**Comment by bobobekturdiyev** [comment]
` NavigationView(
      key: key,
      appBar: NavigationAppBar(
        automaticallyImplyLeading: false,
        title: const AppTitle(),
        actions: AppActions(),
      ),
      pane: NavigationPane(
        selected: index,
        header: Container(
            padding: EdgeInsets.zero,
            height: 50,
            child: SingleChildScrollView(
                physics: NeverScrollableScrollPhysics(), child: Header())),
        onChanged: (i) => setState(() => index = i),
        displayMode: PaneDisplayMode.compact,
        footerItems: Footer.items,
        items: SideBar.items,
      ),
    );
`
Page called from items content:

`
ScaffoldPage(
      header: PageHeader(
        title: Text("Page"),
      ),
      content: GridView.builder(
        addAutomaticKeepAlives: true,
        primary: true,
        padding: EdgeInsets.only(left: 24, right: 24, bottom: 20),
        itemCount: 5,
        shrinkWrap: true,
        gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
          maxCrossAxisExtent: 270,
          mainAxisExtent: 240,
          mainAxisSpacing: 20,
          crossAxisSpacing: 15,
        ),
        itemBuilder: (ctx, index) => const WCourseCard(),
      ),
    );
`

Let me know if you need any class code which is strange for you. I will share it

**Comment by bdlukaa** [comment]
Sorry, I can't reproduce this issue :/

The Icons page in the example app makes use of a `GridView` widget. You can check it there https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/screens/theming/icons.dart#L84
