### ISSUE TITLE
fluent_ui 4.0.1 at fluent master🐛 

### ISSUE THREAD

**Issue by longfit** [bdlukaa/fluent_ui#568]
Since I need run fluent 4.0.1 at flutter master version

but error shown

lib/main_menu.dart:1
: Error: The method '_CustomTrackShape.paint' has fewer named arguments than those of overridden method 'RoundedRectSliderTrackShape.paint'.
../…/inputs/slider.dart:363
  void paint(
       ^
: Context: This is the overridden method ('paint').
../…/material/slider_theme.dart:1682
  void paint(

best Regards

**Comment by bdlukaa** [comment]
Looks like the Flutter Framework has some breaking changes in the master channel. Unfortunately, we need to follow its stable channel

**Comment by Gorter-dev** [comment]
I created a fork wich support flutter at master channel. For now you can use this one: 

https://github.com/Gorter-dev/fluent_ui/tree/hotfix/flutter_master
