### ISSUE TITLE
🐛 ScaffoldPage.scrollable work inproper

### ISSUE THREAD

**Issue by longfit** [bdlukaa/fluent_ui#571]
HI
I have created a long Data table by TABLE WIDGET and deployed to android.
Work inproper scrolling . 
1) wrap singlechildscrollview with table widget ,
   it can be scrolling but Need tap the right-hand side scroll bar
   up and down.
2) without singlechildscrollview.
    It cannot be a scrolling table.

below attached code work at material properly

inproper scrolling or no scrolling

class MunitPage extends StatefulWidget {.....
....
.....

return ScaffoldPage.scrollable(
      header: const PageHeader(
        title: Text('藥品單位'),
      ),
      children: [
        Consumer<MunitViewModel>(
            builder: (context, MunitViewModel? model, child) {
          // return (model.mUnitListModel != null)

          return (model != null && model.mUnitListModel != null)
              ? SingleChildScrollView(
                  child: Column(
                  children: <Widget>[
                    controls,
                    _buildTable(model.mUnitListModel!.list)
                  ],
                ))
              : const Center(child: Text(KString.loading));
        })
      ],
    );
  }

**Comment by bdlukaa** [comment]
Try adding `shrinkWrap: true` to `SingleChildScrollView`

**Comment by longfit** [comment]
Hi
No matter using ListView with shrinkwrap =true or without ListView instead singlechilScrollview
it can be scrolling but Need tap the right-hand side or left hand side scroll bar
up and down.

========================================

  return ScaffoldPage(
        header: const Text(KString.appTitle),
        content: Stack(children: <Widget>[
          Center(
            child: SizedBox(
              width: width,
              child: ListView(
                shrinkWrap: true,
                padding: const EdgeInsets.only(left: 24.0, right: 24.0),
                children: <Widget>[
                  logo,
                  const SizedBox(height: 15.0),
                  title,
                  const SizedBox(height: 48.0),

                  email,
                  const SizedBox(height: 10.0),
                  password,
                  const SizedBox(height: 24.0),
                  loginButton,
                  // forgotLabel
                ],
              ),
            ),
          )
        ]));
  }

**Comment by bdlukaa** [comment]
try wrapping your `Center` widget in a `Positioned.fill`

**Comment by longfit** [comment]
I have tried the below code to work proper ios iPhone  and  Not scrollable on android

I am not sure which is  bug  ?


 return ScaffoldPage.scrollable(
      header: const PageHeader(
        title: Text('Test'),
      ),
      children: [
      
         Table( columnWidths: const {
                      0: FlexColumnWidth(1.0),
                      1: FlexColumnWidth(2),
                      2: FlexColumnWidth(2)
                    },
                    children: const [TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),
                    TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),TableRow(
                      children:[Text('c1'),Text('c2'),Text('c3'),]
                      

                    ),
                    ],
         
    ),
       ]

**Comment by bdlukaa** [comment]
Sorry, but I can't reproduce this issue. The code snippet you provided works:

![image](https://user-images.githubusercontent.com/45696119/197341812-d1624685-9a06-4ef2-9b53-21b88fbfdbf9.png)

**Comment by longfit** [comment]
Noted with many Thank
where Can I buy a coffee?

When Remove Listview widget wrap Table() , which can be working properly.

ListView wraps the Table widget, causing the need to tap right or left side for scrollable movement
