### ISSUE TITLE
Does fluent_ui have RefreshIndicator?

### ISSUE THREAD

**Issue by ghost** [bdlukaa/fluent_ui#573]
I want to use the drop-down refresh function of flutter's RefreshIndicator, but I can't find a similar widget. If there is a corresponding widget, please tell me, thank you!

**Comment by bdlukaa** [comment]
Hello! This behavior is not stated in the Windows UI docs. Even Material's `RefreshIndicator` doesn't work with the mouse in desktop.

The common behavior in desktop is to have a refresh button (you can use `FluentIcons.refresh` for that).

Closing as not planned
