### ISSUE TITLE
🐛 change fontFamily seems dosn‘t work

### ISSUE THREAD

**Issue by huangye0** [bdlukaa/fluent_ui#576]
**Describe the bug**
use the custom fontFamily doesnot work at all
![image](https://user-images.githubusercontent.com/48897708/196580438-4fd2935b-bfe6-4543-8d2b-fa62f415a114.png)
![lALPJvDqWt0zvLbNAbzNBdw_1500_444](https://user-images.githubusercontent.com/48897708/196580555-e7a7d05b-0b2a-4323-9f3a-60bb8e8e950f.png)
![image](https://user-images.githubusercontent.com/48897708/196580933-d70b5c8a-2673-40a1-a2b2-8a11bfcb0a19.png)

if i use materialApp ,the same change can work
![image](https://user-images.githubusercontent.com/48897708/196581248-306e30af-8a31-4514-8952-e4b028b4675b.png)
![Uploading image.png…]()

**Comment by huangye0** [comment]
materialApp:
![image](https://user-images.githubusercontent.com/48897708/196583612-f2f652e4-345b-44ed-bfc3-8c41ff88351c.png)

**Comment by bdlukaa** [comment]
Sorry, but I can't reproduce this issue :/

`fontFamily: 'Arial',`:
![example 22_10_2022 10_45_54](https://user-images.githubusercontent.com/45696119/197342531-2bb42529-cec8-4cb0-b819-3ae3be320ed5.png)

`fontFamily: 'Roboto',`
![🐛 change fontFamily seems dosn‘t work · Issue #576 · bdlukaa_fluent_ui e mais 3 páginas - Pessoa 2 — Microsoft​ Edge 22_10_2022 10_49_03](https://user-images.githubusercontent.com/45696119/197342666-a8cc5dbd-dafb-4403-af43-4b1e4d8b3719.png)
