### ISSUE TITLE
TreeView initial value on selected.

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#578]
Is there a way that the parent will has an initial value also that depends on the children?

<img width="760" alt="Screen Shot 2022-10-20 at 7 52 58 PM" src="https://user-images.githubusercontent.com/40779451/196941926-97cbe1db-7e90-4ab3-b1b5-40066a071177.png">

**Comment by adpmhel24** [comment]
It should be like this.

![Screen Shot 2022-10-21 at 8 30 27 AM](https://user-images.githubusercontent.com/40779451/197084275-94dcf53c-bfdf-4cc2-bfba-3049ba5bb543.png)

**Comment by bdlukaa** [comment]
May be related to #556.

**Comment by adpmhel24** [comment]
> May be related to #556.

there's an initial value some of the children in my treeview. How we can update the parents if some of the children has an initial value of true?

**Comment by klondikedragon** [comment]
@adpmhel24 - the `TreeView` should already be updating the parent items selection state when the state of the `TreeView` widget is initially built, as long as you are using the selection mode of `TreeViewSelectionMode.multiple` -- `initState` will call `buildItems` that will update the selection state of all parent items based on the selection state of their children. Are you changing `selectionMode` property at all?  If you step through in the debugger, is `initState` in the `TreeView` calling `buildItems` and hitting the first branch (`items.executeForAll` is calling `executeForAllParents` on each item in the built tree)?

If you're manipulating the state of items after the state of the widget is built (maybe the widget state is built first and then item states are modified?) are you using `TreeViewItem.setSelectionStateForMultiSelectionMode` to update the item's selection state? (this can ensure that any modifications to the tree update the selection state of the parents, etc.)

**Comment by adpmhel24** [comment]
> @adpmhel24 - the `TreeView` should already be updating the parent items selection state when the state of the `TreeView` widget is initially built, as long as you are using the selection mode of `TreeViewSelectionMode.multiple` -- `initState` will call `buildItems` that will update the selection state of all parent items based on the selection state of their children. Are you changing `selectionMode` property at all? If you step through in the debugger, is `initState` in the `TreeView` calling `buildItems` and hitting the first branch (`items.executeForAll` is calling `executeForAllParents` on each item in the built tree)?
> 
> If you're manipulating the state of items after the state of the widget is built (maybe the widget state is built first and then item states are modified?) are you using `TreeViewItem.setSelectionStateForMultiSelectionMode` to update the item's selection state? (this can ensure that any modifications to the tree update the selection state of the parents, etc.)

My problem was if the children were coming from onExpandToggle.

**Comment by adpmhel24** [comment]
![Screen Shot 2022-11-03 at 9 06 37 AM](https://user-images.githubusercontent.com/40779451/199629948-8ea57808-f735-4a5f-bafb-6978b0d4b09e.png)
![Screen Shot 2022-11-03 at 9 06 52 AM](https://user-images.githubusercontent.com/40779451/199629983-2f102e9d-6fac-46b8-b90d-3926d34de2b1.png)

**Comment by klondikedragon** [comment]
@adpmhel24 - It looks like the `build` that is called to build the visible items to render during the initial state of the control would initially exclude non-expanded items (by design). then, as you point out, if later an item was expanded (e.g., mouse click), currently there is the following code in the bottom of the `build` method in the `_TreeViewState` class:
```dart
                  // Remove the loading indicator.
                  // Toggle the expand icon.
                  setState(() {
                    item.loading = false;
                    item.expanded = !item.expanded;
                    items = widget.items.build();
                  });
```

This really should be something more like:
```dart
                  // Remove the loading indicator.
                  // Toggle the expand icon.
                  setState(() {
                    item.loading = false;
                    item.expanded = !item.expanded;
                    buildItems();
                  });
```

This should fix it. Does it work?

**Comment by adpmhel24** [comment]
> ```dart
> setState(() {
>                     item.loading = false;
>                     item.expanded = !item.expanded;
>                     buildItems();
>                   });
> ```

the problem was if I toggle it off, it deselected the parent.

**Comment by klondikedragon** [comment]
Not sure I follow. Did that change fix the tree selection state when an item is expanded/unexpanded?

You're saying now that when you deselect a child item you want the parent to remain selected? If you don't want that behavior to happen, are you setting `deselectParentWhenChildrenDeselected` to false?

**Comment by adpmhel24** [comment]
> Not sure I follow. Did that change fix the tree selection state when an item is expanded/unexpanded?
> 
> You're saying now that when you deselect a child item you want the parent to remain selected? If you don't want that behavior to happen, are you setting `deselectParentWhenChildrenDeselected` to false?

The parent was deselected when it toggled off even though the children was selected.
This will happen when I've modify this line of code.
```
setState(() {
                    item.loading = false;
                    item.expanded = !item.expanded;
                    buildItems();
                  });
```

https://user-images.githubusercontent.com/40779451/199666799-a23fed8b-6073-42ed-8fdb-9f3d98eca7b0.mov

**Comment by klondikedragon** [comment]
@adpmhel24 - thanks for the video, very helpful! I've opened #597 that I've tested should fix the problem, both for the initial selection state if something is unexpanded, as well as making sure the selection state remains consistent when an item is unexpanded/expanded.
