### ISSUE TITLE
Window button visual effect as default

### ISSUE THREAD

**Issue by definev** [bdlukaa/fluent_ui#58]
Can you implement window button visual effect. 
Glopos has that effect, can you implement something like that in fluent_ui packages.
Glopos pub.dev: https://pub.dev/packages/glopos

**Comment by bdlukaa** [comment]
This effect was removed in the latest version of win-ui, and was even removed from the docs.

**Comment by definev** [comment]
Oh, i don't know that. However, i think it pretty cool 😁
