### ISSUE TITLE
🐛 A RenderFlex overflowed when a footItem has infoBadge in NavigationPane

### ISSUE THREAD

**Issue by dongdaming1966** [bdlukaa/fluent_ui#589]
**Describe the bug**
When I set a footItem  infoBadge in NavigationPane, overflowed occured.
A RenderFlex overflowed by 14 pixels on the right.

**To Reproduce**
1.
 footerItems: [
    PaneItemAction(
      icon: const Icon(FluentIcons.plug_connected),
      title: const Text('COM Port'),
      infoBadge: const InfoBadge(
        color: Colors.errorPrimaryColor,
      ),
      onTap: () => showConfigCOM(context),
    ),
2.expand NavigationPane

**Screenshots**

<img width="380" alt="image" src="https://user-images.githubusercontent.com/13404168/197334222-e5984cf0-fff4-4401-aa67-0dafca77b6b0.png">

**Comment by bdlukaa** [comment]
Seems it's the same issue as #588.

Closing as duplicate
