### ISSUE TITLE
🐛 Incompatibility with pluto_grid +5.0.4

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#590]
**Describe the bug**
I've posted a regression for pluto_grid ( https://github.com/bosskmk/pluto_grid/issues/613 ). I suspect this is related in some manner with `fluent_ui`, too, because:

FUI: `4.0.0-pre4` + pluto_grid: `latest` ✅
FUI: `+4.0.0` + pluto_grid: `5.0.3` ✅
FUI: `+4.0.0` + pluto_grid: `+5.0.4` 🐛❌

**To Reproduce**
See details in https://github.com/bosskmk/pluto_grid/issues/613

**Expected behavior**
See details in https://github.com/bosskmk/pluto_grid/issues/613

**Screenshots**
n/a

**Additional context**
n/a

**Comment by bdlukaa** [comment]
We don't make use of `pluto_grid`. Closing as invalid
