### ISSUE TITLE
Add `animating` to play/pause animation for `ProgressRing` like in `CupertinoActivityIndicator`

### ISSUE THREAD

**Issue by damywise** [bdlukaa/fluent_ui#594]
**Is your feature request related to a problem? Please describe.**
A nice-to-have, like for indicating that a process is intentionally halted.

**Describe the solution you'd like**
```dart
ProgressRing(
  //...
  animating: false,
)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by bdlukaa** [comment]
The Win UI guidelines don't provide a guidance for a stopped indeterminate progress indicator.  [Learn more](https://learn.microsoft.com/en-us/windows/apps/design/controls/progress-controls)

Would setting `value: 0` do it for your case?

**Comment by damywise** [comment]
Not what I want, but I guess I'll try another way
