### ISSUE TITLE
🐛 Opening one expander opens all of them (intended?)

### ISSUE THREAD

**Issue by bmceachnie** [bdlukaa/fluent_ui#596]
**Describe the bug**
Opening a single expander widget opens every other expander when changing route. Is this intended?

**To Reproduce**
1. Go to the [fluent_ui example page](https://bdlukaa.github.io/fluent_ui/)
2. Open any expander
3. Change the route via sidebar
4. Watch all expanders open

**Expected behavior**
Expanders stay closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/60017181/200066673-7638fbe1-2697-4407-95dc-30d424c466ab.png)
![image](https://user-images.githubusercontent.com/60017181/200066712-4192e707-608f-424c-adeb-2adf3c958d6e.png)
![image](https://user-images.githubusercontent.com/60017181/200066751-c01ade71-5e90-4e36-8a9f-a692b36d55da.png)

**Additional context**
The identifier for page storage seems to be at fault (if this is not intended) at `fluent_ui/lib/src/controls/surfaces/expander.dart:180` 

```dart
PageStorage.of(context)?.writeState(
  context,
  open,
  identifier: 'expanderOpen', // Not unique to the specific expander widget
);
```
and `fluent_ui/lib/src/controls/surfaces/expander.dart:143`

```dart
_open = PageStorage.of(context)?.readState(
          context,
          identifier: 'expanderOpen', // Not unique to the specific expander widget
        ) as bool? ??
        widget.initiallyExpanded;
```

**Comment by bmceachnie** [comment]
An option would be to use the key as identifier and don't store open state if none is provided.

Or do you want to store open state regardless of the key?

**Comment by ricard-v** [comment]
I can confirm this issue and I have arrived at the same conclusion. Is there a way to solve that while waiting a fix ?

**Comment by bmceachnie** [comment]
I forked the repo, removed the page storage stuff, and used `dependency_overrides` section in `pubspec.yaml`.

As I've already done it you can go ahead and use my fork:

```yaml
dependency_overrides:
  fluent_ui:
    git:
      url: https://github.com/bmceachnie/fluent_ui.git
```

**Comment by ricard-v** [comment]
> I forked the repo, removed the page storage stuff, and used `dependency_overrides` section in `pubspec.yaml`.
> 
> As I've already done it, you can go ahead and use my fork:
> 
> ```yaml
> dependency_overrides:
>   fluent_ui:
>     git:
>       url: https://github.com/bmceachnie/fluent_ui.git
> ```

Thanks for providing a fork and a way to use it (I did not know how to) 👍 .

I took a quick look at your code and as you said, you did remove the code related to writing & reading the open state. That being said, I was wondering if there is still a way to use keys (something I am not knowledgeable about) or if `PageStorage` could still be used? Or perhaps both?

**Comment by bmceachnie** [comment]
To my understanding, it'd be possible to use the key as an identifier instead of the hardcoded string `expanderOpen`.

If you need it, I could implement it.
