### ISSUE TITLE
How can i use PaneItemExpander on left side navigation pane. Any example use case for that??

### ISSUE THREAD

**Issue by faisalmushtaq007** [bdlukaa/fluent_ui#599]
i am working on the left side navigation pane. Now since item are many, so i want to group different PaneItems in different expanders. i've added an example for you to check. Please respond.
Thankyou
<img width="1080" alt="Screenshot 2022-11-05 at 4 27 36 PM" src="https://user-images.githubusercontent.com/24683159/200116577-86ca46bf-3007-4c2e-b59b-6e4937c2db8b.png">

**Comment by bdlukaa** [comment]
You can check the live example on https://bdlukaa.github.io/fluent_ui/, under the `NavigationView` tab

https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/screens/navigation/navigation_view.dart#L134-L162

**Comment by faisalmushtaq007** [comment]
I already check it, but i am getting an issue here and that is when i use PaneItemExpander it has items parameter that takes list of PaneItem and that works fine and  another parameter of Expander is body. Why does expander have body. Whenever i tap on Expander, it should only expand and show the list of items. How to implement that??

**Comment by bdlukaa** [comment]
Natively, `PaneItemExpander` also has a body and can be selected.

Official resource: https://learn.microsoft.com/en-us/windows/apps/design/controls/navigationview#hierarchical-navigation
![image](https://user-images.githubusercontent.com/45696119/200131677-cd7a9ae4-8dc3-4b9a-abab-f22ec2ac9e2b.png)

You can create a custom `PaneItem` with a specific behavior by extending `PaneItem`: https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart#L569-L602

**Comment by faisalmushtaq007** [comment]
@bdlukaa  Thankyou, will check out custom PaneItem

**Comment by bdlukaa** [comment]
Can this be closed?

**Comment by faisalmushtaq007** [comment]
sure

**Comment by pasleto** [comment]
@faisalmushtaq007 Did you find solution for this?

**Comment by pasleto** [comment]
If anyone looking for solution:

```
class _NoBodyPaneItemExpander extends PaneItemExpander {
  _NoBodyPaneItemExpander({
    required super.icon,
    required super.body,
    required super.items,
    super.title,
  });

  @override
  Widget build(
    BuildContext context,
    bool selected,
    VoidCallback? onPressed, {
    PaneDisplayMode? displayMode,
    bool showTextOnTop = true,
    ValueChanged<PaneItem>? onItemPressed,
    bool? autofocus,
    int? itemIndex,
  }) {
    return Builder(
      builder: (context) => super.build(
        context,
        selected,
        () {},
        displayMode: displayMode,
        showTextOnTop: showTextOnTop,
        onItemPressed: onItemPressed,
        autofocus: autofocus,
        itemIndex: itemIndex,
      ),
    );
  }
}
```

Usage:

```
_NoBodyPaneItemExpander(
  icon: ...,
  title: ...,
  body: const SizedBox.shrink(),
  items: [...],
)
```

Only catch is error when using compact displayMode inside _StickyNavigationIndicatorState when navigating from one item to another within  one expander menu -> indicator stay on same item in navigationPane
-> exception was thrown: setState() called after dispose(): _StickyNavigationIndicatorState#8bba6(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
```
The following assertion was thrown during a scheduler callback:
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
```

@bdlukaa Can this error be handled by us somehow, or should be handled somewhere inside library?
