### ISSUE TITLE
Enable click on `DatePicker` and `TimePicker`

### ISSUE THREAD

**Issue by bdlukaa** [bdlukaa/fluent_ui#6]
Currently there's no click on these widgets because it's blocked by https://github.com/flutter/flutter/issues/38803

**Comment by klondikedragon** [comment]
It could be worth considering using https://pub.dev/packages/clickable_list_wheel_view to implement this.

**Comment by bdlukaa** [comment]
@klondikedragon unfortunately it doesn't work well in infinite scroll views like the ones we use in the pickers
