### ISSUE TITLE
Do not call dispose() on tab page change

### ISSUE THREAD

**Issue by CesareIsHere** [bdlukaa/fluent_ui#603]
Hi,
i noted that on tab changed, the widget tree remove previous opened tab.
It is possible to avoid this and maintain the widgets in the tree? I need it to maintain state between pages.
Let me know if i can do something, thank you!

**Comment by CesareIsHere** [comment]
Enhancement explained better here https://github.com/bdlukaa/fluent_ui/issues/604

**Comment by ReggieMiller1** [comment]
> Enhancement explained better here #604



> Hi, i noted that on tab changed, the widget tree remove previous opened tab. It is possible to avoid this and maintain the widgets in the tree? I need it to maintain state between pages. Let me know if i can do something, thank you!

i removed the disposed function but still i see no changes...please elaborate since i'm still a bit lost or maybe share the code so i can see what you mean....i called the dispose function because i wanted to be sure that the page was really getting disposed.

**Comment by ReggieMiller1** [comment]
> Hi, i noted that on tab changed, the widget tree remove previous opened tab. It is possible to avoid this and maintain the widgets in the tree? I need it to maintain state between pages. Let me know if i can do something, thank you!

and you were right... when the tab is changed the previous item gets removed from the widget tree but the problem seems to be within the package under PaneItem.
