### ISSUE TITLE
AutomaticKeepAliveClientMixin

### ISSUE THREAD

**Issue by ReggieMiller1** [bdlukaa/fluent_ui#604]
AutomaticKeepAliveClientMixin doesn't seem to work...its not preserving the application state at all.

**Comment by bdlukaa** [comment]
Could you provide more details?

**Comment by ReggieMiller1** [comment]
> Could you provide more details?

since you know that AutomaticKeepAliveClientMixin is used to keep a widget alive in other words to preserve its state. i have page that returns a form but when i switch to another page, the previous page gets disposed even when i used AutomaticKeepAliveClientMixin...it doesnt have to be like that. i hope you understand now.

**Comment by ReggieMiller1** [comment]
https://user-images.githubusercontent.com/52163493/200689079-924dd280-e8a2-49aa-8377-f8b4f6f73359.mp4

**Comment by muizidn** [comment]
This issue has been closed. But I still don't understand how the problem solved with #607. 

Meanwhile I implement state preservation in TabView using IndexedStack here https://github.com/muizidn/fluent_ui/commit/6c88b2a126ef945da5b2793d4111562c71b25a36

And to simulate it, I changed example app TabView body to use ListView to check whether each tab scroll location is different
https://github.com/muizidn/fluent_ui/commit/bc3412815cd8166bba643b86b010a344780b6e9b

**Comment by ReggieMiller1** [comment]
> This issue has been closed. But I still don't understand how the problem solved with #607 for TabView
> 
> Meanwhile I implement state preservation in TabView using IndexedStack here [muizidn@99f7f0c](https://github.com/muizidn/fluent_ui/commit/99f7f0cd66263fd8119a5218a87fa1793b8d66cb)
> 
> And to simulate it, I changed example app TabView body to use ListView to check whether each tab scroll location is different [muizidn@1a395ba](https://github.com/muizidn/fluent_ui/commit/1a395ba847a6e7c0401f041f2c7165a7f4818b27)

you right bro

**Comment by bdlukaa** [comment]
> Meanwhile I implement state preservation in TabView using IndexedStack here

If I understood correctly, this issue was reporting issue with state preservation with `NavigationView`. For TabView, please file another issue

**Comment by b34st80y** [comment]
I am still having this issue with NavigationView. After upgrading I can no longer use IndexedStacked and NavigationPane together

#649

**Comment by bdlukaa** [comment]
@b34st80y hey! have you tried version 4.1.2?

**Comment by b34st80y** [comment]
> @b34st80y hey! have you tried version 4.1.2?

@bdlukaa  Yes sir! I am on 4.1.2. I have tried using AutomaticKeepAliveClientMixin as a replacement for IndexedStack as well but no luck. I have stateless widgets as PaneItem.body and the build method is still called when navigating both to and from the respective tab in the NavigationPane.
