### ISSUE TITLE
Old Windows 10 style UI

### ISSUE THREAD

**Issue by Soilcsi** [bdlukaa/fluent_ui#616]
Not quite sure how to describe this.
See this is the ui of windows 10:
![images (3)](https://user-images.githubusercontent.com/104806178/203159831-63ed7ae4-e001-4259-a991-37b21ce88974.jpeg)
And this is windows 11 or the current fluent ui design.
![images (4)](https://user-images.githubusercontent.com/104806178/203159911-ce8ba430-5475-4d01-9260-8ba89d16ce88.jpeg)
Is there any way to switch to the older windows 10 like style in this plugin?
Or define my custom style?
Thanks

**Comment by bdlukaa** [comment]
You can use the [2.0.0](https://github.com/bdlukaa/fluent_ui/tree/2.0.0) branch. But notice it hasn't been updated in a while, so there may be bugs and incorrect designs
