### ISSUE TITLE
Problems positioning a CommandBar

### ISSUE THREAD

**Issue by JostSchenck** [bdlukaa/fluent_ui#623]
I'm using a CommandBar in the header property of a ScaffoldPage, like in the code snippet below. However, the positioning of the CommandBar seems off:

![image](https://user-images.githubusercontent.com/12062873/203943059-52702a33-1665-4a2f-9cc9-93ae71f36c38.png)

Above the CommandBar seems to be too much space until the AppBar begins, and the first button "Add" seems to slightly overlap with the pane. Wrapping the CommandBar with a Padding to the left helps with the second problem -- but the slightly off positioning still leaves me with the feeling I might be using this the wrong way. 

Code snippet:

```
return ScaffoldPage(
      header: CommandBar(
          mainAxisAlignment: MainAxisAlignment.start,
          overflowBehavior: CommandBarOverflowBehavior.dynamicOverflow,
          compactBreakpointWidth: 768,
          primaryItems: [
            CommandBarButton(
              icon: const Icon(FluentIcons.add),
              label: const Text('Add'),
              onPressed: () {},
            ),
            CommandBarButton(
              icon: const Icon(FluentIcons.edit),
              label: const Text('Edit'),
              onPressed: () {},
            ),
            CommandBarButton(
              icon: const Icon(FluentIcons.delete),
              label: const Text('Delete'),
              onPressed: () {},
            ),
          ]),
      content: TreeView(
[...]
```

**Comment by bdlukaa** [comment]
`header` and `CommandBar` are usually used with the `PageHeader` widget.

> Above the CommandBar seems to be too much space until the AppBar begins

`ScaffoldPage` automatically applies `kPageDefaultVerticalPadding` to the top. To override it, provide the `padding` property

**Comment by JostSchenck** [comment]
Thanks a lot!
