### ISSUE TITLE
Snackbar manually dismiss error

### ISSUE THREAD

**Issue by thegioiso** [bdlukaa/fluent_ui#635]
This is not what i need here, because it will cause error if the snack has dismissed.
Example:
We call a snack bar and its will auto dissmiss after 5s.
Before 5s, we can manually dismiss by this method.
But, after 5s, if we call this method, an error will occur:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Assertion failed:
D:\…\widgets\overlay.dart:161
_overlay != null
is not true
When the exception was thrown, this was the stack:
``` 
So... Maybe i will need another way....

Thank you so much for your support.

_Originally posted by @thegioiso in https://github.com/bdlukaa/fluent_ui/discussions/630#discussioncomment-4282025_

**Comment by bdlukaa** [comment]
You can only call `result.remove()` if the snackbar is still being displayed, otherwise, an error will be thrown.
