### ISSUE TITLE
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019

### ISSUE THREAD

**Issue by wxpcl123** [bdlukaa/fluent_ui#639]
I just want to use NavigationView, so I copy a simple example to run it under **Windows(desktop)**.
But the error appears like below:

**flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �޷��������ⲿ���� __imp_FlutterDesktopEngineReloadPlatformBrightness������ "public: void __cdecl flutter::FlutterEngine::ReloadPlatformBrightness(void)" (?ReloadPlatformBrightness@FlutterEngine@flutter@@QEAAXXZ) �������˸÷��� [E:\study\flutter\demo05\build\windows\runner\demo05.vcxproj]
E:\study\flutter\demo05\build\windows\runner\Debug\demo05.exe : fatal error LNK1120: 1 ���޷��������ⲿ���� [E:\study\flutter\demo05\build\windows\runner\demo05.vcxproj]
Exception: Build process failed.
Exited (sigterm)**

**In fact the code can run in Chrome and Edge.**

I copy the code here hope someone can help find the problem.

code:
`import 'package:fluent_ui/fluent_ui.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const FluentApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int topIndex = 0;

  int badge = 8;

  Widget bodyItem() {
    return const Center(
      child: Text('This is content'),
    );
  }

  @override
  Widget build(BuildContext context) {
    return NavigationView(
      appBar: const NavigationAppBar(
        automaticallyImplyLeading: false,
        title: Text('Home', style: TextStyle(fontSize: 32)),
      ),
      pane: NavigationPane(
        selected: topIndex,
        onChanged: (index) => setState(() => topIndex = index),
        displayMode: PaneDisplayMode.open,
        items: [
          PaneItem(
            icon: const Icon(FluentIcons.home),
            title: const Text('Home'),
            body: bodyItem(),
          ),
          PaneItem(
            icon: const Icon(FluentIcons.issue_tracking),
            title: const Text('Track an order'),
            infoBadge: badge == 0 ? const SizedBox.shrink() : InfoBadge(source: Text('$badge')),
            onTap: () {
              setState(() {
                badge = 0;
              });
            },
            body: bodyItem(),
          ),
          PaneItemExpander(
            icon: const Icon(FluentIcons.account_management),
            title: const Text('Account'),
            body: bodyItem(),
            items: [
              PaneItem(
                icon: const Icon(FluentIcons.mail),
                title: const Text('Mail'),
                body: bodyItem(),
              ),
              PaneItem(
                icon: const Icon(FluentIcons.calendar),
                title: const Text('Calendar'),
                body: bodyItem(),
              ),
            ],
          ),
        ],
      ),
    );
  }
}`

**And the below is flutter doctor -v summaries:**
PS E:\study\flutter\demo05> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [版本 10.0.19044.2251], locale zh-CN)
    • Flutter version 3.3.6 on channel stable at E:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (6 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0) 
    • Android SDK at E:\SDK\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)    
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community   
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19044.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.94
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by bdlukaa** [comment]
Seems like it's related to https://github.com/flutter/flutter/issues/96287
