### ISSUE TITLE
Add border parameter for Card widget

### ISSUE THREAD

**Issue by thegioiso** [bdlukaa/fluent_ui#643]
After #641  and new release of version `4.1.1` this border still in my widget. So i look for it and found in Card widget:
![image](https://user-images.githubusercontent.com/106056252/206613087-1444170d-fd15-4cfd-bb87-21172b57c9bf.png)

I cant change it in Card and also in ThemeData:
![image](https://user-images.githubusercontent.com/106056252/206613175-abec89b9-d92a-41b1-ad7d-584f7d2211a8.png)
![image](https://user-images.githubusercontent.com/106056252/206613162-c8d17382-5f16-49ad-bd7a-4f079a22122b.png)

So i hope we can change this `border` in both Card and CommandBarCard. Thank you so much.

**Comment by bdlukaa** [comment]
You can change the color of the border by updating `ThemeData`'s `.resources`:

```dart
ThemeData(
  // use .light or .dark accordingly
  resources: ResourceDictionary.light(
    cardStrokeColorDefault: Color(0xFF753287),
  ),
),
```

**Comment by thegioiso** [comment]
@bdlukaa thank you sir, its worked! But i hope we will have color parameter for this widget some day, because everytime i want to change border color for specific card, i need to add it to Theme and copyWith, it cause my code a litte longer.
