### ISSUE TITLE
More Windows 11 Updates

### ISSUE THREAD

**Issue by bdlukaa** [bdlukaa/fluent_ui#65]
Continuation of #50

*Note: I'll not do this updates, and if I do, it's not gonna be anytime soon*

- [x] Update the typography (TextTheme)
- [ ] Implement `CalendarDatePicker` and `CalendarView`
- [x] Implement `MenuFlyout`
- [ ] Update `ProgressBar`
- [ ] Implement `ToggleSplitButton`

Feel free to make pull requests with the implementation for the above.

**Comment by Poopooracoocoo** [comment]
I just hopped on the web demo and noticed that it's not using the new set of icons.

**Comment by henry2man** [comment]
> * [ ]  Implement `CalendarDatePicker` and `CalendarView`
Related to https://github.com/bdlukaa/fluent_ui/issues/236

**Comment by bdlukaa** [comment]
Closing in favor of #411 and #236
