### ISSUE TITLE
Some widgets don't inherit `fontFamily` from FluentTheme.fontFamily

### ISSUE THREAD

**Issue by kbkb1216** [bdlukaa/fluent_ui#654]
![image](https://user-images.githubusercontent.com/19679347/207759285-ba43de9b-8493-4a70-a69e-a23352953590.png)
![image](https://user-images.githubusercontent.com/19679347/207759461-4d0fe671-ddc8-4ce1-9998-e32410a02c9e.png)

**Comment by bdlukaa** [comment]
What are those widgets?

**Comment by kbkb1216** [comment]
TextBox   TextFormBox 
MenuFlyoutItem
I must specify fontFamily separately, like this
![image](https://user-images.githubusercontent.com/19679347/208038796-cdbfc480-ecd5-4cd7-beef-c5a4abd5ede7.png)

**Comment by bdlukaa** [comment]
@kbkb1216 hey! could you check if #658 fixes the issue?

**Comment by kbkb1216** [comment]
sry, I have COVID-19.

TextBox is OK
MenuFlyoutItem and  CommandBarButton(when click [...] show float bar)  are not OK

<img width="134" alt="image" src="https://user-images.githubusercontent.com/19679347/209633932-b4ea0993-347c-405a-bcf2-76d0c56bb794.png">
<img width="158" alt="image" src="https://user-images.githubusercontent.com/19679347/209638071-30bd26f0-242a-4b5e-a5ef-1447239a193c.png">
