### ISSUE TITLE
Windows drag when TitleBarStyle.hidden

### ISSUE THREAD

**Issue by abhay-s-rawat** [bdlukaa/fluent_ui#661]
**Describe the solution you'd like**
I would like to use DragToMoveArea widget provided by windowManager so that when title bar is hidden I can drag with FluentApp navigation bar.

**Describe alternatives you've considered**
Currently I am using it like as below, now user has to drag title text to drag window.
```
appBar: NavigationAppBar(
          height: 40,
          leading: const Icon(FluentIcons.a_a_d_logo),
          title: const DragToMoveArea(child: Text("FFMpeg Testing")),
          automaticallyImplyLeading: false,
          actions:
              Row(mainAxisAlignment: MainAxisAlignment.end, children: const [
            if (!kIsWeb) WindowButtons(),
          ]),
        ),
```
**Additional context**
NavigationAppBar can be reconstructed to have a argument which will but its content inside DragToMoveArea, to move window.

**Comment by bdlukaa** [comment]
Hey! The title property can take the whole width. As you can see in the following screenshot, the title takes all the blue area. You can wrap your `Text` in an `Align` widget to enforce the alignment and fill the whole width. 

![example 29_12_2022 12_12_33](https://user-images.githubusercontent.com/45696119/209972935-5f4e4ffe-5424-442a-b99c-58343f3c90d4.png)

You can take the example app as an example

**Comment by abhay-s-rawat** [comment]
No no no. I think I haven't cleared the question. I will explain see.

```
// To make window draggable I am using like below
title: const DragToMoveArea(child: Text("FFMpeg Testing"))
// drawback is I can only drag my window if I drag through NavigationAppBar title.
```
```
// Can you do like this ?
appBar: NavigationAppBar(
          height: 40,
          draggable: true,  //<= Adding this will make window draggable
          leading: const Icon(FluentIcons.a_a_d_logo),
          title: Text("FFMpeg Testing"), // No need to use draggable here
          automaticallyImplyLeading: false,
          actions:
              Row(mainAxisAlignment: MainAxisAlignment.end, children: const [
            if (!kIsWeb) WindowButtons(),
          ]),
        ),
// Dragging issue will be solved
```

**Comment by abhay-s-rawat** [comment]
And If I hover corners I cannot resize window.
```
await windowManager.setTitleBarStyle(
        TitleBarStyle.hidden,
        windowButtonVisibility: false,
      );
```

**Comment by bdlukaa** [comment]
¹ You can take the example app as an example of how to make your app bar movable. You must enforce the `title` to fill the whole app bar

² The following is not possible since dragging is only possible with the `window_manager` package
> `draggable: true,  //<= Adding this will make window draggable`

³ 
> And If I hover corners I cannot resize window.

If you have issues with `window_manager`, please open the issue in its repository
