### ISSUE TITLE
🐛 Date Picker Exceeding Size on Open

### ISSUE THREAD

**Issue by luis-otvio** [bdlukaa/fluent_ui#663]
Overflow occurs when using the Fluent UI date field in MacOS desktop version, Flutter 3.3.10, MacOS Ventura 13.1 (22C65). I already tried to increase the width of the parent field to verify if the popup also increased, but it didn't work. I didn't find any width property for the popup on it.

To reproduce this problem, I added a DatePicker field inside a ContentDialog, I don't know if this information is relevant, but that's how I got the overflow to happen.

![Captura de Tela 2022-12-27 às 12 33 34](https://user-images.githubusercontent.com/25575479/209689272-7bab2435-ade3-481f-be1b-5ffe1f1ec7a1.png)

I'm using brazilian portuguese localizations for my application, i if its will help there.
Another detail I noticed is that in the safari browser (including in the Showcase page of Flutter UI) the problem does not occur.
I'm not using any major font settings in the operating system or anything like that.

Since j'

**Comment by bdlukaa** [comment]
I can not reproduce this on Windows, unfortunately. Maybe something related to MacOS font?
