### ISSUE TITLE
Choice to choose between current segoe mdl2 icons and segoe fluent icons

### ISSUE THREAD

**Issue by Hopy-Jaden** [bdlukaa/fluent_ui#664]
segoe mdl2 icons: https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font
Segoe fluent icons in windows 11: https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font

**Is your feature request related to a problem? Please describe.**
When I am using this package to create a fluent app for windows 11, the icons are limited to mdl2 but not fluent. The whole app looks weird compared with the rest of the windows 11 apps.

**Describe the solution you'd like**
I would like to have a choice to choose between mdl2 icons and fluent icons. For example
Original: "FluentIcons.add_field"
New: "FluentIcons.fluent.add_field" & "FluentIcons.mdl2.add_field"

**Describe alternatives you've considered**
https://pub.dev/packages/fluentui_icons
I have tried to use the fluentui_icons pack before, but it cannot work well with this fluent_ui package. This means The icons are unable to choose the fluent style.

**Additional stuff**
Also, Is it possible to update the top navigation view to the windows 11 top navigation view? Thank you ^v^
![image](https://user-images.githubusercontent.com/96371992/209797749-80907688-95be-402c-9e13-483542090c94.png)
![image](https://user-images.githubusercontent.com/96371992/209797082-1bb241d2-5976-4ddd-be09-02b42cad40c0.png)

**Comment by bdlukaa** [comment]
Hey! Segoe Fluent Icons weren't used because of its License. I am not sure if they allow third party apps to use the font family.

https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#how-do-i-get-this-font

> On a Mac or other device: You can download Segoe Fluent Icons and other fonts [here](https://learn.microsoft.com/en-us/windows/apps/design/downloads/#fonts). *You can download the font for use in design and development, but you may not not ship it to another platform*

To my understanding, it can only be used for development, but can't be published

**Comment by Hopy-Jaden** [comment]
How about the top navigation view? I wonder if it is possible to turn it into windows 11 style. Kinda love it

**Comment by bdlukaa** [comment]
> How about the top navigation view?

It is already in Win 11 style. check the example app
