### ISSUE TITLE
Buttons and text box enhancement

### ISSUE THREAD

**Issue by Hopy-Jaden** [bdlukaa/fluent_ui#666]
**Is your feature request related to a problem? Please describe.**
1. Parameters to resize the buttons (including filled buttons, icon buttons, toggle buttons, dropdown buttons, split buttons)
2. ability to add a floating action button in a fluent style
3. Ability to have leading and action parameter to the textbox and auto suggestion box

**Describe the solution you'd like**

_Example with parameters width and height to change the size of buttons_
```
Button(
  child: const Text('A better button I guess),
  onPressed: disabled ? null : () => debugPrint('pressed button'),
  width: 20px
  height: 20px
)
```

_Example of having floating action button (also have customization to the size of button?)_
WIndows 11 clock app:
![image](https://user-images.githubusercontent.com/96371992/210067170-d38c45df-e57d-4d18-b4c7-e1c7ef5eb672.png)
```
FloatingActionButton(
  child: Row(
     Icon(FluentIcons.edit), 
     Icon(FluentIcons.add), 
  ),
  onPressed: disabled ? null : () => debugPrint('pressed button'),
  width: 20px
  height: 20px
)
```

_Example of having action icon in auto suggestion box_ 
**Old - Auto Suggestion box in Documentation:**
![image](https://user-images.githubusercontent.com/96371992/210068512-39e101a8-07eb-4b10-8169-372677bc8ab6.png)
**New - Windows 11 microsoft store search box:**
![image](https://user-images.githubusercontent.com/96371992/210068724-fa3fb3be-653e-489c-bbfc-dea2a57a08a8.png)
```
String? selectedCat;

AutoSuggestBox<String>(
  items: cats.map((cat) {
    return AutoSuggestBoxItem<String>(
      value: cat,
      label: cat,
      onFocusChange: (focused) {
        if (focused) { 
          debugPrint('Focused $cat');
        }
      }
    );
  }).toList(),
  onSelected: (item) {
    setState(() => selected = item);
  },
  actions: Icons(FluentIcons.search),
),

const cats = <String>[
  'Abyssinian',
  'Aegean',
  'American Bobtail',
  'American Curl',
  ...
];
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bdlukaa** [comment]
Hello!

¹ You can wrap the desired button in a `SizedBox` and enforce constraints. Also, buttons are fully customizable, you can customize the padding inside them to make them look small, as well as the content size (icon or font size).

² The requested button is not listed in the Windows UI documentation. To be honest, the Clock "floating action button" looks more like a `Row` with two `IconButton`s surrounded by a card. It can be easily achieved:

```dart
Card(
  child: Padding(
    padding: EdgeInsets.symmetric(horizontal: 6.0, vertical: 4.0),
    child: Row(children: [
      IconButton(...),
      const SizedBox(width: 4.0),
      IconButton(...),
    ]),
  ),
),
```

³ You can provide the `trailingIcon` parameter

**Comment by bdlukaa** [comment]
About AutoSuggestBox, some updates were pushed to master. In fact, you can now change unfocused and focused highlight colors. 

Closing as not planned
