### ISSUE TITLE
AutoSuggestBox Initial Value

### ISSUE THREAD

**Issue by WH-Creations** [bdlukaa/fluent_ui#676]
**Is your feature request related to a problem? Please describe.**
I have a use case where AutoSuggestBox is perfect in every way, except for its inability to provide an initial value.

**Describe the solution you'd like**
Add 'initialValue' property to the AutoSuggestBox or something analogous that makes sense.

**Describe alternatives you've considered**
I've tried other controls including the ComboBox, which does some of what I need...but in a perfect world I'd be able to just provide an initial value to the AutoSuggestBox.

**Comment by bdlukaa** [comment]
Hi! You can use the `controller` property in `AutoSuggestBox` to set an initial value:

```dart
```

**Comment by WH-Creations** [comment]
Awesome, thanks :) That solves it! Cheers and I appreciate all the work on this, it has been very easy to work with.
