### ISSUE TITLE
🐛 The method '_FluentTextSelectionControls.buildHandle' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildHandle'.

### ISSUE THREAD

**Issue by slimyjimmy** [bdlukaa/fluent_ui#69]
First of all: Thanks for your work.

The app that I tried to incorporate fluent_ui (3.1.0) into, fails to compile.
I get the following error messages:

> ../../flutter/.pub-cache/hosted/pub.dartlang.org/fluent_ui-3.1.0/lib/src/controls/form/selection_controls.dart:50:10: Error: The method '_FluentTextSelectionControls.buildHandle' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildHandle'.
  Widget buildHandle(

> ../../flutter/packages/flutter/lib/src/widgets/text_selection.dart:123:10: Context: This is the overridden method ('buildHandle').
  Widget buildHandle(BuildContext context, TextSelectionHandleType type, double textLineHeight, [VoidCallback? onTap, double? startGlyphHeight, double? endGlyphHeight]);

> ../../flutter/.pub-cache/hosted/pub.dartlang.org/fluent_ui-3.1.0/lib/src/controls/form/selection_controls.dart:61:10: Error: The method '_FluentTextSelectionControls.getHandleAnchor' has fewer positional arguments than those of overridden method 'TextSelectionControls.getHandleAnchor'.
  Offset getHandleAnchor(TextSelectionHandleType type, double textLineHeight) {

> ../../flutter/packages/flutter/lib/src/widgets/text_selection.dart:128:10: Context: This is the overridden method ('getHandleAnchor').
  Offset getHandleAnchor(TextSelectionHandleType type, double textLineHeight, [double? startGlyphHeight, double? endGlyphHeight]);

> Failed to compile

**Comment by bostrot** [comment]
Seems like this is an issue with v3.1.0. Using the master branch worked for me:


    fluent_ui:
      git: https://github.com/bdlukaa/fluent_ui.git

**Comment by slimyjimmy** [comment]
Using the master branch works for me, too

**Comment by tobiasht** [comment]
I am using the master branch, but it is not working for me. I need to stay on 2.2.3 stable to compile the application

**Comment by bdlukaa** [comment]
Published version 3.2.0 that fixes this issue!
