### ISSUE TITLE
Nested navigation on paneitem🐛 

### ISSUE THREAD

**Issue by diegotus** [bdlukaa/fluent_ui#692]
hello, i want to congratulate you for this nice UI. but unfortunately im have some issue to implemant a nested navigation on desktop(windows);
i have the navigation pane on le left, and one of the paneItem has a button that lead to onether content. i archived the navitation to the other page, but the back button on the navigation par on top doesnt appear or stay disabled if automaticallyImplyLeading: false.
how can you help me please?

**Comment by h3x4d3c1m4l** [comment]
Hi! Could you perhaps get us a sample project that shows the issue?

thanks!
