### ISSUE TITLE
🐛 Auto Suggest Box Ignore Mouse Click

### ISSUE THREAD

**Issue by devahmedghanim** [bdlukaa/fluent_ui#698]
Auto Suggest Box works when pressing enter on your keyboard but it ignores the mouse click

**Comment by PurshuRana** [comment]
Yes same issue for me after latest update 4.2.0

**Comment by devahmedghanim** [comment]
hello sir ,
Are There Any Updates About This bug

**Comment by h3x4d3c1m4l** [comment]
Unfortunately this does not look like it’s easy fixable.

This has our attention but please find a workaround meanwhile :) perhaps you can workaround it using a `GestureDetector` to detect a click?

**Comment by PurshuRana** [comment]
Okay, thanks i will manage

**Comment by dyxin00** [comment]
To solve this bug, you can refer to https://github.com/flutter/flutter/issues/119390

**Comment by PurshuRana** [comment]
Thanks found the fix.

**Comment by gagsti02** [comment]
just add focusNode inside AutoSuggestBox.

`AutoSuggestBox(
focusNode: FocusNode()
)`

**Comment by devahmedghanim** [comment]
> 



> just add focusNode inside AutoSuggestBox.
> 
> `AutoSuggestBox( focusNode: FocusNode() )`


not work

i think the issue from flutter update 
widget of tap region has 2 function 
inside region and outside region
if you select item from outside region it will work with you
but if you select from inside region the issue will be happen => because the focus will be loss

i dont know how it fix ;
[PurshuRana] type this comment  => Thanks found the fix ;
if he can explain what he do we will => Grateful to you ;

**Comment by devahmedghanim** [comment]
1- Create Focus Node  => FocusNode node = FocusNode();
2- In Child Of AutoSuggestBoxItem  Wrap **TextFieldTapRegion** for Text
3- inside TextFieldTapRegion Type This Function => onTapInside: (event) => node .requestFocus(),
4- You Must Click on widget You Creating like Text in Step number 3

**Comment by devahmedghanim** [comment]
AutoSuggestBox in new version of dart
Null check operator used on a null value

i used sample code in documentation
