### ISSUE TITLE
Closing new Flyout programmatically

### ISSUE THREAD

**Issue by pamtbaau** [bdlukaa/fluent_ui#701]
**Is your feature request related to a problem? Please describe.**
In a MenuFlyoutItem I call a dialog. The Flout does not close.

**Describe the solution you'd like**
I expected something like `flyoutController.close();`

**Describe alternatives you've considered**
Haven't found any alternative.

**Additional context**

**Comment by bdlukaa** [comment]
Use `Navigator.of(context).pop()`

**Comment by pamtbaau** [comment]
I'm sure I've tried that... probably in the wrong location. It does indeed work. Thanks!
