### ISSUE TITLE
🐛 The ContentDialog's size and State bug.

### ISSUE THREAD

**Issue by wpbkj** [bdlukaa/fluent_ui#703]
**Describe the bug**
1.  When I want to add multiple Widgets (like a Column) to the ContentDialog, its height automatically becomes the highest. I know that if I use SizedBox and specify the size, I can solve this problem, but why can't it automatically limit its size?
2.  If I add a RadioButton or ToggleSwitch to the ContentDialog, even if setState is used, they will not work (cannot switch states).

**Expected behavior**
I think it should automatically limit its size.
The setState can take effect.

**Code**
```
          ContentDialog(
            title: const Text('确认关闭'),
            content:
                Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              const Text('请确认关闭此窗口！'),
              RadioButton(
                checked: closeType == 'ask',
                onChanged: (value) {
                  if (value) {
                    setState(() {
                      closeType = 'ask';
                    });
                  }
                },
                content: const Text('询问(默认)'),
              ),
              const SizedBox(height: 10),
              RadioButton(
                checked: closeType == 'close',
                onChanged: (value) {
                  if (value) {
                    setState(() {
                      closeType = 'close';
                    });
                  }
                },
                content: const Text('直接关闭'),
              ),
            ]),
            actions: [
              FilledButton(
                child: const Text('确认'),
                onPressed: () {
                  Navigator.pop(context);
                  windowManager.destroy();
                },
              ),
              Button(
                child: const Text('取消'),
                onPressed: () {
                  Navigator.pop(context);
                },
              ),
            ],
          )
```

**Screenshots**
<img width="283" alt="image" src="https://user-images.githubusercontent.com/63390552/215260118-86e37f16-adaa-4fc2-a4b3-50b155de05d1.png">

**Additional context**
I am a Chinese and my English level is limited. If I don't make it clear, please forgive me

**Comment by bdlukaa** [comment]
Use `Column(mainAxisSize: MainAxisSize.min, ...` to limit the column to its min size

**Comment by wpbkj** [comment]
Ok, thanks, but what about the second question?

**Comment by wpbkj** [comment]
Ok, thanks, but what about the second question?

**Comment by bdlukaa** [comment]
> If I add a RadioButton or ToggleSwitch to the ContentDialog, even if setState is used, they will not work (cannot switch states).

You're probably calling `setState` from the parent widget. You must create a `StatefulWidget` and use in the `content` parameter in order to update the dialog itself. When you call `showDialog`, it pushes a new route, which doesn't update when other routes are updated. You can also try to use a `StatefulBuilder`

**Comment by wpbkj** [comment]
Thank you very much. I understand that I haven't learned enough.
