### ISSUE TITLE
🐛Use ``typography`` in Text(also SelectableText) and use ``setState`` to change that , the font color cannot be changed when switching dark mode.

### ISSUE THREAD

**Issue by wpbkj** [bdlukaa/fluent_ui#706]
**Describe the bug**
When I dynamically change Text to Text.rich (also SelectableText) , the font color cannot be changed when switching dark mode.
I wrote a page to reproduce this bug.

**Code**
```
import 'package:fluent_ui/fluent_ui.dart';

class DebugPage extends StatefulWidget {
  const DebugPage({Key? key}) : super(key: key);

  @override
  State<DebugPage> createState() => _DebugPageState();
}

class _DebugPageState extends State<DebugPage> {
  Text testText = const Text('Normal Text');

  void changeText() {
    Typography typography = FluentTheme.of(context).typography;
    setState(() {
      testText = Text.rich(TextSpan(children: [
        TextSpan(
            text: 'Text.rich',
            style: typography.body?.apply(fontSizeFactor: 1.00))
      ]));
    });
  }

  @override
  Widget build(BuildContext context) {
    return ScaffoldPage.scrollable(
        header: const PageHeader(title: Text('DEBUG TEST')),
        children: [
          testText,
          const SizedBox(height: 20),
          FilledButton(
              child: const Text('changeTextToText.rich'),
              onPressed: () {
                changeText();
              })
        ]);
  }
}

```

**Screenshots**
This is the initial state. At this time, switching the Dark Mode is normal.

![image](https://user-images.githubusercontent.com/63390552/215312343-2e31ac92-a868-4d24-88eb-5d11145c2394.png)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/63390552/215312446-c071c79a-2582-4830-b989-740b9852460d.png">

When I change Text to Text.rich (Clicked the Button) , and switching the Dark Mode, the font color not work nice.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/63390552/215312482-26eac6d8-9260-4bb8-996f-81da87038f5f.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/63390552/215312501-d8149a9a-c6fa-4e23-ba73-9ec374df90db.png">

**Comment by wpbkj** [comment]
I think that's beacuse the ``typography``, If I remove ``typography``, there is no question.

**Comment by wpbkj** [comment]
I changed the page's code, now it's more common.

```
import 'package:fluent_ui/fluent_ui.dart';

class DebugPage extends StatefulWidget {
  const DebugPage({Key? key}) : super(key: key);

  @override
  State<DebugPage> createState() => _DebugPageState();
}

class _DebugPageState extends State<DebugPage> {
  Text testText = const Text.rich(TextSpan(text: 'TextBefore'));

  void changeText() {
    Typography typography = FluentTheme.of(context).typography;
    setState(() {
      testText = Text('TextAfter',
          style: typography.body?.apply(fontSizeFactor: 1.00));
    });
  }

  @override
  Widget build(BuildContext context) {
    return ScaffoldPage.scrollable(
        header: const PageHeader(title: Text('DEBUG TEST')),
        children: [
          testText,
          const SizedBox(height: 20),
          FilledButton(
              child: const Text('changeText'),
              onPressed: () {
                changeText();
              })
        ]);
  }
}

```

**Comment by bdlukaa** [comment]
> When I change Text to Text.rich (Clicked the Button) , and switching the Dark Mode, the font color not work nice.

This is likely a state management issue because the `testText` widget isn't updated when the theme changes. I would recommend you to not store the Widget in a variable. Instead, store only the text string.

This is working as intended.
