### ISSUE TITLE
🐛 Closing a PaneItemExpander close the app

### ISSUE THREAD

**Issue by AlexisL61** [bdlukaa/fluent_ui#707]
**Describe the bug**
When closing a PaneItemExpander, the app close itself.

**To Reproduce**
1. Go to [https://bdlukaa.github.io/fluent_ui/](https://bdlukaa.github.io/fluent_ui/)
2. Click on NavigationView
3. Click on account in the example
4. Click again on account to close the expander

**Expected behavior**
The Expander should close, and not the app

**Comment by h3x4d3c1m4l** [comment]
Looks like a crash, the window goes to black and it prints this error:

`Unhandled Exception: 'package:fluent_ui/src/controls/flyouts/flyout.dart': Failed assertion: line 470 pos 12: 'isAttached': This controller must be attached to a FlyoutTarget`

The error gets printed when you open the `PaneItemExpander`, but it does go to black till you close the `PaneItemExpander`.

**Comment by bdlukaa** [comment]
will check

**Comment by longfit** [comment]
error click at PaneItemExpander

I use 
git: https://github.com/bdlukaa/fluent_ui.git 
which can fix below error at Linux , ios , windows 

But I still came below error message at android , no matter using 4.3.0



error message from  android debug:

 void _ensureAttached() {
    assert(isAttached, 'This controller must be attached to a FlyoutTarget');
