### ISSUE TITLE
🐛 Scrollbar This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

### ISSUE THREAD

**Issue by slimyjimmy** [bdlukaa/fluent_ui#71]
I get the following error message using a `NavigationBody` (which contains two views):

> The following assertion was thrown during a scheduler callback:
> This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 
> 
> Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
> When the exception was thrown, this was the stack: 
> #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:909:9)
> #1      State.context (package:flutter/src/widgets/framework.dart:915:6)
> #2      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1236:98)
> #3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
> #4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
> #5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
> #9      _invoke (dart:ui/hooks.dart:166:10)
> #10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
> #11     _drawFrame (dart:ui/hooks.dart:129:31)
> (elided 3 frames from dart:async)

To be honest, I'm a little baffled. The error seems to be related to the `NavigationBody` (since I don't get the error when using a regular Material `Scaffold`). I tried adding `AutomaticKeepAliveClientMixin`s to the views of the `NavigationBody` but that didn't help.

Have any of you ever experienced something similar?

**Comment by bdlukaa** [comment]
This issue is happening since I ever implemented scrollbars. It happens when we resize the window I think.

Tho, this is a Flutter issue. It happens on `RawScrollbar`

**Comment by NicolaVerbeeck** [comment]
Seems like it is fixed on the flutter master branch

**Comment by TerryLiu** [comment]
I met the same problem

**Comment by YehudaKremer** [comment]
same here.
1. clone repo
2. debug example:
![image](https://user-images.githubusercontent.com/946652/143217833-9cfd153e-a873-412f-8bb6-8c45c094c71d.png)

**Comment by WinXaito** [comment]
Seems to be fixed with: 

```dart
child: Scrollbar(
  controller: pane.scrollController ?? ScrollController(),
  ...
)
```

At these lines:

https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/pane.dart#L340
https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/pane.dart#L464
https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/pane.dart#L583


But after that, I've the following error (only at the changement `compact -> open` and `open -> compact`, otherwise when I resize the window I don't have any errors.

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1285:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1310:6)
#2      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1242:16)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#9      _invoke (dart:ui/hooks.dart:166:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#11     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
====================================================================================================
```

**Comment by bdlukaa** [comment]
https://github.com/flutter/flutter/pull/92657 seems to have fixed it. Tho it might take a while to land on stable

**Comment by bdlukaa** [comment]
https://github.com/flutter/flutter/issues/82573

**Comment by jonahzheng** [comment]
it is fixed on the flutter master branch.

flutter channel master

**Comment by WinXaito** [comment]
@bdlukaa what about this ? 

I got that with TabView... :(

**Comment by shiwenwang** [comment]
> 

me too, so what's the solution for TabView? 

flutter version: 2.10.5
fluent_ui version: 3.11.0

**Comment by shiwenwang** [comment]
> @bdlukaa what about this ?
> 
> I got that with TabView... :(

me too, so what's the solution for TabView?

flutter version: 2.10.5
fluent_ui version: 3.11.0
