### ISSUE TITLE
🐛 FlyoutController .open & .close missing

### ISSUE THREAD

**Issue by mstfkhazaal** [bdlukaa/fluent_ui#713]
Hi
FlyoutController .open and FlyoutController .close missing

@bdlukaa 
Is there a way for close?

**Comment by cxhan** [comment]
@mstfkhazaal Hi, is this problem solved?

**Comment by bdlukaa** [comment]
Yes. You can use `Flyout.of(context).close()`. You can also do `flyoutController.close()`
