### ISSUE TITLE
NavigationView body switch reset

### ISSUE THREAD

**Issue by 903531306** [bdlukaa/fluent_ui#716]
version：fluent_ui: ^3.11.1
platform windows

NavigationView The content of the NavigationBody will be reset when switching to another menu. Whether the design is the same or whether there are properties that can be set. The data loaded before switching to another menu is reloaded again

**Comment by h3x4d3c1m4l** [comment]
For upgrade steps please check the changelog of the library: https://pub.dev/packages/fluent_ui/changelog
Especially the changes in 4.0.0 will be important in this case.

**Comment by 903531306** [comment]
OK, I will try to upgrade the version
