### ISSUE TITLE
Improve visibility TreeviewItem collapse/expand toggle

### ISSUE THREAD

**Issue by pamtbaau** [bdlukaa/fluent_ui#717]
**Is your feature request related to a problem? Please describe.**
The toggle to expand/collapse a TreeviewItem is hardly visible.

![image](https://user-images.githubusercontent.com/5120011/216259157-f4f38e85-b835-4c00-91f0-ac9203962402.png)

The [original toggle defined by Fluent](https://learn.microsoft.com/en-us/fluent-ui/web-components/components/tree-view?pivots=typescript) is much more prominent:

![image](https://user-images.githubusercontent.com/5120011/216259361-a3bc391c-21b6-4faf-b0d8-09a046bbc371.png)

**Describe the solution you'd like**
- The foreground color of the toggle icon could be darkened or using thicker lines.
- Preferably, the color, or maybe even the icon itself, is a variable.

**Comment by h3x4d3c1m4l** [comment]
That looks a lot different indeed. I think the docs that are leading for the development of this component are these:
https://learn.microsoft.com/en-us/windows/apps/design/controls/tree-view

I haven't really been comparing the exact colors yet, but from a quick look (comparing the doc from your issue with the above one) it seems Microsoft is not 100% consistent with these kind of details... :(

**Comment by pamtbaau** [comment]
True, but both docs show more prominent icons than currently implemented. 

Also, have a look at the treeview implementation in the left sidebar of the[ official docs](https://learn.microsoft.com/en-us/windows/apps/design/controls/tree-view). Quite clear and crisp icons.

On further inspection, the same holds for the Combobox. Using the same docs you are revering to, but now the [Combobox](https://learn.microsoft.com/en-us/windows/apps/design/controls/combo-box)

![image](https://user-images.githubusercontent.com/5120011/216378965-c2205b6a-5ce0-4244-8b69-eeea63ae036e.png)

Also, the icon used for your Expander is more clear.

**Comment by bdlukaa** [comment]
Reproducible with the latest version.

On `fluent_ui`, we use the hardcoded color `Colors.grey[80]` (https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/tree_view.dart#L970)

On native, `textFillColorSecondaryBrush` is used (https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/TreeView/TreeView_themeresources.xaml#L40)
