### ISSUE TITLE
Please update to intl: ^0.18.0

### ISSUE THREAD

**Issue by vasilich6107** [bdlukaa/fluent_ui#721]
Please update to intl: ^0.18.0

**Comment by JesusMayuri7** [comment]
Please update to intl: ^0.18.0

**Comment by bdlukaa** [comment]
Our current dependencies depend on intl 0.17.0, so we're actually blocked on this one

**Comment by bdlukaa** [comment]
`flutter_localizations` enforce 0.17.0 (see their [pubspec](https://github.com/flutter/flutter/blob/7048ed95a5ad3e43d697e0c397464193991fc230/packages/flutter_localizations/pubspec.yaml)). When trying to upgrade, the following message is printed to the console:

```Because fluent_ui depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because fluent_ui depends on intl ^0.18.0, version solving failed.
pub get failed
```

**Comment by juanbonastre** [comment]
do you intend to update to intl: ^0.18.0 in the future?
