### ISSUE TITLE
Rename ThemeData to FlutentThemeData

### ISSUE THREAD

**Issue by vasilich6107** [bdlukaa/fluent_ui#722]
**Is your feature request related to a problem? Please describe.**
flutent_ui `ThemeData` conflicts with flutter `ThemeData` class

**Describe the solution you'd like**
Rename fluent_ui `ThemeData` to `FluentThemeData`

**Describe alternatives you've considered**
importing as but it is uncomfortable

**Additional context**
no

**Comment by bdlukaa** [comment]
A sudden change like this is not dev-friendly. In the mentioned PR, `ThemeData` is depreacted and should be removed sometime in the future
