### ISSUE TITLE
Open drop down button programatically

### ISSUE THREAD

**Issue by bdlukaa** [bdlukaa/fluent_ui#723]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to open a dropdown button programatically.

**Describe the solution you'd like**
Exposing `DropDownButtonState`, and use a key to open it

```dart
final dropdownKey = GlobalKey<DropDownButtonState>();

DropDownButton(
  key: dropdownKey,
  ...
);
```

to open the flyout:

```dart
dropdownKey.open();
dropdownKey.isOpen;
dropdownKey.close()
```

**Describe alternatives you've considered**
n/a

**Additional context**
#718

**Comment by tonka3000** [comment]
@bdlukaa Thanks for the PR. Works great. The only thing I am missing is the referenced `close` method from your example above. Do I miss something?

**Comment by bdlukaa** [comment]
@tonka3000 sorry, it was a mistake by my part. There is no `.close()` to close the flyout. To close it, use `Navigator.of(context).pop()` or, if you provide a navigator key, use `navigatroKey.pop()`
