### ISSUE TITLE
Generate TreeViewItems From data

### ISSUE THREAD

**Issue by hugetiny** [bdlukaa/fluent_ui#729]
**Is your feature request related to a problem? Please describe.**
I tried adding directory tree like data (Infinite nesting maybe) to  nested TreeViewItems ,but don't know how.
Flutter does not contain a 'id' or 'class' property and ‘queryselector’ like method to find the specific widget .So I can't continuously add children in TreeViewItem with directory tree like data

**Describe the solution you'd like**
Make flat data format or tree like data format to  treeViewItems.
data format  like this

```
List flat = [{id: 0, type: folder, name: home, parentId: -1, children: [1, 2, 3, 7]}, {id: 1, type: file, name: fuck1, parentId: 0}, {id: 2, type: file, name: fuck2, parentId: 0}, {id: 3, type: folder, name: 0000, parentId: 0, children: [4, 5]}, {id: 4, type: file, name: fuck3, parentId: 3}, {id: 5, type: folder, name: ODLC, parentId: 3, children: [6]}, {id: 6, type: file, name: fuck4, parentId: 5}, {id: 7, type: folder, name: ODLC, parentId: 0, children: [8]}, {id: 8, type: folder, name: 0000, parentId: 7, children: [9]}, {id: 9, type: file, name: fuck5, parentId: 8}]

```

the method should like
```
TreeViewItems.fromData(List flat)
```

**Describe alternatives you've considered**
Is buildContext.element.visitAncestorElements method a solution for Infinite nesting data to TreeViewItems ?

**Comment by bdlukaa** [comment]
Hello! I believe the [Iterable.map](https://api.dart.dev/stable/2.19.2/dart-core/Iterable/map.html) method is the way to go. Something like the following:

```dart
```

> Flutter does not contain a 'id' or 'class' property and ‘queryselector’ like method to find the specific widget .

you can make use of `key`s as the id for the item.

**Comment by hugetiny** [comment]
the Widget structure of "items" in TreeView is nested while the data structure is plain.So map method is not the way to go .

So which method can i find a specific widget with a key?

**Comment by hugetiny** [comment]
solved
