### ISSUE TITLE
🐛 Use NavigationView in the page, click the tab to expand and shrink the page will exit

### ISSUE THREAD

**Issue by think-of-xiao** [bdlukaa/fluent_ui#732]
**Describe the bug**

You can use it in the new page, and click the page again after clicking the tab to expand it will automatically exit. why is that?

The code in the usage example is as follows：
`NavigationView(
  appBar: const NavigationAppBar(
    title: Text('NavigationView'),
  ),
  pane: NavigationPane(
    selected: topIndex,
    onChanged: (index) => setState(() => topIndex = index),
    displayMode: displayMode,
    items: [
      PaneItem(
        icon: const Icon(FluentIcons.home),
        title: const Text('Home'),
        body: BodyItem(),
      ),
      PaneItem(
        icon: const Icon(FluentIcons.issue_tracking),
        title: const Text('Track an order'),
        infoBadge: const InfoBadge(source: Text('8')),
        body: BodyItem(),
      ),
      PaneItemExpander(
        icon: const Icon(FluentIcons.account_management),
        title: const Text('Account'),
        body: BodyItem(),
        items: [
          PaneItem(
            icon: const Icon(FluentIcons.mail),
            title: const Text('Mail'),
            body: BodyItem(),
          ),
          PaneItem(
            icon: const Icon(FluentIcons.calendar),
            title: const Text('Calendar'),
            body: BodyItem(),
          ),
        ],
      ),
    ],
  ),
)`

**Comment by h3x4d3c1m4l** [comment]
Hi! What version are you using? This should have been fixed by 4.3.0 actually.
