### ISSUE TITLE
How to use Fluent's theme in MaterialApp as a 'subTheme'?

### ISSUE THREAD

**Issue by hugetiny** [bdlukaa/fluent_ui#734]
**Is your feature request related to a problem? Please describe.**
I want to use both Fluent's theme with Material's theme in my project

**Describe the solution you'd like**
the method should be like
```
ThemeData.copyWith(Fluent's ThemeData)
```
Material's theme data is primary
and Fluent's theme is secondary

**Comment by h3x4d3c1m4l** [comment]
Hi! At the moment you can't due to ThemeData (Material) and FluentThemeData being two totally different kinds of theme data. What use case would there be for such a solution?

**Comment by bdlukaa** [comment]
I am not sure this can be a thing. One theme doesn't complement the other.

Could you detail it more what you need?

**Comment by hugetiny** [comment]
I love the treeview of fluent ui,but the other coder for my project insist on using material ui as the main ui for our app.I have already added the treeview by import fluent ui as fluent.

**Comment by bdlukaa** [comment]
You can make use of `FluentTheme`. Fluent can not be implemented into material, or vice-versa. You need to update the theme for both libraries.

Closing as invalid.
