### ISSUE TITLE
🐛 AutoSuggestBoxItem does not respond when clicked

### ISSUE THREAD

**Issue by simplezhli** [bdlukaa/fluent_ui#737]
After upgrading to the latest version 4.3.0, it was found that the `onSelected` callback method is not executed when `AutoSuggestBoxItem` is clicked.

https://user-images.githubusercontent.com/12456431/218308322-b2d86961-0ff9-4566-b16e-1e8c1e4a1d2d.mov

**Comment by bdlukaa** [comment]
Duplicate of #698
