### ISSUE TITLE
How can i navigate from PaneItem to another Screen without losing Drawer.

### ISSUE THREAD

**Issue by DevThurain** [bdlukaa/fluent_ui#739]
I am trying to implement window style navigation.
When navigate from PaneItem, it always leave the drawer.

**Comment by bdlukaa** [comment]
you can try to set your `paneDisplayMode` to `PaneDisplayMode.open`. This way, the left pane will always be there regardless of screen size.

**Comment by DevThurain** [comment]
Thanks. It help me out.
