### ISSUE TITLE
🐛 ListView does not work properly under NavigationView/NavigationPane/PaneItem.

### ISSUE THREAD

**Issue by lines-of-codes** [bdlukaa/fluent_ui#746]
**Describe the bug**
I don't know if this is a real bug or just me forgetting to read something, but anyway, The ListView does not work properly when its parent is a PaneItem (which is in the items array of NavigationPane, which is a pane for the NavigationView), At this point, I don't even know what I am doing.

**To Reproduce**
1. Get the code from [this example code](https://gist.github.com/lines-of-codes/566719670a07544c68d62d19b442f8bc)
2. add a main function and do a runApp(MyApp)
3. Run it.
4. See the error

**Expected behavior**
The ListView should work and display properly.

**Screenshots**

**Additional context**
It's likely a widget sizing issue.

**Comment by bdlukaa** [comment]
¹ you can use the `ListView.shrinkWrap` property to size the children

² you can try to wrap the ListView in a `SizedBox` and give it a specific size

**Comment by lines-of-codes** [comment]
Somehow shrinkWrap does not solve the problem for me, but SizedBox did.

**Comment by bdlukaa** [comment]
closing this as resolved
