### ISSUE TITLE
TabView lazyLoading

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#751]
I hope there's an option if we load all the tabs or when we switch that's the time the tab body will add to widget tree.

**Comment by bdlukaa** [comment]
If I understood correctly, you don't want `TabView` to make use of `IndexedStack` under the hood to display the body, therefore loading them only when the tab is selected, right?

**Comment by adpmhel24** [comment]
> If I understood correctly, you don't want `TabView` to make use of `IndexedStack` under the hood to display the body, therefore loading them only when the tab is selected, right?

Yes, you're right, it will load the body when selected.

**Comment by bdlukaa** [comment]
Fixed on https://github.com/bdlukaa/fluent_ui/commit/00c61146cba44caab0577b69f1f7330cc4132775

**Comment by adpmhel24** [comment]
> Fixed on [00c6114](https://github.com/bdlukaa/fluent_ui/commit/00c61146cba44caab0577b69f1f7330cc4132775)

Nice. Thank you so much
