### ISSUE TITLE
How can i check NavigationPane is open in PaneDisplayMode.compact ?

### ISSUE THREAD

**Issue by thitlwincoder** [bdlukaa/fluent_ui#758]
I want to use multiple `crossAxisCount` in `GridView` like below. How can i check ?

```dart
GridView.builder(
      shrinkWrap: true,
      itemCount: 10,
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: isOpen ? 3 : 4,
      ),
      itemBuilder: (context, index) {
        return itemUI(index);
      },
)
```

**Comment by h3x4d3c1m4l** [comment]
Hi! I checked the API. Using a `GlobalKey<NavigationViewState>` one can know whether the minimal pane is open, but that won't help you with the compact pane. As of now there seems to be no way of getting this.

Maybe you could change the `crossAxisCount` based on the space you have available by wrapping your widget with a `LayoutBuilder`?
