### ISSUE TITLE
Add ability to change the `NavigationPaneItem` height

### ISSUE THREAD

**Issue by ricardoboss** [bdlukaa/fluent_ui#762]
**Is your feature request related to a problem? Please describe.**
I think the icons of the `NavigationPane` are a bit small and want to change their seize. I can change the width of the column, the icon size itself, but not the pane height.

**Describe the solution you'd like**
Currently, the pane height is hardcoded (see https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/pane_items.dart#L204).

**Describe alternatives you've considered**
As described above, changed column width and icon size, neither of which let me change the height.

**Additional context**
I asked in Discord and was told to file an issue for this.

**Comment by bdlukaa** [comment]
The hardcoded value is actually wrong. The value should be `40`, as per https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/NavigationView/NavigationView_rs1_themeresources_v1.xaml#L248

A fixed height shouldn't be provided as well. Instead, just a min height, making the widget possible to expand as it needs.

`NavigationView` in general doesn't follow the theme resources from Microsoft and should be updated

**Comment by ricardoboss** [comment]
Hi, any updates on this?
