### ISSUE TITLE
🐛 When the mouse hovers over bleak, it will report theme null

### ISSUE THREAD

**Issue by 903531306** [bdlukaa/fluent_ui#763]
![image](https://user-images.githubusercontent.com/25999671/224298203-c6b283cb-f97e-427c-8e86-6b7cfd08fc54.png)
![image](https://user-images.githubusercontent.com/25999671/224298234-e2319e0e-5e76-479a-9c60-f95e30bf6bff.png)
![image](https://user-images.githubusercontent.com/25999671/224298302-c4d8fb1f-9acf-4738-b9de-b137c4f4ffc3.png)
code init
![image](https://user-images.githubusercontent.com/25999671/224298423-92de65f2-95fd-4992-a679-76cce9fd0ac6.png)
Is there a problem with my integration

**Comment by bdlukaa** [comment]
When the `builder` callback is used, the `UpgradeView` is rendered above `FluentTheme` and above the `Navigator`. You need to make use of `home` or routes.

The `builder` callback should be used to define widgets above all screens, like providers and related.

**Comment by 903531306** [comment]
Thanks, solved
