### ISSUE TITLE
🐛 Can't open a Flyout with a navigatorKey

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#764]
I have a title bar like that: 

![image](https://user-images.githubusercontent.com/8223773/224350305-732a2cbe-3ce8-4af6-85b2-1049ee0e713b.png)

This bar is outside the navigation and global to all page.

For this usage, I asked for https://github.com/bdlukaa/fluent_ui/issues/538 (thanks for that @bdlukaa)

After the upgrade of fluent_ui (from 4.1.5 to 4.4.1), I'm facing the following issue:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2961 pos 14: 'renderer.parent != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2961:14)
#3      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2661:39)
#4      FlyoutController.showFlyout (package:fluent_ui/src/controls/flyouts/flyout.dart:569:19)
#5      _ActionState.showMenu (package:dncui/src/controls/core/mw_window_caption.dart:190:16)
```

The problem is caused by this line (https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/flyouts/flyout.dart#L569 and line 572).

If I comment `, ancestor: navigatorBox`, that's work ! 

![image](https://user-images.githubusercontent.com/8223773/224351200-2926b870-2b11-437e-ac6e-42cf22cab01c.png)

The code for open the flyout:

```dart
controller.showFlyout(
      navigatorKey: widget.action.navigationKey,
      builder: widget.action.flyoutBuilder!,
      position: position,
      placementMode: FlyoutPlacementMode.bottomRight,
      margin: 0,
      // additionalOffset: -kWindowCaptionHeight,
);
```

**Comment by bdlukaa** [comment]
If ancestor is not provided, the position of the flyout is likely to be incorrect in a nested Navigator context (using `go_router`'s `ShellNavigator`, for example)

From the documentation of the `RenderBox.localToGlobal` function:
> If ancestor is non-null, this function converts the given point to the coordinate system of ancestor (which must be an ancestor of this render object) instead of to the global coordinate system.

This is what it looks like if the `, ancestor: navigatorBox` is commented in a nested Navigator context (It uses `shellNavigatorKey` from the example app):

#### Expected
![image](https://user-images.githubusercontent.com/45696119/224855323-5cc006d9-6197-46f6-82cc-43e9c438f617.png) 

#### Actual
![image](https://user-images.githubusercontent.com/45696119/224855024-c65b4d9c-d3b0-45e3-ae04-9b0594054877.png)

On the other hand, if the Navigator is not a parent of the `Flyout`, this error will be thrown (as of `renderer.parent != null`). I'm not sure that removing the reference to the navigator box is the way to go.

Your code may need to be updated to support a global navigator context

**Comment by WinXaito** [comment]
Yeah, I tried to create a new `Navigator` on the new tree, but that's not what I want:

![image](https://user-images.githubusercontent.com/8223773/224960289-914d3160-73e6-43e6-9fe1-d4bf8386960b.png)

My tree: 

![image](https://user-images.githubusercontent.com/8223773/224961573-5e0d8cbb-c60b-436d-bcfd-3592468f77cc.png)

The app bar is builded like that:

```dart
return FluentApp(
  ...
  builder: (context, child) {
    return CoreView(
      child: child ?? const Text('internal error'),
      ...
    );
  },
);
```

The appbar is constructed in the `CoreView` widget, and the content of the page is in the `child` variable. So, the Navigator is in `child` and my `CoreView` widget is not an ancestor of him.

Maybe we can add the possibility to pass a custom navigator ancestor (aka pass à `null` ancestor, otherwise we use the default navigator key..)

**Comment by WinXaito** [comment]
In fact, I found the problem.

You calculate the position with the ancestor like that:

```dart
    final targetBox = context.findRenderObject() as RenderBox;
    final targetSize = targetBox.size;
    final targetOffset =
        targetBox.localToGlobal(Offset.zero/*, ancestor: navigatorBox*/) +
            Offset(0, targetSize.height);
    final targetRect =
        targetBox.localToGlobal(Offset.zero/*, ancestor: navigatorBox*/) &
            targetSize;
```

But I give him the position manually, so the position is used like that:

```dart
targetOffset: position ?? targetOffset,
```

Si for resolve this problem, we simply must don't calculate the `targetOffset` if the `position` is gave.

If you are ok with that, I will make a PR.
