### ISSUE TITLE
🐛 Mouse cursor does not change when hovering over buttons or other controls

### ISSUE THREAD

**Issue by ricardoboss** [bdlukaa/fluent_ui#769]
**Describe the bug**
The mouse cursor always stays the same, regardless of if I hover over buttons/checkboxes (not text boxes though).

**To Reproduce**
1. run the example
2. go to Inputs > Buttons
3. hover over the buttons

**Expected behavior**
The cursor should change to `SystemMouseCursors.click`.

**Comment by ricardoboss** [comment]
It would also be nice to be able to specify the cursor on each button. But that's a feature request, not a bug.

**Comment by ricardoboss** [comment]
Note: I tested on macOS

**Comment by bdlukaa** [comment]
On native Windows, the cursor is rarely changed to `.click`, that is a common web behavior. I don't know much about macOS, but I think [`macos_ui`](http://pub.dev/packages/macos_ui) also changes it to `.click`. 

Either way, most widgets (mostly inputs) have the `mouseCursor` property and can be changed. Some can be changed by their theme data class as well

**Comment by ricardoboss** [comment]
Wow, I didn't even realize native apps don't do this. Not even macOS apps. You're totally right.

I guess this can be closed as 'intended behaviour' then.
