### ISSUE TITLE
🐛 FlyoutMenu doesn't work well

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#774]
**Describe the bug**

The FlyoutMenu and Flyout context menu doesn't work as expected in the demo application.

![image](https://user-images.githubusercontent.com/8223773/225585379-d65b5a96-1a20-4d9f-885e-61e4ae2c28bf.png)

I though that maybe come from #768 but that's not the case !

**Comment by bdlukaa** [comment]
https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/flyouts/menu.dart#L449-L453

**Comment by bdlukaa** [comment]
This is due to the multiple navigators
