### ISSUE TITLE
🐛 Moving mouse cursor in or out of the window causes focus lose

### ISSUE THREAD

**Issue by glanium** [bdlukaa/fluent_ui#777]
**Describe the bug**
Moving mouse cursor in or out of the window causes CommandBar button's focus lose

**To Reproduce**
1. Run your demo application on windows 11 desktop.
2. Go to CommandBar page.
3. Press Tab key to move focus and put focus on 1st or 2nd button CommandBar. (in case of your demo application, New button or Delete button) <- this is important to reproduce issue.
5. Move mouse cursor in or out of the window
6. Focus lost(moving to another button)

Strange behaviour

**Expected behavior**
No focus lost

**Additional context**
fluent_ui 4.4.1
flutter 3.7.7
windows 11

**Comment by WinXaito** [comment]
Note: not reproductible on Web.

**Comment by bdlukaa** [comment]
This issue is not reproducible on the latest version! Also, it should be an issue with Flutter itself, since it doesn't happen in web
