### ISSUE TITLE
Allow NumberBox to work with double value

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#788]
Currently, the NumberBox widget work only with `int` value.

The idea is to have a generic Widget that accept a type extended from `num` (that include `int` and `double`).

**Comment by bdlukaa** [comment]
Maybe a number box that accepts expressions too?

![NumberBox with math expressions support](https://user-images.githubusercontent.com/45696119/227585198-bb0007da-dc7b-4b3b-9fb2-395f0903416b.png)

**Comment by WinXaito** [comment]
Yes of course !

I had the idea but I forgot to open an issue, thanks for the remainder
