### ISSUE TITLE
Change Button style

### ISSUE THREAD

**Issue by detroxx92** [bdlukaa/fluent_ui#8]
More a question than an issue. I want to change the theme / color of a button.
The button should be blue with white text color (like a primary button for a dialog).

I think it's relativly easy, but i could not get it done.

Thanks for any help. Keep up the good work 👍

**Comment by detroxx92** [comment]
In the readme is an example of the button i want to have: Content Dialog -> last screenshot with the headline "Subscribe to App Service?"

**Comment by bdlukaa** [comment]
you can change its decoration using the style property:

```dart
Button (
   text: Text(' button '),
   style: ButtonStyle(
      decoration: (state) => yourDecoration,
   ),
)
```

Remember to add a different decoration for all the states.

**Comment by detroxx92** [comment]
Thats was the missing hint :)

Thank you very much 👍
