### ISSUE TITLE
DropDown value

### ISSUE THREAD

**Issue by the-best-is-best** [bdlukaa/fluent_ui#805]
not available value selected

**Comment by the-best-is-best** [comment]
I think the drop down menu is not showing what is selected
  When a value is selected the current value does not appear in the UI and how to set the value from the API

**Comment by bdlukaa** [comment]
You should use `ComboBox` for that

**Comment by the-best-is-best** [comment]
Thank you sorry

**Comment by the-best-is-best** [comment]
> You should use `ComboBox` for that

I am sorry thank you for helping
