### ISSUE TITLE
Add notificationPredicate on Scrollbar

### ISSUE THREAD

**Issue by harlanx** [bdlukaa/fluent_ui#809]
I'm using the property [notificationPredicate](https://api.flutter.dev/flutter/material/Scrollbar/notificationPredicate.html) to simultaneously show scrollbars in material ui however this property is not available on this ui package. Is there any plan on adding it soon?

Here's currently what I have using material's scrollbar with the compromise of not having the fluent design behavior on scrollbars.
```dart
mt.Scrollbar(
controller: _vController,
thumbVisibility: true,
 child: mt.Scrollbar(
 controller: _hController,
 thumbVisibility: true,
 notificationPredicate: (notification) => notification.depth == 1,
  child: mt.SingleChildScrollView(
  controller: _vController,
   child: mt.SingleChildScrollView(
   controller: _hController,
   scrollDirection: Axis.horizontal,
    child: const Text(_longText),
   ),
  ),
 ),
)
```

**Comment by bdlukaa** [comment]
Fixed by https://github.com/bdlukaa/fluent_ui/commit/691c806646a1926cca10685c44fe0691c38cf137
