### ISSUE TITLE
TabBar throws Unexpected Null-Value when width is too small

### ISSUE THREAD

**Issue by brianmayclone** [bdlukaa/fluent_ui#825]
When using the TabBar Widget from fluent-ui I currently encounter an error: Unexpected Null-Value under the following circumstances:

- Reducing the Width of the Parent-View containing the TabBar to a size, where not all Tabs can be rendered completely.

For Reproduction:
- All Tabs contain Text and Icons.

The TabView then only renders grey (or red in debug-mode) and is not usable anymore.

**Comment by brianmayclone** [comment]
This is the complete Error:
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════

The following TypeErrorImpl was thrown building LayoutBuilder:

Unexpected null value.

The relevant error-causing widget was:

TabView

TabView:file:///(Removed)/incident_list_tab_view.dart:50:12

incident_list_tab_view.dart:50

When the exception was thrown, this was the stack:

C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49 throw_

C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 561:63 nullCheck
packages/flutter/src/widgets/scroll_position.dart 145:49 get maxScrollExtent
packages/scroll_pos/src/scroll_pos.dart 35:53 get max
packages/scroll_pos/src/scroll_pos.dart 51:59 get canForward
packages/fluent_ui/src/controls/navigation/tab_view.dart 530:41 forwardButton
packages/fluent_ui/src/controls/navigation/tab_view.dart 555:27 <fn>
packages/fluent_ui/src/controls/navigation/tab_view.dart 567:38 <fn>
packages/flutter/src/widgets/layout_builder.dart 119:70 layoutCallback
packages/flutter/src/widgets/framework.dart 2682:19 buildScope
packages/flutter/src/widgets/layout_builder.dart 153:5 [_layout]
packages/flutter/src/rendering/object.dart 2300:59 <fn>
packages/flutter/src/rendering/object.dart 1056:15 [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 2300:7 invokeLayoutCallback
packages/flutter/src/widgets/layout_builder.dart 228:7 rebuildIfNecessary
packages/flutter/src/widgets/layout_builder.dart 313:5 performLayout
packages/flutter/src/rendering/object.dart 2189:7 layout
packages/flutter/src/rendering/box.dart 2430:11 layout
packages/flutter/src/rendering/layout_helper.dart 56:10 layoutChild
packages/flutter/src/rendering/flex.dart 903:45 [_computeSizes]
packages/flutter/src/rendering/flex.dart 938:32 performLayout
packages/flutter/src/rendering/object.dart 2027:7 [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 1020:17 flushLayout
packages/flutter/src/rendering/binding.dart 516:19 drawFrame
packages/flutter/src/widgets/binding.dart 865:13 drawFrame
packages/flutter/src/rendering/binding.dart 381:5 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1289:15 [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1218:9 handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1076:5 [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/platform_dispatcher.dart 1168:13 invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/platform_dispatcher.dart 218:5 invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/_engine/engine/initialization.dart 190:45 <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37 _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39 dcall

**Comment by WinXaito** [comment]
> @WinXaito looks like an issue with `scroll_pos`

Indeed, it looks like a problem with scroll_pos

I will check that

**Comment by WinXaito** [comment]
I checked on scroll_pos, but I didn't find anything wrong, because de error comes from flutter scroll_controller.

I thing the controller is not correctly attached to the tabview. 

@brianmayclone  Can you provide a minimal reproductible example please ?

**Comment by brianmayclone** [comment]
@WinXaito Sorry I wanted to provide a sample to you within the next days.
@WinXaito @bdlukaa Tried the current master in our project and it works like a charm!

BIG THANX !
