### ISSUE TITLE
Duplicate GlobalKeys detected in widget tree

### ISSUE THREAD

**Issue by juan-jeldes** [bdlukaa/fluent_ui#830]
This is fixed in 4.5.1
the problem still occurs in this version

_Originally posted by @bdlukaa in https://github.com/bdlukaa/fluent_ui/issues/827#issuecomment-1537427161_

**Comment by bdlukaa** [comment]
Without a reproducible snippet, we can not investigate the issue. Please fill the issue template.

Also, have you tried to run `flutter pub upgrade` to ensure the latest version is used?
