### ISSUE TITLE
🐛 need to upgrade Intl version to  0.18.0 or above

### ISSUE THREAD

**Issue by jayakumarzoftsol** [bdlukaa/fluent_ui#837]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alevinetx** [comment]
@bdlukaa   Is there any reason preventing this?   I haven't experienced any issues with a dependency override.

**Comment by bdlukaa** [comment]
It is actually due to `flutter_localizations` from Flutter 3.10, which is used by the package. They require 0.18.0 on master
