### ISSUE TITLE
Can onTap in PaneItem intercept jump events

### ISSUE THREAD

**Issue by FengZi-lv** [bdlukaa/fluent_ui#846]
```dart
PaneItem(
    onTap: () {
      Logger().i('hello');
    },
)
```

Normally, when i click on 'PaneItem', I execute 'Logger().i('hello'); 'and jump to another page.

But now I need to just execute 'Logger().i('hello'); 'Do not jump.

Thanks.

**Comment by bdlukaa** [comment]
You can use `PaneItemAction` to achieve that behavior. For more custom behavior, you can extend the `PaneItem` class: https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart#L741-L774
