### ISSUE TITLE
Slider -  Label visualisation  🐛 

### ISSUE THREAD

**Issue by tobiasht** [bdlukaa/fluent_ui#847]
Should be a background on the label and the font color for light mode is wrong.

![Screenshot 2023-05-27 at 11 26 41](https://github.com/bdlukaa/fluent_ui/assets/20655261/32363f27-997b-4464-bd92-b5e8409d7255)
![Screenshot 2023-05-27 at 11 26 32](https://github.com/bdlukaa/fluent_ui/assets/20655261/76d431f0-b3e5-4284-ab34-c9c5726f6b09)

**Comment by bdlukaa** [comment]
Please, fill the issue template.

**Comment by tobiasht** [comment]
Can you reopen this one?
