### ISSUE TITLE
Wishlist for new widgets

### ISSUE THREAD

**Issue by tobiasht** [bdlukaa/fluent_ui#85]
There is a couple of widgets that I would like to use in my project, which is currently not a part of the fluent_ui. I have listed them in order of personal importance. I would very much appreciate if anyone could add any of these, especially the first one.

- [x] [Expander](https://docs.microsoft.com/en-us/windows/apps/design/controls/expander)
![image](https://user-images.githubusercontent.com/20655261/139147636-5946d11e-b9de-4a1c-b833-1f789d447cb0.png)

- [x] [TreeView](https://docs.microsoft.com/en-us/windows/apps/design/controls/tree-view) (#120)
![image](https://user-images.githubusercontent.com/20655261/139147736-39cb56e5-1e42-4750-aadc-6d062bb45fb3.png)

- [x] [Drop down button](https://docs.microsoft.com/en-us/windows/apps/design/controls/buttons#create-a-drop-down-button) (#108)
![image](https://user-images.githubusercontent.com/20655261/139147800-80240577-710b-4c42-b98f-c529fcab5dcb.png)

- [ ] [Increment and decrement stepping](https://docs.microsoft.com/en-us/windows/apps/design/controls/number-box)
![image](https://user-images.githubusercontent.com/20655261/139147855-f2d268f6-97c3-46fd-b916-22122394cb46.png)

- [ ] [Teaching tip](https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/teaching-tip)
![image](https://user-images.githubusercontent.com/20655261/139147941-b2539472-fedc-4478-b565-96b95be1dd32.png)
![image](https://user-images.githubusercontent.com/20655261/139147990-7fbb8ce4-4700-4eab-9a07-8725e77b4c27.png)

**Comment by antoniopetricc** [comment]
Is it possible to add a DataTable as well?

**Comment by bdlukaa** [comment]
Closing in favor of #412
