### ISSUE TITLE
🐛  The parameter 'clipboardStatus' of the method '_FluentTextSelectionControls.buildToolbar' has type 'ClipboardStatusNotifier?'

### ISSUE THREAD

**Issue by ariancamejo** [bdlukaa/fluent_ui#852]
The parameter 'clipboardStatus' of the method '_FluentTextSelectionControls.buildToolbar' has type 'ClipboardStatusNotifier?', which does not match the corresponding type, 'ValueListenable<ClipboardStatus>?', in the overridden method, 'TextSelectionControls.buildToolbar'.

 fluent_ui: 4.6.2

environment:
  sdk: '>=2.19.2 <3.0.0'

**Comment by bdlukaa** [comment]
What flutter version are you using?

**Comment by ariancamejo** [comment]
Flutter versión: 3.11.0-11.0.pre.3

**Comment by bdlukaa** [comment]
`fluent_ui` is meant to run on the Flutter stable channel
