### ISSUE TITLE
Microsoft Store like NavigationPaneItems

### ISSUE THREAD

**Issue by Auties00** [bdlukaa/fluent_ui#853]
**Is your feature request related to a problem? Please describe.**
In the Microsoft Store, the item pane looks like this:
![image](https://github.com/bdlukaa/fluent_ui/assets/28218457/702c6345-15b9-4f7e-98db-ab21e2f42bdd)
This isn't possible with NavigationPaneItem as far as I can tell.

**Describe the solution you'd like**
I was wondering if a paneItemBuilder method could be added, considering that paneBodyBuilder exists.
I could work on a PR if the functionality isn't actually there.

**Comment by bdlukaa** [comment]
you can actually extend the `PaneItem` class and use it like a `PaneItem`. Similar to usages of `PaneItemAction` and `PaneItemExpander`

**Comment by Auties00** [comment]
thanks for letting me know
