### ISSUE TITLE
🐛 PaneItemExpander error "A FlyoutController was used after being disposed".

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#857]
when clicking the items of PaneItemExpander i got an error of A FlyoutController was used after being disposed.

**Comment by adpmhel24** [comment]
https://github.com/bdlukaa/fluent_ui/assets/40779451/e35c7f62-6bae-44fc-915b-a70612f09830

**Comment by bdlukaa** [comment]
What version of `fluent_ui` are you using? Probably a duplicate of #818

_please fill the issue template next time_

**Comment by adpmhel24** [comment]
> What version of `fluent_ui` are you using? Probably a duplicate of #818
> 
> _please fill the issue template next time_

Even though the displayMode is compact

**Comment by bdlukaa** [comment]
Sorry, but I was not able to reproduce this issue. Can you try it on the example application?

**Comment by Quintonvv** [comment]
I created a web application for flutter, I get the same errors.

When I use the app in Fullscreen with the expanded menu, the error does not appear, however when its compact or even closed (mobile) I get an error related to FlyOut.

Error on conpact:  A FlyoutController was used after being disposed.
Error when on mobile: "This controller must be attached to a FlyoutTarget".
