### ISSUE TITLE
NavigationPaneExpander Items, ontap doesnt trigger when flyout.

### ISSUE THREAD

**Issue by adpmhel24** [bdlukaa/fluent_ui#859]
**Describe the bug**
It doesnt trigger the onTap when the navigationexpander items were in flyout.

https://github.com/bdlukaa/fluent_ui/assets/40779451/2c7745a4-19e2-48e2-8087-a1f4081dcd25

**Comment by bdlukaa** [comment]
What version of `fluent_ui` are you using? This should be fixed in the latest version
