### ISSUE TITLE
RadioButton and CheckBox disabled text

### ISSUE THREAD

**Issue by WinXaito** [bdlukaa/fluent_ui#861]
Sometimes, I want to disable a text (with radio box, or checkbox, etc.)

So, I do something like that:

```dart
final replaceFileText = DefaultTextStyle.merge(
      child: const Text('Remplacer le fichier d\'origine'),
      style: TextStyle(color: FluentTheme
          .of(context)
          .disabledColor));
```

Result:

![image](https://github.com/bdlukaa/fluent_ui/assets/8223773/43ac63c1-6835-45d3-8a2c-3c39f3baebe2)

Maybe we can add an option `disabled` to `Text` ? 

And maybe, for Radio and Checkbox, apply that to text automatically when onChanged is null.

**Comment by bdlukaa** [comment]
> Maybe we can add an option disabled to Text ?

I don't think this is possible, since `Text` comes from the `flutter/widgets` library.

For the other widgets, `Button`s, `PaneItem` and a few more already make use of disabled when `onChanged` is `null`

For `CheckBox` and `RadioButton`, it can be added
