### ISSUE TITLE
🐛 cannot use "fluentui_system_icons" package with this package

### ISSUE THREAD

**Issue by saquibansari0101** [bdlukaa/fluent_ui#866]
**Describe the bug**
As each package contains icons with same class name, The name 'FluentIcons' is defined in the libraries 'package:fluent_ui/src/icons.dart (via package:fluent_ui/fluent_ui.dart)' and 'package:fluentui_system_icons/src/fluent_icons.dart (via package:fluentui_system_icons/fluentui_system_icons.dart)'. 

**To Reproduce**
1. Add fluentui_system_icons and fluent_ui package into pubspec.yaml
2. use FluentIcon anywhere in scaffold.

**Expected behavior**
Change the class name of icon.dart in package or remove the icon.dart as microsoft provides a package for it on pub.dev

**Screenshots**
![image](https://github.com/bdlukaa/fluent_ui/assets/45628219/610b0225-0d39-4aa3-8c63-f1b243361cfe)

**Comment by WinXaito** [comment]
You can use named import for resolve this conflict:

```dart
import 'package:fluentui_system_icons/fluentui_system_icons.dart' as icon;
```

And you can call icons with `icon.FluentIcons...`

---------

Or, you can hide FluentIcons from fluent_ui with:

```dart
import 'package:fluent_ui/fluent_ui.dart' hide FluentIcons;
```


See that: https://stackoverflow.com/questions/66937190/how-would-you-resolve-a-naming-conflict-inside-dart

**Comment by saquibansari0101** [comment]
Solved!
