### ISSUE TITLE
[AutoSuggestBox] Item Builder

### ISSUE THREAD

**Issue by valientegaston** [bdlukaa/fluent_ui#869]
Hi! Is there any way to change the textstyle of the suggestions? Thank you!
![Captura de Pantalla 2023-06-25 a la(s) 01 00 22](https://github.com/bdlukaa/fluent_ui/assets/4804726/c62eecac-be23-4cf9-8d34-13995846f415)

**Comment by bdlukaa** [comment]
Hello! You can use `AutoSuggestBoxItem.child` property to render any widget in the auto suggest box overlay tile.

```dart
AutoSuggestBox(
  items: [
    AutoSuggestBoxItem(
      value: 0,
      label: '0',
      child: Text('The number is 0'),
    ),
  ], 
)
```

I will keep this open because auto suggest box still misses some customization enhancements.

- [ ] Semantic label
- [ ] Item builder
