### ISSUE TITLE
🐛 AutoSuggestBox used on a null value 🐛 

### ISSUE THREAD

**Issue by mesharkw** [bdlukaa/fluent_ui#883]
**Describe the bug**
A bug occurs when clicking the AutoSuggestBox.

**To Reproduce**
1. Go to 'created Widget
2. Click on the created widget
3. Error shows null

The error actually points out to:
The following _TypeError was thrown building
_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#cdb62](dirty, dependencies:
[MediaQuery], state: _OverlayEntryWidgetState#bc0ea):
Null check operator used on a null value

**Comment by bdlukaa** [comment]
Can you provide the full stacktrace?

**Comment by mesharkw** [comment]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building
_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#cdb62](dirty, dependencies:
[MediaQuery], state: _OverlayEntryWidgetState#bc0ea):
Null check operator used on a null value

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///Users/value8/FlutterProjects/crs_mobile/lib/main.dart:84:12

When the exception was thrown, this was the stack:
#0      FluentTheme.of (package:fluent_ui/src/styles/theme.dart:25:70)
#1      _AutoSuggestBoxState._insertOverlay.<anonymous closure> (package:fluent_ui/src/controls/form/auto_suggest_box.dart:533:33)
#2      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:345:36)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#13     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#15     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#19     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#24     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#29     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#33     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#34     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#44     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#52     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#61     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#62     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#73     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#85     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#89     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#97     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#100    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#102    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#106    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#110    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#115    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#119    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#123    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#127    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#131    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#140    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#142    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#144    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#148    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#149    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#152    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#154    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#157    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#159    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#163    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#166    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#168    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#170    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#174    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#175    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#185    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#189    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#192    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#200    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#201    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#204    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#206    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#207    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#209    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#210    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#211    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#214    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#215    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#217    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#221    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#222    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#225    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#227    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#230    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#231    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#232    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#235    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#236    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#239    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#241    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#244    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#245    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#248    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#249    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#250    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#251    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#253    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#254    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#257    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#258    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#259    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#260    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#262    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#264    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#266    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#268    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#269    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#270    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#271    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#274    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#275    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#276    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#277    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#278    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#279    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#280    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#283    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#284    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#285    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#286    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#287    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#289    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#291    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#292    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#293    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#294    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#295    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#296    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#297    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#298    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#309    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 10 frames from class _Timer, dart:async, and dart:async-patch)

**Comment by bdlukaa** [comment]
Hmm. I see you are making use of `MaterialApp`. You need to either use `FluentApp` or wrap your material app with a `FluentTheme` widget
