### ISSUE TITLE
🐛 'ForceRedraw': is not a member of 'flutter::FlutterViewController'

### ISSUE THREAD

**Issue by DeVeraGiovanni** [bdlukaa/fluent_ui#889]
**Describe the bug**
Cant run the app because of an error of 
### C:\Users\Gvnn\Desktop\tib_system\windows\runner\flutter_window.cpp(37,24): error C2039: 'ForceRedraw': is not a member of 'flutter::FlutterViewController' [C:\Users\Gvnn\Desktop\tib_system\build\windows\runner\tib_system.vcxproj]
Exception: Build process failed.

**Screenshots**
![image](https://github.com/bdlukaa/fluent_ui/assets/53848311/efff82de-4bc7-480c-9b8a-c54cdbdb6116)

**Additional context**
Here is my flutter version
![image](https://github.com/bdlukaa/fluent_ui/assets/53848311/2f431304-f82d-4933-865e-fd1208a6c591)

**Comment by bdlukaa** [comment]
It looks like your app was created in the master channel, but you're trying to run it using the stable channel. You can try to delete the `windows` folder and running `flutter create .` to recreate it

**Comment by DenisSba** [comment]
Thanks. Working!!
