### ISSUE TITLE
Add content padding parameter in Expander

### ISSUE THREAD

**Issue by harlanx** [bdlukaa/fluent_ui#891]
Currently the Expander widget uses 16px an all sides for the content child

**Describe the solution you'd like**
Add the content padding parameter (preferably EdgeInsets and not double type) in the Expander class.

**Additional context**
In WinUI 3 App example, custom content padding can be set
![image](https://github.com/bdlukaa/fluent_ui/assets/78299538/ecade17d-bd86-48ab-a9ed-8db18e31cf64)

**Comment by bdlukaa** [comment]
You are right, the content padding is hardcoded. It was due to [this property](https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/Expander/Expander_themeresources.xaml#L119)
