### ISSUE TITLE
🐛 Transparency on FilledButton and ToggledButton

### ISSUE THREAD

**Issue by robkri** [bdlukaa/fluent_ui#892]
**Describe the bug**
`FilledButton` and `ToggledButton` seem to use some transparency effect for their background color. See the color change of the same `AccentColor` on different backgrounds:
![AccentColor](https://github.com/bdlukaa/fluent_ui/assets/103884835/37c9033d-1cf6-4514-86c4-632dbac82e5d)
This is probably the same for other widgets that use `AccentColor` as background color.

**Expected behavior**
Whereas an unfilled `Button` should use white with an opacity of about 15% for dark mode (about 70% for light mode), the fill color of a `FilledButton` should always be `AccentColor` with 100% opacity. This is what all sources that I found so far imply.

**Comment by robkri** [comment]
Okay, I dove into this a little more and apparently, the accent color does change depending on the luminence of the current layer to keep the contrast the same. To achieve that they don't seem to use transparency though, as far as I can tell, but apparently some algorithm to calculate the accent color for each luminence: https://fluent-components.azurewebsites.net/?path=/docs/design-system-color-explorer--page

Using transparency might be just good enough.

**Comment by bdlukaa** [comment]
I am reopening this issue because, on native, the accent color for controls change depending on the theme. 

https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Common_themeresources_any.xaml#L163-L166
https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Common_themeresources_any.xaml#L379-L382

**Comment by bdlukaa** [comment]
Actually, the defined properties in microsoft-ui-xaml look outdated. I checked and the current implementation is paired with the native implementation
