### ISSUE TITLE
🐛 Flyout's close transition duration is different

### ISSUE THREAD

**Issue by harlanx** [bdlukaa/fluent_ui#893]
**Describe the bug**
When passing a custom duration to `transitionDuration` in `FlyoutContoller.showFlyout`, it only gets applied to the animation when opening the flyout.

**Screenshots**

|Duration.zero|Duration(seconds: 3)|
|-|-|
|![DurationZero](https://github.com/bdlukaa/fluent_ui/assets/78299538/b866deaf-11d9-4ae5-ab25-200f62a6a033)|![DurationThree](https://github.com/bdlukaa/fluent_ui/assets/78299538/4e3a7bf6-4052-42ad-93a7-7ea37411f062)|

**Comment by harlanx** [comment]
It might be the `reverseTransitionDuration` is not set and is using the default value `Duration(milliseconds: 300)` on the [PageRouteBuilder](https://api.flutter.dev/flutter/widgets/PageRouteBuilder-class.html) used in the [Flyout](https://github.com/bdlukaa/fluent_ui/blob/db39f70436ba3617a421a2bf914ffa6e9b3c36e4/lib/src/controls/flyouts/flyout.dart#L595C5-L595C5) class.

**Comment by bdlukaa** [comment]
The documentation on both transition duration properties led me to think that I only needed to set one. It is ambiguous.

(love your UI btw)
