### ISSUE TITLE
🐛 Tabs - On hover close button flickering

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#90]
**Describe the bug**
Using   fluent_ui: ^3.4.0, when mouse hovers on Tabs, the "X" close button flicks from grey to white. Maybe is some side effect of enabling/disabling the close button ?

**To Reproduce**
1. Go to https://bdlukaa.github.io/fluent_ui/ 
2. Click on 'Others'
3. Scroll down to the Tabs demo
4. Pass the mouse pointer over the tabs. The close button flicks and retains a darker grey background in comparison with the rest of the Tab.
5. Move the mouse again. The close button flicks again.

**Expected behavior**
I'm not expecting anything special

**Screenshots**
N/A

**Additional context**
N/A

**Comment by WinXaito** [comment]
More detail from #109 

> **Expected behavior**
> 
> ![fluent_ui_tabbar_expected](https://user-images.githubusercontent.com/8223773/143769990-8f23a5c5-7247-4fe4-b144-2d8ef342e22d.gif)
> 
> **Screenshots**
> 
> ![fluent_ui_tabbar](https://user-images.githubusercontent.com/8223773/143769945-1968ca3c-47cc-468d-94f9-49b45637b0cb.gif)
>

**Comment by henry2man** [comment]
Even though there are some new issues with tabs (https://github.com/bdlukaa/fluent_ui/issues/122), this specific change worked very well. Awesome!
