### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by Korzhukov** [bdlukaa/fluent_ui#900]
Link1 returns 404: https://pub.dev/documentation/fluent_ui/latest/

Link2 opens gray screen: "Read the [documentation](https://bdlukaa.github.io/fluent_ui/)"

**Comment by damywise** [comment]
link2 works for me

**Comment by robkri** [comment]
I experience the same issue as Korzhukov: The showcase is supposed to load, but only a gray screen with a faint logo is shown.

> link2 works for me, though it opens example/showcase, not documentation

Maybe it's still cached in your browser?

**Comment by damywise** [comment]
> Maybe it's still cached in your browser?

I tried in other browser, device, private mode, works everywhere

**Comment by Korzhukov** [comment]
Link2: Tried 3 different browsers in private window. All three are gray screen. Dev tools console says `NoSuchMethodError: method not found: 'toString' on null` in `js_primitives.dart:42`.
Anyway it is not a link to the documentation, but to a demo.

**Comment by bdlukaa** [comment]
I just pushed a commit. Can you check if the demo app is running fine?

**Comment by Korzhukov** [comment]
Demo works now. And the documentation available again. Thanks!

**Comment by robkri** [comment]
The demo app is running again, but the API documentation is still (or again?) not reachable (404). Checked it with different browsers on different machines.

As you can see, the link to the API reference is missing:
![grafik](https://github.com/bdlukaa/fluent_ui/assets/103884835/b61c8e9c-c9d5-4388-a161-e04d7efdae10)

**Comment by robkri** [comment]
@Korzhukov Is the documentation still available to you?

**Comment by Korzhukov** [comment]
> @Korzhukov Is the documentation still available to you?

It is 404 again.

**Comment by bdlukaa** [comment]
Unfortunately I don't have control over the https://pub.dev/documentation/fluent_ui/latest/ link and its result. Sometimes pub fails to analyze the project and the documentation is not properly generated. 

You can generate it manually: https://pub.dev/packages/dartdoc
