### ISSUE TITLE
Show AutoSuggestBox overlay when content is empty.

### ISSUE THREAD

**Issue by frg2089** [bdlukaa/fluent_ui#912]
**Is your feature request related to a problem? Please describe.**
I noticed this entry in the 4.7.2 changelog.

> - fix: AutoSuggestBox overlay is now only displayed after the user started typing (d95970a230b433f76085880b7f09f38e22c813b5)

I use it to displayed something like search history.
But now, it doesn't work.

**Describe the solution you'd like**
Is there anything that provides a way to provide a Suggest when the text is empty?
like
```dart
AutoSuggestBox({
  displayOverlayWhenClick: true
})
```

**Comment by bdlukaa** [comment]
I'd rather expose `AutoSuggestBoxState` to make it possible to open the overlay programatically. This way you could listen to the focus and show the overlay accordingly.

The native behavior is to only show the overlay when the user starts typing.

**Comment by bdlukaa** [comment]
This is fixed on https://github.com/bdlukaa/fluent_ui/commit/4b98f75e79710e6025937e8f69fa7f609fd7e7ed

The example app shows how to do it!
