### ISSUE TITLE
Change NavigationPane Button (Hamburguer)

### ISSUE THREAD

**Issue by danielreghin** [bdlukaa/fluent_ui#929]
Is there a way of changing the default hamburguer icon for opening the NavigationPane? 
Tried to find a NavigationPaneThemeData properties but without success .

The reason that I want it is that I will have two NavigationPane one on top of another. The upper one will change the application modules and the bottom one will change the pages inside a module. I want the upper menu to have a differnt icon instead the hamburguer.

Is that possible?

![image](https://github.com/bdlukaa/fluent_ui/assets/44054763/82c3e434-7420-43a1-ace6-7733faa45e55)
![image](https://github.com/bdlukaa/fluent_ui/assets/44054763/c0c28a9f-2af6-452f-96e8-f5c3169b4959)
![image](https://github.com/bdlukaa/fluent_ui/assets/44054763/eb908716-6306-4dff-9623-be759559aef1)

**Comment by bdlukaa** [comment]
Currently, it is not possible.

#### Additional resources
* https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/navigation_view/view.dart#L363C13-L382

**Comment by danielreghin** [comment]
Thanks. It worked. Otherwise, I couldn't change the Icon color as the parameter that you've put it is a FluentIcon. 
But, i didn't tried hard to find if it is possible by another parameter. Will do that, if i'm not able to do that, i will open a new ticket. 

Best Regards.
