### ISSUE TITLE
🐛 TabView - shortcutsEnabled is not working

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#93]
**Describe the bug**
I'm not able to enable TabView shortcuts using `shortcutsEnabled: true`. I've tested both on Chrome and MacOS native.

**To Reproduce**
1. Setup a TabView with `shortcutsEnabled: true` 
2. Create some tabs
3. Press 1-8 (first to eighth tab), nothing happens
4. Press 9 (last tab), nothing happens
5. Press Ctrl + W (using MacOS), nothing happens

**Expected behavior**
As documented, the shortcuts lets the user navigate through the tabs. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by henry2man** [comment]
Related to  https://github.com/bdlukaa/fluent_ui/issues/15 ?

**Comment by WinXaito** [comment]
@bdlukaa the commit f3bc01a fix this issue ? Can be closed ?

**Comment by bdlukaa** [comment]
I couldn't make shortcuts working, that's why I didn't close it.

**Comment by WinXaito** [comment]
Waiting to have this in stable: https://github.com/flutter/flutter/pull/93693

And after that, add a `Focus(autofocus: true, child: tabBar)` here: https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/navigation/tab_view.dart#L294

**Comment by labulakalia** [comment]
i add textfiled to bodies, when textfiled input get focus,shortcut is worker,when loss focus, shortcut not is worker

**Comment by labulakalia** [comment]
@henry2man https://github.com/mdctable/fluent_ui/blob/fabf8698205c811b8a5d1e55f95f4d892349e308/lib/src/controls/navigation/tab_view.dart#L512
i add `Focus` to bodies, it work

**Comment by WinXaito** [comment]
> @WinXaito How can we know if this issue is included in latest 3.0.x version of Flutter?
> 
> Maybe we can fix this now here.

Seems to be different in 3.1.0: https://github.com/flutter/flutter/blob/3.1.0/packages/flutter/lib/src/widgets/shortcuts.dart#L1033-L1042

And the PR: https://github.com/flutter/flutter/pull/93693/files#diff-8993c409f9f79bcf62387d9f603fa69c2178163e84a697819af5bec956a3384eL1007-R1012

so I think there was another pull request behind it. So maybe that fixes the problem?

(this PR was the last change: https://github.com/flutter/flutter/pull/100167)

**Comment by bdlukaa** [comment]
Shortcuts are working on TabViews
