### ISSUE TITLE
Plans for supporting Fluent 2?

### ISSUE THREAD

**Issue by dmacan23** [bdlukaa/fluent_ui#930]
**Describe the solution you'd like**
I love how the new Fluent 2 looks and it would be great to see it in action in Flutter as well. Are there any plans on upgrading this to support Fluent 2?

**Additional context**
[Official Fluent2 website](https://fluent2.microsoft.design/)

**Comment by bdlukaa** [comment]
Hello! The link you mentioned links to the "Web React" version of `fluent_ui`.

The main goal of this project is to replicate Win UI, which is described under the link below:

  * https://fluent2.microsoft.design/components/windows

I think this is a duplicate of #907
