### ISSUE TITLE
How to set AppBar for ScaffoldPage

### ISSUE THREAD

**Issue by TENX-S** [bdlukaa/fluent_ui#941]
In my situation, I only require a single page without a `NavigationView`. However, I am unable to find a property that allows me to position my window buttons using an `AppBar` in `ScaffoldPage.scrollable`.
I am aware of the existence of the header property, but it does not appear to be ideal:
![image](https://github.com/bdlukaa/fluent_ui/assets/40336192/173c5e82-db65-4ee7-bed7-07155dc4e714)

**Comment by bdlukaa** [comment]
Hello! You can create a `NavigationView` without a `pane`! The app bar is not independent and depends on the navigation view.

**Comment by TENX-S** [comment]
Thank you!
