### ISSUE TITLE
ComboboxItem disabled property.

### ISSUE THREAD

**Issue by Piero512** [bdlukaa/fluent_ui#949]
**Is your feature request related to a problem? Please describe.**
I am in the process of creating a desktop app that has customizable options, and I wanted to show a greyed out combobox option that could not be selected, with an additional tooltip explaining why that item is not selectable.

**Describe the solution you'd like**
I would love that the ComboboxItem class be updated to carry a disabled/enabled property that would style the Text or any other widget of the Combobox item, so that item will tell the user that is not a selectable option, but it could be supported if circunstances change. Although that might not be in compliance with WinUI3 and stuff, so a similar class like [CommandBarBuilderItem](https://pub.dev/documentation/fluent_ui/latest/fluent_ui/CommandBarBuilderItem-class.html)  would be acceptable.

**Describe alternatives you've considered**
Trying to cancel the onTap on the Selected State and raising a dialog explaining why the option can't work. Displaying only the currently supported options.

In my specific case, I could just remove from the option selector, say, the use CUDA option if my code detects that there isn't an NVIDIA GPU installed.

**Additional context**

**Comment by bdlukaa** [comment]
Added `ComboboxItem.enabled`. If you set it to false, the tap method is not invoked.

To create a custom combobox item, you can extend the `ComboboxItem` and override the `build` method.

```dart
final MyItem extends ComboboxItem {

  ...

  @override
  Widget build(BuildContext context) {
    return Tooltip(
      message: .....,
      child: super.build(context),
    );
  }

}
```
