### ISSUE TITLE
[Question/Proposal] NavigationBody and state preservation

### ISSUE THREAD

**Issue by henry2man** [bdlukaa/fluent_ui#95]
I'm using `NavigationView`, a `NavigationPane` with menu entries and a `NavigationBody`.

Looking into the source code, it looks that every time I change the main `index` the associated `children[index]` is **rebuilt from scratch**. But, in my case, I wish there were some kind of state preservation.

I've added `AutomaticKeepAliveClientMixin` to every children but every time I change the page using the menu the previous state is lost.

Is there a known way to preserve state when switching between menu options? If not, I think it would be great to add this option to `NavigationBody`.

At the moment I think I am going to try to use a `PageView`, where I do have experience maintaining the state between changes.

Here it is a sample code:

```dart
import 'package:fluent_ui/fluent_ui.dart';

void main() {
  runApp(MainScreenTest());
}

class MainScreenTest extends StatefulWidget {
  MainScreenTest({Key? key}) : super(key: key);

  @override
  State<MainScreenTest> createState() => _MainScreenTestState();
}

class _MainScreenTestState extends State<MainScreenTest> {
  int index = 0;

  @override
  Widget build(BuildContext context) {
    return FluentApp(
      home: NavigationView(
          content: NavigationBody(
            index: index,
            children: [
              StatefulPage(title: "Screen 1"),
              StatefulPage(title: "Screen 2"),
              StatefulPage(title: "Screen 3")
            ],
          ),
          pane: NavigationPane(
            selected: index,
            onChanged: (i) => setState(() => index = i),
            // displayMode: PaneDisplayMode.top,
            items: [
              PaneItem(icon: Icon(FluentIcons.home), title: Text("Screen 1")),
              PaneItem(icon: Icon(FluentIcons.read), title: Text("Screen 2")),
              PaneItem(icon: Icon(FluentIcons.event), title: Text("Screen 3")),
            ],
          )),
    );
  }
}

class StatefulPage extends StatefulWidget {
  const StatefulPage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _StatefulPageState createState() => _StatefulPageState();
}

class _StatefulPageState extends State<StatefulPage>
    with AutomaticKeepAliveClientMixin {
  int counter = 0;

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Mica(
      child: Column(
        children: [
          Text(widget.title),
          Button(
            child: Text("Current: $counter - Press to increment!"),
            onPressed: () => setState(() => counter++),
          ),
        ],
      ),
    );
  }
}

```

**Comment by takifouhal** [comment]
use `IndexedStack` instead of `NavigationBody`.
but you need to be aware that `IndexedStack` loads all pages at the beginning , to overcome that you need to add a condition on the page  build method to  `currentIndex == pageIndex || pageLoadedAtLeastOnce`

**Comment by bdlukaa** [comment]
And it won't provide any animations (unless you do so)

**Comment by henry2man** [comment]
> And it won't provide any animations (unless you do so)

And would it be possible to reuse any of the animations in the package?

**Comment by bdlukaa** [comment]
Yes. You can use https://github.com/bdlukaa/fluent_ui/blob/538371720241b595dcc04cbcce4ea5227787ff10/lib/src/styles/motion/page_transitions.dart

**Comment by henry2man** [comment]
> IndexedStack

@takifouhal Thanks! `IndexedStack` worked like a charm as a 1:1 direct replacement of `NavigationBody`. 
@bdlukaa Thanks for the tip. In my use case for now I think I'll go without animations because is some kind of backend UI and "instant switch" feels better than anything animated. 

Regarding this issue, do whatever you want. If you consider this kind of feature useful, leave it open; if not, please close it.

Thanks for your time guys.

**Comment by henry2man** [comment]
As I'm happy using `IndexedStack` I'm going to close this. Thanks!

**Comment by bdlukaa** [comment]
Reopening as a valid request!

**Comment by alimsk** [comment]
hi, how do i use transition in `IndexedStack`?
an example would be useful :slightly_smiling_face:

**Comment by bdlukaa** [comment]
Wrap your `IndexedStack` in a `AnimatedSwitcher`. Something like the following:

```dart
int index = 0;

AnimatedSwitcher(
  transitionBuilder: (child, animation) {
    return DrillInPageTransition(child: child, animation: animation);
  },
  child: IndexedStack(
    key: ValueKey<int>(index),
    currentIndex: 0,
    children: [...],
  ),
)
```

**Comment by Spsden** [comment]
I also had the same problem and  Pageview works absolutely fine. Although I have not been able to find a way to preserve state when the app switches PaneDisplayMode. Is there any fix for that ?

**Comment by bdlukaa** [comment]
I could check how `PageView` implements it and try to replicate

**Comment by Spsden** [comment]
> I could check how `PageView` implements it and try to replicate

Sure,
Here's an implementation in my repository 
https://github.com/Spsden/Drip/blob/master/lib/main.dart

Thanks for the excellent work you are doing.

**Comment by jonahzheng** [comment]
class MyViewPageState extends State<SshViewPage> with AutomaticKeepAliveClientMixin{
..................

  @override
  bool get wantKeepAlive => true;
}

**Comment by henry2man** [comment]
> I've added `AutomaticKeepAliveClientMixin` to every children but every time I change the page using the menu the previous state is lost.

As I said in the issue description, I tried this solution without success but, TBH, since I moved to the solution with `IndexedStack` (https://github.com/bdlukaa/fluent_ui/issues/95#issuecomment-985279730) I have not retested the issue using this possibility again.

**Comment by bdlukaa** [comment]
I was able to keep the state on the example app. Take a look

**Comment by henry2man** [comment]
Sounds great! I'll take a look because this will let me use page transitions easily...

Giving the fact that we have a working solution, you can close this issue if you're happy too.

**Comment by MasterHiei** [comment]
@bdlukaa Hi! Could you give me more details about https://github.com/bdlukaa/fluent_ui/issues/95#issuecomment-1166542393? 
In my case, I'm using provider but those will be recreated evevry time I switch the pane.

**Comment by bdlukaa** [comment]
@MasterHiei what if you create your provider above your `NavigationView`?

**Comment by MasterHiei** [comment]
@bdlukaa It's not bad:+1: 
In riverpod 2.0, `cacheTime` also worked for me but I would like to use it. Thanks.
