### ISSUE TITLE
🐛 The text selection should disappear if the text doesn't have the focus.

### ISSUE THREAD

**Issue by TENX-S** [bdlukaa/fluent_ui#952]
**Describe the bug**
If a `SelectableText` is selected and you click elsewhere, the selection is not gone. In fact, it is possible to have multiple text selections simultaneously.

<img width="551" alt="image" src="https://github.com/bdlukaa/fluent_ui/assets/40336192/a5083023-5c98-4a71-91b4-a3e8320458cb">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bdlukaa** [comment]
We do not maintain `SelectableText`. Please, file an issue under the `flutter/` repo
