### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by 8floven8** [bdlukaa/fluent_ui#954]
### how to add this:

fluent_ui:git:
       https://github.com/bdlukaa/fluent_ui.git

### where it needs to be assigned specifically, I get an error when checking packages:

[fluent_ui-master] flutter pub get --no-example
Resolving dependencies...
Error on line 23, column 3 of pubspec.yaml: A package may not list itself as a dependency.
    ╷
23 │ fluent_ui:
    │ ^^^^^^^^^
    ╵
exit code 65)

### and how i need to start this ui:

The following devices were found, but are not supported by this project:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3448]
Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
Edge (web)        • edge    • web-javascript • Microsoft Edge 118.0.2088.61
If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.

### don’t choke me, unfortunately I don’t really understand this, I’m just starting out, I can’t find information anywhere, please tell me what actions need to be carried out from beginning to end

**Comment by bdlukaa** [comment]
Can you try to run `flutter clean`; `flutter pub get`

**Comment by 8floven8** [comment]
but where i beed to put this:?
dependencies:
  fluent_ui: ^4.4.0

OR

dependencies:
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git

**Comment by bdlukaa** [comment]
Hmm, I see. You're trying to add the `fluent_ui` dependency to the `fluent_ui` project? 

You probably want to create a new project and add the `fluent_ui` dependency to it. You can do so by running:

```terminal
flutter create app
flutter pub add fluent_ui
```

**Comment by 8floven8** [comment]
but why was the code written on Github, is it needed for some import or something else, or do I just need to download everything from the Internet (vs code, git, dart), can you describe to me the sequence for installing flutter for further use in their future software pls

**Comment by milindgoel15** [comment]
> or do I just need to download everything from the Internet (vs code, git, dart), can you describe to me the sequence for installing flutter for further use in their future software pls

Hello, since you are starting out on flutter, you should:

- first read or watch the introduction as to how to set up flutter in the first place. 
- check what stuff you need in flutter development beforehand and how they all work together.
- Learn the basics of flutter before jumping on to some UI kit.

> but why was the code written on Github, is it needed for some import or something else,

The code is provided for all flutter developers who want to add fluent UI kit to their app. 

Don't forget to start with the basics. Good luck :)

**Comment by 8floven8** [comment]
ty, but I’m really interested, please tell me how should I use this code on Github, how and where does it go?

**Comment by milindgoel15** [comment]
> ty, but I’m really interested, please tell me how should I use this code on Github, how and where does it go?

Again, please watch some basic tutorial first.  

Some video to help you start: https://youtu.be/CzRQ9mnmh44?si=huZ-4IpkWhcWs_zd
