### ISSUE TITLE
🐛 Background color of `SelectableText`'s context menu is transparent

### ISSUE THREAD

**Issue by Jhonfunk** [bdlukaa/fluent_ui#968]
![f](https://github.com/bdlukaa/fluent_ui/assets/78594391/2dd8ab75-42ab-497d-a6d6-36a55bc5f570)

**Comment by bdlukaa** [comment]
Similar to https://github.com/bdlukaa/fluent_ui/issues/952

We do not maintain `SelectableText`. You may want to display the fluent controls on `SelectableText`, [here's an example](https://github.com/bdlukaa/fluent_ui/blob/9497dee26e01ed4b15991bf1cd1947c95f5979a3/example/lib/screens/surface/expander.dart#L137-L148) of how to do so.
