### ISSUE TITLE
Button border 

### ISSUE THREAD

**Issue by juppdes** [bdlukaa/fluent_ui#976]
I can't remove the button borders. Any tips?

    Button(
        style: theme.buttonTheme.defaultButtonStyle,
        child: const SizedBox(
          width: 400, 
          height: 30, 
          child: DecoratedBox(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [Color(0xFFFF2A76), Color(0xff5532e8), Color(0xfffe9628)],
              ), 
            ), 
            child: Center(
              child: Text(
                'OK',
                style: TextStyle(color: Colors.white, fontSize: 16,),
              )
            )
          )
        ), 
        onPressed: () {},
    )

**Comment by bdlukaa** [comment]
You can use `ButtonStyle.shape` to change the border:

```dart
Button(
  style: ButtonStyle(
    shape: ButtonState.all(const RoundedRectangleBorder()), // can be any ShapeBorder 
  ),
),
```

Hope this helps :)

**Comment by juppdes** [comment]
Bruno, já que vi que és compatriota meu, escrevo em português mesmo.. 
obrigado pela ajuda, mas não tem jeito de tirar as bordas (devo estar deixando de ver algo).
No modelo acima que me passou, a borda do botão continua.. tentei algumas opções, mas sempre a borda continua.
Tens alguma orientação ou modelo onde a borda não aparece? Eu preciso mesmo do SizedBox e do DecoratedBox para poder aumentar o tamanho e as cores em gradiente, ou teria uma forma melhor?

**Comment by juppdes** [comment]
Tranquilo Bruno, só tenho a agradecer pelo ótimo trabalho!
