### ISSUE TITLE
🐛 Source code in showcase app not color-highlighted

### ISSUE THREAD

**Issue by dhafinrayhan** [bdlukaa/fluent_ui#981]
**Describe the bug**
In the showcase app, the source code for "A read-only TextBox with various properties set" is not color-highlighted.

**To Reproduce**
1. Go to https://bdlukaa.github.io/fluent_ui/#/forms/text_box
2. Click on 'Source code' below "A read-only TextBox with various properties set"
3. See that the source code is not color-highlighted

**Expected behavior**
Source code should be color-highlighted, the same way as the other source code is

**Screenshots**
![image](https://github.com/bdlukaa/fluent_ui/assets/49405411/40260191-4935-432f-95c8-3cd7aacb35d8)

**Comment by dhafinrayhan** [comment]
Apparently it's because of a typo, fixing it

**Comment by bdlukaa** [comment]
I did a quick search through the example app.

The [`InfoBar as a popup`](https://bdlukaa.github.io/fluent_ui/#/surfaces/info_bar) section is also poorly highlighted.
