### ISSUE TITLE
AutoSuggestBox validation

### ISSUE THREAD

**Issue by juppdes** [bdlukaa/fluent_ui#984]
Is there any way to require the value entered into an AutoSuggestBox to be a valid AutoSuggestBoxItem and trigger the onSelected event with the Enter key?

**Comment by bdlukaa** [comment]
You have control over the content of the auto suggest box content by providing a text `controller`. You can also pass the `noResultsFoundBuilder` parameter to build the dialog when no content is matched. 

The `onSelect` event is already triggered on the enter key.
