### ISSUE TITLE
🐛 Show error when MenuFlyoutItem onPressed

### ISSUE THREAD

**Issue by thitlwincoder** [bdlukaa/fluent_ui#991]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 1533 pos 12: 'scope != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ModalRoute.willPop (package:flutter/src/widgets/routes.dart:1533:12)
#3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5186:74)
#4      Navigator.maybePop (package:flutter/src/widgets/navigator.dart:2519:34)
#5      MenuFlyoutItem.build.<anonymous closure> (package:fluent_ui/src/controls/flyouts/menu.dart:273:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#23     _invoke1 (dart:ui/hooks.dart:328:13)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

**Comment by bdlukaa** [comment]
I can not reproduce this locally. From the stack trace, the state of your navigator has been somewhat lost.

Closing this! Please, report if it happen again
