### ISSUE TITLE
is posible to chang paneitem when selected? or hover

### ISSUE THREAD

**Issue by bagusandrewijaya** [bdlukaa/fluent_ui#992]
i want change color when paneitem is selected on navigationpane maybe red or yellow etc 
from this default fluent ui
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/ba8689d5-7f50-426a-9d3c-6f5812135ecf)
to this what i want
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/e96bbfe7-f141-4218-9676-c3f217e42905)
can anyone help me?

**Comment by bagusandrewijaya** [comment]
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/18ff91ca-0b84-4db1-9da8-38bdcda2b7d8)
SOLVED!



if someone have same problem like me you just need go to
lib\src\controls\navigation\navigation_view\pane_items.dart


and find bellow code 
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/a152fa51-15e0-44bd-9824-349a805f1aa5)
step 1
find boxconstraints 
step 2 wrap the widget use container and 
step 3 just add color and use iteration
selected == true ? Colora : colorb

**Comment by bdlukaa** [comment]
You can create your own pane item by extending a `PaneItem` - just like you'd do with a normal widget. See [this](https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart#L665-L701) for reference
