### ISSUE TITLE
🐛 Content Dialog issue

### ISSUE THREAD

**Issue by Sakthivel-bpigt** [bdlukaa/fluent_ui#994]
I'm trying to make a dialog using the Fluent UI Content dialog
My dialog has ComboBox with two options as first input parameter.
Based on that first input I have to design the rest of the dialog, which is going to have other input fields like Text box, more ComboBoxs etc.

My issue is, when ever I change my first input in the dialog the rest of the parameters are getting added again and again.
I tried to solve the problem but I couldn't figure it out.
Can you help me?

**Comment by bdlukaa** [comment]
It is hard to help when no code snippet or error message is provided. Please, follow the issue template.
