### ISSUE TITLE
when i try dynamic paneitem if just 1-2 item its not show error but when after 3 error showing  🐛 

### ISSUE THREAD

**Issue by bagusandrewijaya** [bdlukaa/fluent_ui#996]
i want like this
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/58882858-1b69-4adb-8a33-50d7ab0776c9)

but i make sure the key its not duplicate because i use uuidv4
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/7a9e891b-d6ea-4350-9bd7-4b82904ac9a0)

this
![image](https://github.com/bdlukaa/fluent_ui/assets/103176578/3aa01c22-7b53-4b80-8851-610c708beabc)

**Comment by bdlukaa** [comment]
I'm not sure whether this is an issue with the package. It looks more like an issue with your architecture. 

The error message and the snippet you provided are not helpful at all on solving this problem. Please, follow the issue template.

**Comment by bagusandrewijaya** [comment]
@bdlukaa thanks mate yes i wrong with my code thanks for attention
